### ISSUE TITLE
passport jwt token authentication

### ISSUE THREAD

**Issue by mtbvang** [SoftwareBrothers/adminjs#1004]
Is it possible to use express passport JWT token authentication with adminJS?

**Comment by davoscript** [comment]
Hello everyone. I wonder where a custom replacement for sessions with JWT would need to happen, it seems to me that sessions are "forced" here https://github.com/SoftwareBrothers/adminjs-expressjs/blob/d3352d3bc6fc1eafb20c79f83789d9034f1eef03/src/buildAuthenticatedRouter.ts#L69? 

Any guidance is much appreciated @dziraf. Thanks.

**Comment by rlamorea** [comment]
I am just going to say that it is ridiculous to dismiss this as "not planned". There is an obvious use case to allow for an external auth provider to generate a valid JWT for the AdminJS session (validated, for example, by checking `role` in the payload). This is just common sense.

I'll be sure to document my solution once I've got it working.
