### ISSUE TITLE
Add/delete databases while admin panel is running.

### ISSUE THREAD

**Issue by nicnacnic** [SoftwareBrothers/adminjs#1010]
Is it possible to add/delete new databases while the admin panel is running? I would like to be able to add new databases to the navigation bar when clicking a button for example. I took a quick look through the documentation but couldn't find anything relevant. Any ideas?

**Comment by dziraf** [comment]
Never tried that, `databases` is a part of server configuration. I assume you might be able to do it by triggering a custom REST endpoint which would e. g.:
1. Copy your AdminJS config
2. Add a new database to `databases`
3. Replace the original file with the updated one
4. Restart the server

But if you require this to be seamless, then no.
