### ISSUE TITLE
Access to resources gets a 302 status code that redirects to admin/login

### ISSUE THREAD

**Issue by marciondg** [SoftwareBrothers/adminjs#1014]
**Describe the bug**
When `NODE_ENV === 'production'`, adminJS doesn't works like development environments.
When I click on any resource from the sidebar, the GET request has a 302 status code and a alert raises:

> Your session expired. You will be redirected to login screen

![image](https://user-images.githubusercontent.com/53331055/153913125-c9ecb18c-0311-4e17-8efc-a120f845ab24.png)

![image](https://user-images.githubusercontent.com/53331055/153913210-c683bf92-b75e-4a82-a628-a4d3ffd0f547.png)

The request response redirects us to admin/login, so the session expires.
Why this behavior? When `NODE_ENV === 'staging'` or `NODE_ENV === 'development'` we don't have any error. Our admin panel works fine:

![image](https://user-images.githubusercontent.com/53331055/153913758-3a0ab012-e111-49b3-9480-bca86e24dd09.png)

**Installed libraries and their versions**

* adminjs@5.5.1
* @adminjs/express@4.0.1
* @adminjs/mongoose@2.0.0

**AdminJSOptions with schema**

```
  const router = AdminJSExpress.buildAuthenticatedRouter(
    adminJs,
    {
      cookieName: env.COOKIE_ADMIN_NAME,
      cookiePassword: env.COOKIE_ADMIN_PASSWORD,
      authenticate: async (user, password) => {
        // here goes the authentication logic
        (...)
      }
    },
    null,
    {
      resave: false,
      saveUninitialized: true
    }
  );
```

**Comment by dziraf** [comment]
You need a store where you save your sessions.

**Comment by AllounSalah** [comment]
Did you find any solution on how to do this with redis or anything?
I've been trying for weeks now with no avail on (NestJs).

**Comment by Boredude** [comment]
can you share an example with express and mongoose? I couldn't follow the example you shared

**Comment by tranghaviet** [comment]
@Boredude you can follow this. AdminJS and Admin Bro are quite similar
```js
const adminRouter = AdminJSExpress.buildAuthenticatedRouter(
  adminJS, // new AdminJS(resources:[models...], rootPath: '/admin')
  {
    authenticate: async (email, password) => {
      const user = await models.User.findOne({ email })
      if (user) {
        return user.isPasswordMatch(password) // return bcrypt.compare(password, user.password)
      }
      return false
    },
    cookieName: 'authentication',
    cookiePassword: process.env.ENCRYPTION_KEY,
    maxRetries: 5,
  },
  null,
  {
    resave: true,
    saveUninitialized: true,
    secret: process.env.ENCRYPTION_KEY,
    cookie: {
      httpOnly: process.env.NODE_ENV === 'production',
      secure: process.env.NODE_ENV === 'production',
    },
    name: 'authentication',
  }
)
```

**Comment by tranghaviet** [comment]
and others [Compatible Session Stores](https://github.com/expressjs/session#compatible-session-stores)

**Comment by JalalMitali** [comment]
> You need a store where you save your sessions.

can you explain please ?

**Comment by AaronDsilva97** [comment]
> You need a store where you save your sessions.

How to do it, can we get details explanation
