### ISSUE TITLE
There is no Box exported from adminjs

### ISSUE THREAD

**Issue by Chukstart** [SoftwareBrothers/adminjs#1026]
**Describe the bug**
The Documentation in this link 
https://docs.adminjs.co/tutorial-writing-react-components.html
It's not correct I tried to export Box but it's not there even Intelisense can't seem to find it 
This took a huge amount of my time please fix the documentation to avoid this happening to some other unsuspecting developer

```
import React from 'react'
import { Box } from 'adminjs'

const Dashboard = (props) => {
  return (
    <Box>My custom dashboard</Box>
  )
}

export default Dashboard
```

**Installed libraries and their versions**

* "adminjs": "^5.6.2",
*  "@adminjs/express": "^4.0.2"
* "@adminjs/mongoose": "^2.0.1",

**Comment by dziraf** [comment]
Tutorials are currently outdated, we've recently started updating the documentation to match with the latest versions of modules. I'll try to prioritise this

**Comment by CherryDT** [comment]
What should be used instead of `<Box>`?

**Comment by Chukstart** [comment]
@CherryDT If you have vsCode using intellisense it will suggest other components exported from adminjs

**Comment by dziraf** [comment]
Closing because we've updated the documentation: https://docs.adminjs.co
