### ISSUE TITLE
Updated version of design system brings dependency problem

### ISSUE THREAD

**Issue by kw-michal** [SoftwareBrothers/adminjs#1027]
Even though I got my adminjs version fixed (5.2.2), I received an error today when trying to install dependencies.
The error says:

```
  #10 194.6
  #10 194.6 npm ERR! peer dep missing: react@17.0.2, required by @adminjs/design-system@2.1.1
  #10 194.6 npm ERR! peer dep missing: react-dom@17.0.2, required by @adminjs/design-system@2.1.1
  #10 ERROR: executor failed running [/bin/sh -c npm i  && npm ls  && npm cache clean --force]: exit code: 1
  ```
  
  and it is caused by design-system library, which has updated peer dependency of reactjs in the commit:
  "Fit submodule to AdminJS dev workspace"
  https://github.com/SoftwareBrothers/adminjs-design-system/commit/53192f55a2a9418f323b110baf6e50f7326fe4d4
  

**Its not a minor change!** since adminjs is using caret symbol for this npm dependency, meaning that this update is introduced automatically. 

Please consider reviewing the strategy for versioning of adminjs and its child modules.

**Comment by damian-pastorini** [comment]
It seems we are all having similar issues because the different Reac versions between the core package an the sub-modules.
We opened a thread on Slack: https://adminbro.slack.com/archives/C010HE74G3X/p1645541017920519 

Even if you try all the latest versions in a clean installation the npm install fails on the dependecies requirements.

```
"@adminjs/design-system": "2.1.1",
"@adminjs/express": "4.0.3",
"@adminjs/upload": "2.0.2",
"adminjs": "5.7.0",
"react": "^17.0.2"
```

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: reldens@4.0.0-beta.19
npm ERR! Found: @adminjs/design-system@2.0.2
npm ERR! node_modules/@adminjs/design-system
npm ERR!   @adminjs/design-system@"2.1.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @adminjs/design-system@"2.1.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"17.0.2" from @adminjs/design-system@2.1.1
npm ERR!   node_modules/@adminjs/design-system
npm ERR!     @adminjs/design-system@"2.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
```
And not even downgrading most of the modules works, the install at some point may work, but for example AdminJSExpress.buildAuthenticatedRouter() will still fail on:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher ( src\node_modules\adminjs\node_modules\react\cjs\react.development.js:1476:13)
    at useMemo ( src\node_modules\adminjs\node_modules\react\cjs\react.development.js:1531:20)
    at I18nextProvider ( src\node_modules\adminjs\node_modules\react-i18next\dist\commonjs\I18nextProvider.js:16:34)
    at processChild ( src\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
    at resolve ( src\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render ( src\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read ( src\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString ( src\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)
    at html ( src\node_modules\adminjs\lib\frontend\login-template.js:73:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by dziraf** [comment]
I've just pushed triggered new release runs for core package and design system which should downgrade react to the version we previously used. We will most likely upgrade to v17 when we refresh design system components but it will be marked as a breaking change then.

**Comment by damian-pastorini** [comment]
@dziraf  did you fixed this in the design-system package as well? 2.1.1 still requires react 17.x.

**Comment by dziraf** [comment]
2.1.2 should be up

**Comment by grigory-js-ninja** [comment]
Problem is still exists (
```json
"dependencies": {
    "@adminjs/express": "^5.0.0",
    "@adminjs/typeorm": "^4.0.0",
    "adminjs": "^6.0.6",
    "class-validator": "^0.13.2",
    "cookie-parser": "^1.4.6",
    "dotenv": "^16.0.1",
    "express": "^4.18.1",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",
    "pg": "^8.7.3",
    "reflect-metadata": "^0.1.13",
    "typeorm": "^0.3.7"
  },
```

**Comment by dziraf** [comment]
@grigory-js-ninja version 6 of adminjs and version 3 of the design system package had been marked as a major release with breaking changes, so updating to React 18 is required and planned.

**Comment by CherryDT** [comment]
However, it requires a hardcoded version of react-router which in term requires React 17 and doesn't allow 18!
