### ISSUE TITLE
Admin Bro is not working

### ISSUE THREAD

**Issue by betsy-carshair** [SoftwareBrothers/adminjs#1033]
Admin bro is not working. I keep getting this error in the console. 
<img width="573" alt="Screen Shot 2022-02-28 at 4 35 11 PM" src="https://user-images.githubusercontent.com/83302546/156082339-e9c326db-32e9-4e5a-9780-765e583a3f6c.png">

**Comment by dziraf** [comment]
Are you sure you're not using outdated libraries? We rebranded to AdminJS almost a year ago
