### ISSUE TITLE
Adminjs not recognizing Non default schema

### ISSUE THREAD

**Issue by Yedidyar** [SoftwareBrothers/adminjs#1037]
I am coruntly using postgresql as my db. 

When I changing my schema from public to some over schema adminjs don't recognize the models as part of the new schema insted  when new query is executed it tries to "newSchema.myTable" and adminjs not recognizing it as one of the tables

**Installed libraries and their versions**

* adminjs@5.2.1
* @adminjs/express@4.0.3
* @adminjs/sequelize @2.1.1

**To Reproduce**

1. Bootstrap a regular adminjs postgres sequelize 
2. Create new schema in your db
3. Connect your models to schema in the definition 
4. Go to a model with at list one forgin key
Now you should get the error 

**Expected behavior**
A normal behavior like when connecting a project to adminjs

**the error massage**

`Error: there are no resource with given id "newSchema.tableName" this is the list of all register resources you can use:....... `

**Comment by dziraf** [comment]
> @adminjs/sequelize @1.4

Are you sure? There is no such version

**Comment by Yedidyar** [comment]
> > @adminjs/sequelize @1.4
> 
> Are you sure? There is no such version

Sori my mistake 2.1

**Comment by ZukLevinson** [comment]
Encountered a similar issue.

After configuring sequelize models with a schema, and loading the sequelize connection in the `AdminJS` config, AdminJS looks for resources only with the `tableName` - while having a resource with ID of `${schemaName}.${tableName}`.

Tried to configure the resources with configured ID, but had no progress.

**Comment by dziraf** [comment]
Can you try with `2.1.4`?

**Comment by Yedidyar** [comment]
@dziraf
It seems that the upgrade works. 
Thank very much 😄
