### ISSUE TITLE
Hide and Show Resources based on roles.

### ISSUE THREAD

**Issue by SwaroopS94** [SoftwareBrothers/adminjs#1038]
**Describe the problem feature solves**
Is there a way to hide the resources based on the current role of the user?

**Describe the solution you'd like**
We want to hide a particular resource if the role is not a admin role.

**Describe alternatives you've considered**
Currently we are controlling the field's visibility based on the role, but would be better if we can hide the entire resource based on the current role.

**Acceptance criteria**

**Comment by dziraf** [comment]
```
    {
      resource: InternalModel,
      options: {
        actions: {
          list: {
            isAccessible: ({ currentAdmin }) => currentAdmin.role === 'SUPER_ADMIN',
          }
        }
      }
    },
```
Have you tried something like that? Setting `isAccessible` to `false` hides the resource from the sidebar. If you add a similar `isAccessible` to other actions it will also disable them.

**Comment by SwaroopS94** [comment]
This is perfect, thanks!

**Comment by Akifcan** [comment]
if you need to hide href resources
use this
        ```
href: ({h, resource, currentAdmin}) => {
            return currentAdmin.endpoints.includes('admin')
                ? h.resourceActionUrl({
                      resourceId: resource.decorate().id(),
                      actionName: 'new',
                  })
                : null
        },
```
