### ISSUE TITLE
Automatic creation of slugs

### ISSUE THREAD

**Issue by aliazimoshan** [SoftwareBrothers/adminjs#1040]
Hi,
I create a store and use adminjs as an admin panel, which met all my needs,
the problem is for generating the URL slug and adding it to MongoDB.

My question is can I fill two properties with one field?
eg, get the name of the product from admins and replace dash(-) with spaces.

admin input
**_awesome admin panel_**

I store
**_awesome-admin-panel_**

Thanks for your attention.

**Comment by dziraf** [comment]
You can either create a custom component for the second property which watches for changes of the first property using `React.useEffect` and updates it's value accordingly.

Alternatively, if you don't need this to be dynamic, you can write a `before` hook for your action. The payload with changes is stored in `request.payload`. You can modify the payload as you want.
