### ISSUE TITLE
Add a custom route to the Router object

### ISSUE THREAD

**Issue by siorm2310** [SoftwareBrothers/adminjs#1043]
I am trying to add my own route with my own controller to the Router object but with no success.

I cannot find any code exmple for that in the documentation. However I did manage to found one [here](https://github.com/SoftwareBrothers/adminjs/issues/229)

My use case is a custom component that needs to preview a record which is related to the current one. I tried to use a method from the sequelize's DAL layer (in the component), but an exception has risen: ```Error: Element Type invalid... No name was provided for external module {nodejs_module_name} in output.globals - guessing {nodejs_module_name}``` . With that said, the main problem with my implementation imo is a nodeJs function that isn't bundled into the component.

I'm wondering if the referenced issue can be helpful by creating an API endpoint for sequelize's DAL operations.

**Comment by dziraf** [comment]
Not sure I understand but you should be able to add routes using your server framework, e. g. express:

```
adminRouter.get(<path>, <handler)
```

> I tried to use a method from the sequelize's DAL layer (in the component)

Sequelize is not a frontend/browser library so it's normal it throws that error.
