### ISSUE TITLE
AWS Elastic Beanstalk Deployment impossible

### ISSUE THREAD

**Issue by playleaks** [SoftwareBrothers/adminjs#1046]
**Describe the bug**
When adding the adminjs package to the node_mules of a fastify app (not yet using it in the app), and deploying to AWS Elastic Beanstalk (with node environment) AWS refuses to boot ending up in a severe error.
Startup of AWS machine results imopossible.

**Installed libraries and their versions**

* adminjs@5.7.3

**To Reproduce**
1. Add adminjs@5.7.3 to your fastify app
2. Deploy to AWS elastic beanstalk

**Expected behavior**
AWS server start without errors

**Screenshots**

**AdminJSOptions with schema**
no options defined yet

**Comment by dziraf** [comment]
What's the error? Please share more details, we won't be able to reproduce since we're not using elastic beanstalk anywhere in our apps currently.

**Comment by playleaks** [comment]
For sure. The error happens during the machine init scripts (eb-cfn-init) but it's quite difficult to determine the exact problem.
This is the only log I have access to (the underlying EC2 machine logs):

<img width="1686" alt="Schermata 2022-03-11 alle 14 24 11" src="https://user-images.githubusercontent.com/100738729/157876019-e1f88206-bba6-4c19-8470-c2ff47bbad22.png">

This is the final status of the EBS environment screen:

<img width="1684" alt="Schermata 2022-03-11 alle 14 23 24" src="https://user-images.githubusercontent.com/100738729/157875649-58bf3010-5080-4a67-892f-5bb2ab1166fc.png">


I am trying to debug in every possible other way, but AWS is quite a black box : since it's not even able to complete the bootstrap phase I am not able to ssh into the EC2 underlying machine to inspect logs, and the high level ElasticBeanstalk logs are ofc not accessible.
 

I have tried even with an old version adminjs@4.0.1 that I had to build manually and import as a folder package, but I have the same issue.
Locally everything works fine, but when deployed to AWS I get this failure. Of course if I remove the AdminJs package dependency the deploy runs flawlessly and the fastify app runs well.


I cannot tell what's the issue , that's why I ask your help.
But since even not using the adminJs module and only installing it I get this problem , I suppose that maybe some dependencies in the node_modules may be creating some issues in the EBS initialization scripts.

**Comment by dziraf** [comment]
My guess is that it happens because AdminJS bundles custom components on server's startup by default, which in turn creates `.adminjs` directory and this is what could be failing.

Can you try to:
1. Use `@adminjs/bundler`:
https://docs.adminjs.co/module-@adminjs_bundler.html
https://github.com/SoftwareBrothers/adminjs-bundler
2. Make sure you start the server with `ADMIN_JS_SKIP_BUNDLE="true"`. `"true"` must be a string, not a boolean. Also it's advised to use `NODE_ENV=production` for remote envs and use alternative env to differentiate environments. Without `NODE_ENV=production` AdminJS uses development bundles which are not minified

**Comment by playleaks** [comment]
But I didn't really understand how to use the @adminjs/bundler.
Should I just add it to my packages , or should I use it somehow in the code? The example is not really clear.

**Comment by playleaks** [comment]
I tried to put the environment variables and to install bundler, but I didn't solve anything.

Unfortunately I am afraid there is an issue of big memory leakage in one of your NPM modules dependencies, during 

> npm install

:

As visible in the screens below:

<img width="1779" alt="Schermata 2022-03-11 alle 16 02 25" src="https://user-images.githubusercontent.com/100738729/157894727-388524e1-648f-404b-a8c8-d3ed5ded4359.png">

<img width="1779" alt="Schermata 2022-03-11 alle 16 10 44" src="https://user-images.githubusercontent.com/100738729/157894738-a6c87877-7e9f-4366-8ce3-20baa332b3ac.png">

Thanks
