### ISSUE TITLE
Problems with relation and nested resources

### ISSUE THREAD

**Issue by KristinaErdman** [SoftwareBrothers/adminjs#1050]
Hi, I tried to display related resources in the admin panel.
NestJs and TypeOrm.
Entitties:
```
import { Entity, Column, PrimaryGeneratedColumn, OneToMany, BaseEntity } from 'typeorm';

import { FeatureValue } from './feature-values';


@Entity({ name: 'feature' })
export class Feature extends BaseEntity{
  @PrimaryGeneratedColumn()
	id: number;

  @Column({ length: 150, unique: true })
	name: string;

  @OneToMany((type) => FeatureValue, (value) => value.feature)
	values: Array<FeatureValue>;
}
```

```
import { Entity, Column, PrimaryGeneratedColumn, ManyToOne, BaseEntity, RelationId } from 'typeorm';

import { Feature } from '../feature.entity';


@Entity({ name: 'feature_value' })
export class FeatureValue extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  value: string;

  @ManyToOne((type) => Feature, (feature) => feature.values, {
    cascade: true,
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
    nullable: false,
  })
  feature: Feature;

  @RelationId((value: FeatureValue) => value.feature)
  featureId: number;
}
```
In app.module.ts
```
import { AdminModule } from '@adminjs/nestjs';
import { Database, Resource } from '@adminjs/typeorm';
import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import AdminJS from 'adminjs';

import { Feature, FeatureValue } from './features';


AdminJS.registerAdapter({ Database, Resource })

@Module({
  imports: [
    TypeOrmModule.forRoot(),
    // any modules
    AdminModule.createAdmin({
      adminJsOptions: {
        rootPath: '/admin',
        resources: [
          {
            resource: Feature, options: {
              properties: {
                values: { type: 'mixed' },
              }
            }
          },
          { resource: FeatureValue },
        ]
      }
    }),
  ],
  controllers: [],
  providers: [],
})
export class AppModule { }
```

Creation and filtering work correctly. 
<img width="1724" alt="Снимок экрана 2022-03-15 в 11 48 59" src="https://user-images.githubusercontent.com/77478361/158309736-822910d0-08f2-4ba2-a156-d0c633f1f532.png">

But when you browse, you don't see any linked resources.
<img width="1722" alt="Снимок экрана 2022-03-15 в 11 57 41" src="https://user-images.githubusercontent.com/77478361/158310254-7698f980-0975-4b35-ac69-808970eb065c.png">
<img width="1720" alt="Снимок экрана 2022-03-15 в 11 49 29" src="https://user-images.githubusercontent.com/77478361/158310261-3d80a872-a52e-4fba-bb4c-bf51d060b170.png">
<img width="1713" alt="Снимок экрана 2022-03-15 в 12 06 32" src="https://user-images.githubusercontent.com/77478361/158310474-d9e83668-8720-41e3-ae9d-34be509ff344.png">

An error occurs during the update.
<img width="1726" alt="Снимок экрана 2022-03-15 в 11 54 24" src="https://user-images.githubusercontent.com/77478361/158310337-b8ce28be-f898-4387-a71c-fbcc5d3f5633.png">

**Comment by pratikkapadia5** [comment]
I am also having the same issue. Followed the same as provided in documentations and added RelationId in ManyToOne but the relationId in AdminJS is empty

**Comment by dziraf** [comment]
Add `@Column()` decorator above your foreign key, i. e.:

```
  @RelationId((value: FeatureValue) => value.feature)
  @Column()
  featureId: number;
```

**Comment by KristinaErdman** [comment]
> @Column()

Thank you so much! It worked!
How can I add related resources to a page? For example, on a Feature page, can I add all the FeatureValues related to it?


> Add `@Column()` decorator above your foreign key, i. e.:
> 
> ```
>   @RelationId((value: FeatureValue) => value.feature)
>   @Column()
>   featureId: number;
> ```

**Comment by dziraf** [comment]
`1:m` and `m:n` relations are currently not populated by default. I'm trying to figure out how to implement this while supporting different ORMs. Meanwhile, you can create your own custom components and actions to handle that.

**Comment by KristinaErdman** [comment]
> `1:m` and `m:n` relations are currently not populated by default. I'm trying to figure out how to implement this while supporting different ORMs. Meanwhile, you can create your own custom components and actions to handle that.

Thank you

**Comment by thefelixno** [comment]
if you're looking for a quick and (very) dirty workaround for many-to-many, this works for me:

Entity:
`  @Field(() => [NodeRelationModel])
  @ManyToMany(() => NodeRelationModel, (nodeRelation) => nodeRelation.nodes, {
    // is eager on other side
    eager: true,
    cascade: true,
  })
  @JoinTable()
  relations: NodeRelationModel[];

  // for adminjs
  @RelationId((node: NodeModel) => node.relations)
  // must be column to call handler on it
  @Column('simple-array', { nullable: true })
  overrideRelationsById?: string[] | null;`

add an event subscriber to beforeUpdate:
`  // add relations from relationsId field
  // this allows adminJS to manage many-to-many relationships
  async beforeUpdate(event: UpdateEvent<NodeModel>): Promise<any> {
    const node: NodeModel = event.entity as NodeModel;
    // relationId is empty -> nothing to do here
    if (node.overrideRelationsById === null) return;

    // for dev only: indicate we changed this item
    node.intro = 'cleared by subscriber';
    // clear relations, so we can overwrite with only those from relationsId
    node.relations = [];
    for (const id of node.overrideRelationsById) {
      try {
        console.log(id);
        const relation = await event.manager.findOneBy(NodeRelationModel, {
          id: id,
        });
        node.relations.push(relation);
      } catch (e) {
        throw new UnprocessableEntityException(event.entity);
      }
    }

    // clear relationsid to avoid double calling of this listener
    node.overrideRelationsById = null;
    // save relations in db
    await event.manager.save(node);

    return node;
  }`

view overrides in adminjs:
`
export const NodeResource: ResourceWithOptions = {
  ...
  options: {
    ...
    properties: {
      overrideRelationsById: {
        isArray: true,
        reference: 'NodeRelationModel',
      },
    },
    actions: {
      edit: {
        before: [validateRelationsHandler],
      },
    },
  },
};
`

this requires a lot of unnecessary db operations, but is the quickest way I have found.

**Comment by lpbonomi** [comment]
> `1:m` and `m:n` relations are currently not populated by default. I'm trying to figure out how to implement this while supporting different ORMs. Meanwhile, you can create your own custom components and actions to handle that.

Any news on this?

**Comment by dannicada** [comment]
> Add `@Column()` decorator above your foreign key, i. e.:
> 
> ```
>   @RelationId((value: FeatureValue) => value.feature)
>   @Column()
>   featureId: number;
> ```

another way to go about it is to add `{eager: true}` to the relation options (if you don't mind the related entity being loaded as well) like so:
```
@ManyToOne((type) => Feature, (feature) => feature.values, {
    cascade: true,
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
    nullable: false,
    eager: true,
  })
  feature: Feature;
```
  
  then you can remove "featuredId" entirely if it's not useful in your application logic.
  
  Found this helpful in my case.
