### ISSUE TITLE
Can I use ckeditor instead of richtext?

### ISSUE THREAD

**Issue by KristinaErdman** [SoftwareBrothers/adminjs#1051]
Can I use ckeditor instead of richtext?

**Comment by dziraf** [comment]
You can create your own custom component and use any editor that you wish for specific inputs

**Comment by KristinaErdman** [comment]
Is it possible to configure the built-in richtext field to store images not in base64 format, but uploaded to the server?

**Comment by dziraf** [comment]
Not possible to configure but it should be possible to implement a custom handler which communicates with your REST endpoint to upload
