### ISSUE TITLE
Skipping array fields in edit action causes error in `prepareParams`

### ISSUE THREAD

**Issue by erkkah** [SoftwareBrothers/adminjs#1056]
**Describe the bug**
Leaving out an array field in edit by explicitly specifying `editProperties` will yield a null valued parameter input for that field.

This causes an issue on line 23 here:
 https://github.com/SoftwareBrothers/adminjs/blob/915a73dbbaf17c369d2783c945863ba883895fef/src/utils/param-converter/prepare-params.ts#L19-L23

The problem is that only `undefined` values are skipped on line 19, but null values make it to the call to `map`, which causes: 

```
TypeError: Cannot read properties of null (reading 'map')
```

**Installed libraries and their versions**

* adminjs@5.7.3
* @adminjs/koa@2.0.0
* adminjs-graphql@2.3.0 (Unreleased as of yet - since it is being updated to support newest adminjs core)

**To Reproduce**
Follow the steps in "Describe the bug" above.

**Expected behavior**
No error, and a nicely updated record.

**Comment by dziraf** [comment]
your fix to this issue has been released in `5.7.4`, thank you

**Comment by erkkah** [comment]
Great, that was fast! Thanks, @dziraf !
🍰 ☕
