### ISSUE TITLE
Show data  type object

### ISSUE THREAD

**Issue by aminekhalifa92** [SoftwareBrothers/adminjs#1065]
i want the show   data  the type object (mixed) ,in custom component, but every time i get the data from record.params in this format 
![image](https://user-images.githubusercontent.com/44671018/161045458-d18751c9-d9d6-439d-883b-9e6e01b40525.png)

this is my code : 
 "adminjs": "5.3.3",
  "@adminjs/express": "4.0.1",
  "@adminjs/mongoose": "2.0.0",
   "mongoose": "5.9.13",
mongoose Schema : 

   data: {
        type: Object,
    },
admin js resource :
![image](https://user-images.githubusercontent.com/44671018/161045825-2ba0e609-28cd-480a-bd55-d8b0b08a0ee9.png)

**i want to show the data like this :** 
![image](https://user-images.githubusercontent.com/44671018/161045596-899c264a-82d7-4543-b0ab-7244b314c42f.png)

**Comment by dziraf** [comment]
```
import { flat } from 'adminjs';

...
// somewhere in your component:
const unflattenedData = flat.unflatten(props.record.params);
```
