### ISSUE TITLE
How to use search action in resource panel?

### ISSUE THREAD

**Issue by weilitao** [SoftwareBrothers/adminjs#1067]
Hello,

From the doc, there is search action for resource. but in demo site and the site I built, I can't use search on resource panel (I have tried add `search: { isVisible : true }` to resource option, but only search button shown like custom action, no search query box and search function). From the doc, in order to enable search, I only need to set isTitle property. Did I miss something to enable search?

**Comment by dziraf** [comment]
Currently you can use filters panel to search records. The search action is used to search records on dropdown fields, e.g. you have a Product resource which is related to Category via categoryId. The categoryId property uses search to let you select a category.

**Comment by weilitao** [comment]
OK, thanks.
