### ISSUE TITLE
Can not upload file

### ISSUE THREAD

**Issue by IvanSeagull** [SoftwareBrothers/adminjs#1098]
**Describe the bug**

I need to attach files when I create a new record in a table. With empty files or files that have a small size, everything works perfectly. But for some reason, when you try to attach a pdf with a size of >3 mb, an error pops up in the panel. The console doesn't have it though. Therefore, I have a question: is there a default limit on the file size, and if there is one, is it possible to change it somehow?

**Installed libraries and their versions**

* adminjs@5.7.3
* @adminjs/upload@2.0.2
* @adminjs/express@4.1.0
* @adminjs/sequelize@2.1.5

Here is the code snippet where I handle file uploading
```
uploadFeature({
          provider: { local: { bucket: path.join(__dirname, '../public/trips') } },
          properties: {
            file: 'registration.file',
            filePath: 'registration.path',
            filename: 'registration.filename',
            filesToDelete: 'registration.toDelete',
            key: 'registration.key',
            mimeType: 'registration.mimeType',
            bucket: 'registration.bucket',
          },
          multiple: true,
          uploadPath: (record, filename) => `${record.id()}/registration/${filename}`,
        }),
```

**Comment by IvanSeagull** [comment]
Is that because of the file limit or something or it is just because of certain file @dziraf ?

**Comment by dziraf** [comment]
It shouldn't be the case of file size limit. AdminJS uses `express-formidable` which limits the maximum file size to 200MB by default.
