### ISSUE TITLE
Question: dynamic field visibility

### ISSUE THREAD

**Issue by xapro-dev** [SoftwareBrothers/adminjs#1100]
Hello!
How to change field "A" visibility based on field "B" value change?
The only way I suppose is to create custom component for both fields and use redux to link them together?

**Comment by dziraf** [comment]
You don't need redux, this is a similar question to: https://github.com/SoftwareBrothers/adminjs/issues/1087

**Comment by xapro-dev** [comment]
> You don't need redux, this is a similar question to: #1087

Thank you, but not that case. I need to change visibility not when resource loaded, but for example on clicking checkbox related to another field.
