### ISSUE TITLE
Datepicker is broken

### ISSUE THREAD

**Issue by IvanSeagull** [SoftwareBrothers/adminjs#1104]
The date and time picker doesn't work properly. When you choose today's date, you can put any time. But when you try to select another day, it sets the time to 00:00. When you try to change the time to another, it returns the date to today's date

**Installed libraries and their versions**

* adminjs@5.7.3
* @adminjs/express@4.1.0
* @adminjs/sequelize@2.1.5

**Here I've selected todays date and I can change time**
![image](https://user-images.githubusercontent.com/47693465/164545938-6fb0defb-39c8-4ea9-a143-7b1fef18777b.png)

**When I'm selecting others day, first of all it doesn't show which day I chose, second of all the time resets to 0**
![image](https://user-images.githubusercontent.com/47693465/164546054-299c7208-2f20-4edb-aaaa-860a6cc9fcf4.png)

**And when I'm trying to change time again the date is reset to today**

Please fix that

**Comment by dziraf** [comment]
This will be fixed in AdminJS v6 + Design System v3

https://user-images.githubusercontent.com/16668924/165273545-1a2c6ff2-26a9-499a-9a43-9daccaf2ab7a.mov

**Comment by Tevvek** [comment]
Also related to this, when submitting a date i.e. `2022-05-01 11:00` the database saves `2022-05-01 01:00`. I am in a timezone GMT+10, so I am guessing it is doing minus 10 hours to the actual saved time. Is this something I should handle in the database (PostgreSQL) or in AdminJS? Thanks!

**Comment by dziraf** [comment]
AdminJS sends the datetime as an ISO String to your backend so the database date should be saved in GMT+0 format.
