### ISSUE TITLE
Question: Search action filter by populated records

### ISSUE THREAD

**Issue by t1nky** [SoftwareBrothers/adminjs#1107]
I have 2 tables:

```
Users
id: number
settingsId: number @unique
```

```
Settings:
id: number
name: string
```

Is it possible to add filtering for settingsId dropdown at the Edit and New pages from the Users table, so the dropdown will only show those Settings that are not yet assigned to Users?

Basically, I want to change the list of items in the dropdown, so it will only show unused settings.

I'm using the latest adminjs and with prisma ORM.

**Comment by dziraf** [comment]
You would have to override the `handler` of `search` action in your `Settings` resource to achieve this.

https://github.com/SoftwareBrothers/adminjs/blob/master/src/backend/actions/search/search-action.ts
