### ISSUE TITLE
Hide Dashboard and redirect to resources

### ISSUE THREAD

**Issue by udayanss** [SoftwareBrothers/adminjs#1109]
Hello @dziraf , Can you please suggest me how can i redirect to my one of my resources(/admin/resources/Leagues) directly after login,i dont need the dashboard, below is my code

  const adminJs = new AdminJS({
    // databases: [connection],
    resources: [
      {
        resource: Leagues,
        options: {
          listProperties: ["name", "country"],
      },
]

    rootPath: "/admin",
  });
 const ADMIN = {
    email: "admin3@letsscout.co.in",
    password: "admin123",
  };

  const app = express();

  const router = AdminJSExpress.buildAuthenticatedRouter(
    adminJs,
    {
      cookieName: "adminjs",
      cookiePassword: "testtest",
      authenticate: async (email, password) => {
        if (ADMIN.password === password && ADMIN.email === email) {
          return ADMIN;
        } 
        }
        return null;
      },
    },
    null,
    {
      resave: false,
      saveUninitialized: true,
    }
  );

**Comment by dziraf** [comment]
Currently it isn't possible to remove the dashboard, you could create a custom component for the dashboard e. g.:
```
import React, { useEffect } from 'react';
import { useHistory } from 'react-router';

const Dashboard = () => {
  const history = useHistory();
  useEffect(() => {
    history.push(xxx);
  }, []);

  return null;
};

export default Dashboard;
```
but an empty dashboard might be displayed briefly before redirect happens.
