### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mariovojnichajduk** [SoftwareBrothers/adminjs#1125]
**Describe the bug**
I'm unable to login into admin panel on server (hosted on AWS), while on local everything works as it should. On server when I login, it just reloads the page, without any errors.

**Installed libraries and their versions**

    "adminjs": "^5.7.2",
    "@adminjs/express": "^4.0.1",
    "@adminjs/nestjs": "^3.0.1",
    "@adminjs/typeorm": "^2.0.0",
    "bcrypt": "^5.0.1",

**To Reproduce**

**Expected behavior**
Expected to login admin and let him enter the panel.

**Screenshots**

**AdminJSOptions with schema**

**Desktop (please complete the following information if relevant):**

**Smartphone (please complete the following information if relevant):**

**Additional context**

**Comment by nathanguigui** [comment]
https://github.com/SoftwareBrothers/adminjs/issues/669#issuecomment-1113280635
