### ISSUE TITLE
Custom component import css

### ISSUE THREAD

**Issue by etomarat** [SoftwareBrothers/adminjs#1128]
Hello!
I want to use a third party library for my custom adminjs component but it requires `css` or `scss` file to be imported. If I import css I get an error that I should use a plugin (which one?). How can I get out of the situation with little bloodshed?
Thanks for considering my request!

**Comment by es-lynn** [comment]
Not sure if anyone has a better way, but what I did was use `styled-components`, wrapped the imported 3rd party component into a container div, then used styled components to apply CSS to that container.

eg:

MarkdownPreview.tsx
```
const MarkdownPreview = ({ text }: MarkdownEditorProps) => {
  return (
    <MarkdownContainer>
      <MDEditor.Markdown source={text} />
    </MarkdownContainer>
  )
}

export { MarkdownPreview }
```

MarkdownContainer.tsx
```
const MarkdownContainer = styled.div`
  @media (prefers-color-scheme: light) {
    .wmde-markdown,
    .wmde-markdown-var {
      color-scheme: dark;
      --color-prettylights-syntax-comment: #8b949e;
      --color-prettylights-syntax-constant: #79c0ff;
      --color-prettylights-syntax-entity: #d2a8ff;
   ...
  // copy the code from the css file into here
```

**Comment by dziraf** [comment]
You can also use styled-component's `css`: https://github.com/SoftwareBrothers/adminjs-design-system/blob/master/src/utils/datepicker.styles.ts

and import it into your own styled component, but the end result is the same

**Comment by trangvu9** [comment]
Hey @dziraf, any idea to do this with scss? My custom component does import scss file.

Thanks
