### ISSUE TITLE
Inconsistent behaviour on `before` and `after` hooks

### ISSUE THREAD

**Issue by es-lynn** [SoftwareBrothers/adminjs#1129]
**Describe the bug**
All of the actions seem to have either 1 - 2 different phases. 
- The first phase is the `load_data` phase, where the data is loaded to display on the page.
- The second phase is the `process_data` phase, where data is sent from the client to the server to process.

However it seems like there's vastly inconsistent behaviour on when the `before` and `after` hooks are called. Sometimes it's called on the 1st phase, sometimes it's called on the 2nd phase, sometimes it's called on both.

This is confusing because the handlers are used for different purposes, sometimes for loading data and sometimes for processing. It's also confusing on the edit button as the handlers are being called twice. This also leads to some weird behaviour where you are able to modify data before it is rendered on `show, list, edit` but not on `new` actions.

**show**
```
// view single record
before()
load_data()
after()
```

**list**
```
// view listing
before()
load_data()
after()
```

**new**
```
// click on new button
load_data()
// click on create button
before()
process_data()
after()
```

**delete**
```
// click on delete button
before()
process_data()
after()
```

**edit**
```
// click on edit button
before()
load_data()
after()
// click on save button
before()
process_data()
after()
```

**Installed libraries and their versions**

- "@adminjs/express": "^4.1.0"
- "@adminjs/prisma": "^1.0.3"
- "@prisma/client": "^3.12.0"
- "adminjs": "^5.9.10"

**To Reproduce**

Modify all the actions of a resource to console.log during the before and after phases. Then monitor the console to see when the actions are triggered.

```
options: {
      properties: {},
      actions: {
        show: {
          before: async request => {
            console.log('before show')
            return request
          },
          after: (response: any, request: any) => {
            console.log('after show')
            return response
          }
        },
        new: {
          before: async request => {
            console.log('before new')
            return request
          },
          after: (response: any, request: any) => {
            console.log('after new')
            return response
          }
        },
        edit: {
          before: async request => {
            console.log('before edit')
            return request
          },
          after: (response: any, request: any) => {
            console.log('after edit')
            return response
          }
        },
        list: {
          before: async request => {
            console.log('before list')
            return request
          },
          after: (response: any, request: any) => {
            console.log('after list')
            return response
          }
        },
        delete: {
          before: async request => {
            console.log('before delete')
            return request
          },
          after: (response: any, request: any) => {
            console.log('after delete')
            return response
          }
        }
      }
    }
```

**Expected behavior**

My suggestion is to split into 6 separate handlers.
- `beforeLoad`
- `loadHandler`
- `afterLoad`
- `beforeProcess`
- `afterProcess`
- `processHandler`

For actions that are view only, such as `list` and `show`, they will only have the first 3 handlers.

This will make it clear and explicit which handler will be called during the different phases. It will also allow for more customization and flexibility as it allows developers to control when their code is called.

**Additional context**

I was looking for a way to be able to autofill values based on URL params when creating new records. 

ie: http://localhost:8080/resources/User/actions/new?params.name=Bob

I was exploring to see if I could use the `before` handler to inject the value into the component props. It seems like this is possible on `edit` actions as the `before` handler is called before rendering the page. However it's not possible on a `new` action as the `before` handler is not called before render.

**Comment by dziraf** [comment]
`load_data()` and `process_data()` are actually just action's `handler`.

The reason `new` action only has `load_data()` is because it only loads an empty form. There's no point in splitting this up into 6 separate hooks, we only need the frontend to run a `GET` request against `new` endpoint before displaying the form to preload values.
