### ISSUE TITLE
Question about complicated rows

### ISSUE THREAD

**Issue by IvanSeagull** [SoftwareBrothers/adminjs#1131]
I was checking demo of adminjs and found out that you can create complicated rows in model 

![image](https://user-images.githubusercontent.com/47693465/167815541-70d15404-fda8-493a-978a-eeb239e2b044.png)

I would like to know, is this feature only for mongodb resources or can I create something like that with postgreSql and Sequelize or Type Orms for example.

**Comment by dziraf** [comment]
This is available for all adapters but requires you to configure it using AdminJS (`type: 'mixed'`)

**Comment by dziraf** [comment]
Closing because of lack of response. If you still need help, leave a comment here or open a new issue.
