### ISSUE TITLE
RichText displays a question mark when I add a new line after a bold text

### ISSUE THREAD

**Issue by Ameendarwan** [SoftwareBrothers/adminjs#1139]
**Describe the bug**
RichText displays a question mark when I add a new line after a bold text.
Video Link: https://share.vidyard.com/watch/eeQBPsjdzb9WwgcrXdNNns?

**Installed libraries and their versions**

* adminjs@4.0.1
* @adminjs/express@2.0.0
* @adminjs/mongoose@1.4.0
... mongo, express (whatever you think is relevant)

**To Reproduce**

**Expected behavior**

**Screenshots**

**AdminJSOptions with schema**
Paste your AdminJS config with database schema if it could be related to the issue

**Desktop (please complete the following information if relevant):**

**Smartphone (please complete the following information if relevant):**

**Additional context**

**Comment by dziraf** [comment]
We're going to release AdminJS v6 and Design System v3 very soon which will use a different richtext editor (we change from Quill to TipTap). This issue should be fixed then.

**Comment by dziraf** [comment]
Closing in favour of https://github.com/SoftwareBrothers/adminjs/issues/963 for various richtext related issues
