### ISSUE TITLE
In resources, show only specific options to an array property based in one of its attributes

### ISSUE THREAD

**Issue by ZamurVedovatto** [SoftwareBrothers/adminjs#1141]
I'm filtering every list from every resource based in one specific attribute that the logged user has in common with the items.
But when one of this resources is an option to select on adding or editing an entity, this property shows every item from this another resource (not only the ones with the same "account" attribute with the currentAdmin).

As an example:
- User has an "account" attribute.
- Store has an "account" attribute.
- In the list of Stores, the logged user can only see the Store that has the same "account" attribute that he has.
- When creating a new Category (another resource) and the Store is one of its properties (an array of Stores is within the Category model), this logged user has to see only the Stores with its same "account" that he has, but every Store is showing to select.

How is it possible to filter the availableValues to a property based on one attribute from the items on the list and also the same attribute referencing the currentAdmin?

**Comment by dziraf** [comment]
You would have to create a `before` hook for your `search` action in `Store` resource which sets `request.query['filters.xxx']` based on `context.currentAdmin` data.
