### ISSUE TITLE
Computed title in Select component

### ISSUE THREAD

**Issue by etomarat** [SoftwareBrothers/adminjs#1143]
Hey! Can you please tell me how can I display a custom computed property in this list instead of `title`? This is a linked collection in MongoDB. Do I need to make my own custom `Select` component, or is there a way to change the existing one somehow?
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/710389/169671853-8175eb1b-6710-41a8-b113-b9bb9322cf93.png">

**Comment by etomarat** [comment]
@dziraf hello! The matter is that in my resource there is no necessary field. For example, I have `id` and I have `title` and I want to display `${id} ${title}` in Select. How to be in this case?

**Comment by all-bear** [comment]
@etomarat in a case if you are using TypeOrm and MySql you could achive it via virtual colums

```
@Entity()
export class Client extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;
  
  @Column()
  title: string;
  
  @Column({
    generatedType: "VIRTUAL",
    asExpression: "CONCAT(`firstName`, ' ', `lastName`, ' (', `email`, ')')",
  })
  resourceTitle: string;
}  
```

and after that you could use `isTitle: true` for column `resouceTitle`

**Comment by etomarat** [comment]
@all-bear thanks! But im using mongoDb :(
