### ISSUE TITLE
Any way to pass a session object in it's entirety ? 

### ISSUE THREAD

**Issue by AHarmlessPyro** [SoftwareBrothers/adminjs#1145]
**Describe the problem feature solves**
Currently the @adminjs/express with authenticated router has a session options parameter. Is there any way to pass in the session object as a whole or a boolean in case we have a session object already setup ?

**Describe the solution you'd like**
Ideally we'd be able to pass the session object or a boolean to indicate that the session object is already available at the expected location (request.session)

**Describe alternatives you've considered**
Not really sure what other alternatives could be here. It seems that adminjs defaults to memorystore if there isn't something passed.

**Acceptance criteria**
- [ ] A sessionOptions object is no longer necessary to access request.session at it's already populated at the expected location.

**Comment by AshotN** [comment]
Are you trying to setup a custom auth system?

You can set the session involved like so

```
app.post("/login", async (req, res) => {
  req.session.user = {...}
})


expressRouter.use((req, res, next) => {
  if (req.session && req.session.user) {
    req.session.adminUser = req.session.user
    next()
  } else {
    res.redirect("/mycustomlogin")
  }
})
```

**Comment by dziraf** [comment]
Closing because the issue is stale
