### ISSUE TITLE
Is there any way to show all fields in list?

### ISSUE THREAD

**Issue by leo900807** [SoftwareBrothers/adminjs#1146]
As titled, I saw "Let's say that you have a resource city with 20 fields like name, lat, lng, population, pollution, .... By default AdminJS will render first DEFAULT_MAX_ITEMS_IN_LIST which is 8. What if you want to present just 3 of them in a different order." in the official site.
May I show all fields by configuring or modifying code?

**Comment by es-lynn** [comment]
I believe you can simply list down every field in the `listProperties` configuration.

eg:
```
{
    resource: { model: dmmf.modelMap.City, client: prisma },
    options: {
      listProperties: ['name', 'lat', 'lng', 'population', 'pollution', 'item6', 'item7', 'item8', 'item9', 'item10'],
}
```

**Comment by dickorydock** [comment]
Thank you for this post. I had the same question but it took me a while to find the `listProperties` option.
