### ISSUE TITLE
Filters are removed during Drawer actions (create/edit/bulk delete)

### ISSUE THREAD

**Issue by es-lynn** [SoftwareBrothers/adminjs#1147]
**Describe the bug**

When viewing a filtered list of resources, if any action is opened within the drawer, then the filters are removed and the entire list of resources is visible.

**Installed libraries and their versions**

- "adminjs": "^5.10.3"

**To Reproduce**

1. Go to any resource (eg. 10 items total)
2. Apply a filter such that only some items are visible (eg. only 5 items out of 10 are visible)
3. Select multiple items, click on 'Bulk Delete'.
4. Now that the drawer is open, the filters have been removed, and all items are now visible again
5. After the items have been deleted, the filters are still removed and all items are visible

**Expected behavior**
1. If a filter or any URL params are present in the list view
2. If any action opens in a drawer
3a. Then the filters should still be present and the list should still remain filtered
3b. If an action is performed, then it should display to the list view with the original filters

**Screenshots**
<img width="904" alt="Screenshot 2022-05-31 at 23 39 52" src="https://user-images.githubusercontent.com/7008316/171215338-eea92b3e-8961-421c-bfb5-08a26accaeb1.png">

1. List of items are filtered by the letter 'F'.

<img width="905" alt="Screenshot 2022-05-31 at 23 40 07" src="https://user-images.githubusercontent.com/7008316/171215351-b642da24-f208-4281-a54c-f85552190d50.png">

2. After clicking on the 'Bulk Delete', drawer opens up, but filters are removed and the whole list is visible.

**AdminJSOptions with schema**
Please request if relevant.

**Desktop (please complete the following information if relevant):**
N/A

**Smartphone (please complete the following information if relevant):**
N/A

**Additional context**
- It might be useful to forward all query/search params when opening anything in a window.
- It might also be useful to pass in a flag to redirect back to the original URL after performing any action rather than always redirecting to the `/list` view.

**Comment by dziraf** [comment]
Just leaving a note that the bug still exists in v7.

**Comment by ZeroCho** [comment]
@dziraf I think this is because `filters` or `page` querystring is removed when clicking action buttons. I really need `filters` and `page` querystring to be preserved when clicking any kind of action buttons

**Comment by dziraf** [comment]
Hi, this has been fixed in one of recent versions
