### ISSUE TITLE
Login is eternally pending

### ISSUE THREAD

**Issue by chrisbasso** [SoftwareBrothers/adminjs#1148]
I already tried everything I found here to solve this problem.
I already tried to use bodyParser.json() or express.json() before or after the definition of the router

There are no error logs in the console.

"@adminjs/express": "^4.1.3",
"@adminjs/mongoose": "^2.0.3",
"adminjs": "^5.10.3",
"bcryptjs": "^2.4.3",
"body-parser": "^1.20.0",
"cookie-parser": "^1.4.6",
"cookie-session": "^1.4.0",
"cors": "^2.8.5",
"dotenv": "^16.0.1",
"express": "^4.18.1",
"express-formidable": "^1.2.0",
"express-session": "^1.17.3",
"jsonwebtoken": "^8.5.1",
"mongoose": "^5.13.13",

        AdminJS.registerAdapter(AdminJSMongoose);
	const adminJsOptions : AdminJSOptions = {
		resources: [UserResource, Role],
		rootPath: '/admin',
		databases: [db],
	}

	const adminJS = new AdminJS(adminJsOptions)

	const router = AdminJSExpress.buildAuthenticatedRouter(adminJS, {
		authenticate: async (email, password) => {
			const user = await User.findOne({ email })
			if (user) {
				const matched = await bcrypt.compare(password, user.password)
				if (matched) {
					return user
				}
			}
			return false
		},
		cookiePassword: 'some-secret-password-used-to-secure-cookie',
	})

	app.use(adminJS.options.rootPath, router)
	app.use(express.json());
	app.use(express.urlencoded({ extended: false }));

please help i really liked this library

**Comment by dziraf** [comment]
Have you tried setting up a session store like in this comment: https://github.com/SoftwareBrothers/adminjs/issues/669#issuecomment-1113280635 ? Not having it often casues issues for people.

**Comment by chrisbasso** [comment]
I had a cookie session for api routes that conflicted with the adminjs session. I put my cookie session after the admin route like this and it worked.

		adminRoute(app, mongoose)

		app.use(express.json());
		app.use(express.urlencoded({ extended: true }));
		app.use(
			cookieSession({ ....

Thanks for everything!
