### ISSUE TITLE
filter drawer colors

### ISSUE THREAD

**Issue by loagencydev** [SoftwareBrothers/adminjs#1152]
**Describe the problem feature solves**
the current issue is that the theming of the filter drawer is quite limited to colors that actually match with the `white` which is used for the headers in the filter drawer. It'd be awesome if the colors of the filter drawer would be customizable regardless of how the main dashboard or app colors are set.

**Describe the solution you'd like**
the easiest would be to have such thing:
```javascript
const theme = combineStyles({
	colors: {
		filterBg: "#fff",
		filterColor: "#000" // <- this should have effect on the labels, header (h3) and reset button
	},
});
```

**Describe alternatives you've considered**
so far i tried to actually override the components, but there was no luck

**Acceptance criteria**
to be able to style them as described

**Comment by dziraf** [comment]
Design system v3/core v6 should have more customization options related to themes
