### ISSUE TITLE
Delete record not working

### ISSUE THREAD

**Issue by goldylucks** [SoftwareBrothers/adminjs#1155]
**Describe the bug**
Everything seems to work out of the box except for deleting resource.
It prompts with a confirmation dialog to delete, and then confirming doesn't do anything, not firing any network requests.

**Installed libraries and their versions**
```
"@adminjs/express": "^4.1.3",
"@adminjs/mongoose": "^2.0.3",
"adminjs": "^5.10.4",
"express": "^4.18.1",
"express-formidable": "^1.2.0",
"mongoose": "^6.2.2",
"normalize-mongoose": "^1.0.0",
```

**To Reproduce**
1. create resource
2. initialize adminjs 
3. `npm run start`
4. create resource record through adminjs (works)
5. press delete button on the record
6. press confirm in the dialog
7. nothing happens 🤷‍♀️

**Expected behavior**
record should be deleted (or at least make a network call)

**Screenshots**
![adminjs](https://user-images.githubusercontent.com/6963212/174707521-ec8aec1c-31fd-4550-8308-612acaeb9688.gif)

**AdminJSOptions with schema**
```
import { Express } from "express"

import db from "./db"

const AdminJS = require("adminjs")
const AdminJSExpress = require("@adminjs/express")
const AdminJSMongoose = require("@adminjs/mongoose")
AdminJS.registerAdapter(AdminJSMongoose)

const adminJs = new AdminJS({
  // databases: [],
  rootPath: "/admin",
  resources: [db.User, db.Entry, db.Photo],
})
const router = AdminJSExpress.buildRouter(adminJs)

export default function registerAdmin(app: Express) {
  // this is the first thing being registered on the app, right after const app = express()
  app.use(adminJs.options.rootPath, router)
}

```

**Desktop (please complete the following information if relevant):**
 - OS: Mac Monterei M1 chip
 - Browser chrome 102

**Additional context**
Project seems awesome! I just need that delete button to work :)
Happy to submit a PR with some guidance, you guys ROCK 🚀

**Comment by dziraf** [comment]
@goldylucks I tried to reproduce your issue but couldn't.

Can you either:
a) create an example repository where your problem appears?
b) clone https://github.com/dziraf/repro-delete-adminjs and make changes necessary to reproduce this


https://user-images.githubusercontent.com/16668924/174783969-f3e88a24-0b47-4b3d-8ce8-1448d78fbbca.mov

**Comment by dziraf** [comment]
Closing because no response from original poster
