### ISSUE TITLE
Creating entity with column array of strings doesn't work

### ISSUE THREAD

**Issue by oleh-popovych** [SoftwareBrothers/adminjs#1156]
**Describe the bug**
When I'm trying to create entry with column "hardSkills" it creates an entry with a empty "hardSkills". But when I update this record  and set few elements to "columnA" adminjs saves it with all setted elements.

**Installed libraries and their versions**

* "@adminjs/express": "^4.1.3",
*  "@adminjs/nestjs": "^4.0.1",
*  "@adminjs/typeorm": "^3.0.0",
* "@nestjs/typeorm": "^8.1.4",
*  "adminjs": "^5.10.4",
*  "pg": "^8.7.3",
* "typeorm": "^0.3.6"
* postgres (PostgreSQL) 14.2

**To Reproduce**
1. Go to "Create new"
2. Fill all fields
3. Press "Save"
4. Find new entry
5. See that the required field is empty (create works bad)
6. Go to "Update"
7. Fill empty field
8. Press "Save"
9. See that update works good

**Expected behavior**
Create entity with column array of strings

**Screenshots**
![2022-06-21 о 20 59 26](https://user-images.githubusercontent.com/95422360/174867880-d295f0cf-5730-4b99-9616-50bcfa4c541c.gif)

**AdminJSOptions with schema**

```
@Entity()
export class Vacancy extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'varchar', array: true, default: [] })
  hardSkills: string[];

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
```
**AppModule:** 
```
  ....
  AdminModule.createAdmin({
      adminJsOptions: {
        rootPath: '/admin',
        resources: [{ resource: Vacancy }],
      },
    }),
  .....
```
**Desktop (please complete the following information if relevant):**
 - OS: MacOS Monterey (v12.3.1)
 - Browser Chrome (v102.0.5005.115)

**Comment by dziraf** [comment]
Can you check if
```
        resources: [{
          resource: Vacancy,
          options: {
            properties: {
              hardSkills: { isArray: true, type: 'string' }
            }
          }
        }],
```
makes a difference?

**Comment by oleh-popovych** [comment]
No, nothing has changed

**Comment by oleh-popovych** [comment]
> Can you check if
> 
> ```
>         resources: [{
>           resource: Vacancy,
>           options: {
>             properties: {
>               hardSkills: { isArray: true, type: 'string' }
>             }
>           }
>         }],
> ```
> 
> makes a difference?

No, nothing has changed

**Comment by oleh-popovych** [comment]
@dziraf 
Everything works, thank you!

**Comment by promentol** [comment]
I have same issue with prisma, can anybody help me?
