### ISSUE TITLE
get page : api client: pass  parameter 

### ISSUE THREAD

**Issue by faroukbouzouita** [SoftwareBrothers/adminjs#1161]
Hello ,
I need to pass a parameter from my custom page to the handle function using the apiclient class and the get page function
at the level of this function I cannot pass any parameter or query 
how can I get around this problem?

**Comment by dziraf** [comment]
You can use either `data` or `params`:
```
const api = new ApiClient()
api.getPage({
  pageName: 'xxx',
  data: { test: 123 }, // visible in request.payload in handler
})
