### ISSUE TITLE
Creating entity with column array of json doesn't work

### ISSUE THREAD

**Issue by oleh-popovych** [SoftwareBrothers/adminjs#1163]
**Describe the bug**
I have an error:
```There are validation errors - check them out below```
 when I'm trying to create entry with column "quotes" type which is json.

**Installed libraries and their versions**
* "@adminjs/express": "^4.1.3",
* "@adminjs/nestjs": "^4.0.1",
* "@adminjs/typeorm": "^3.0.2",
* "@nestjs/typeorm": "^8.1.4",
* "adminjs": "^5.10.4",
* "pg": "^8.7.3",
* "typeorm": "^0.3.6"
*  postgres (PostgreSQL) 14.2

**To Reproduce**
1. Go to "Create new"
2. Fill all fields
3. Press "Save"
4. Get an error "There are validation errors - check them out below"

**Expected behavior**
Create entity with column array of json

**Screenshots**
![screen](https://user-images.githubusercontent.com/95422360/176465321-137f060d-1c22-4dee-86ef-31bbf6423e6c.gif)

**AdminJSOptions with schema**

```
class Quote {
  authorName: string;
  text: string;
}

@Entity()
export class Project extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'json', array: true, default: [] })
  quotes: Quote[];

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}

```

**app.module.ts**

```
...
AdminModule.createAdmin({
      adminJsOptions: {
        rootPath: '/admin',
        resources: [
          {
            resource: Project,
            options: {
              properties: {
                quotes: {
                  type: 'mixed',
                  isArray: true,
                },
                'quotes.authorName': { type: 'string' },
                'quotes.text': { type: 'string' },
              },
            },
          },
        ],
      },
    }),
...
```

**Desktop (please complete the following information if relevant):**
 - OS: MacOS Monterey (v12.3.1)
 - Browser Chrome (v102.0.5005.115)

**Comment by dziraf** [comment]
Hmm this has worked before, could you try without `array: true,` in the decorator? I think it's normally used with simple array types, e. g. `text[]`, `int[]` and could be messing up metadata somehow. Can you also share what the validation error is? It should be present in the `Network` tab in your dev tools under server's response.

**Comment by oleh-popovych** [comment]
Thanks!
Without ```array: true``` in the decorator everything works fine!
There is screensot of ```Network``` with validation error.
![Знімок екрана 2022-07-01 о 15 43 36](https://user-images.githubusercontent.com/95422360/176896848-f342cfcf-8cf3-40dc-b29c-a0af59ba4dec.png)
