### ISSUE TITLE
Multi select dropdown for filters

### ISSUE THREAD

**Issue by tomtastico** [SoftwareBrothers/adminjs#1165]
**Describe the problem feature solves**
Right now you can only select a single value to filter for in dropdowns.

**Describe the solution you'd like**
It would be good to be able to select multiple values.

**Describe alternatives you've considered**
Might be a duplicate of #438 ... ? 

**Acceptance criteria**
Being able to select multiple values in filter dropdowns, and being able to filter by those.

Now:

![image](https://user-images.githubusercontent.com/690217/177057144-e0c58c0c-86ca-4a9e-aff6-4701e19a5b93.png)

Enhancement:

![image](https://user-images.githubusercontent.com/690217/177059305-f1eb0533-e868-4b0b-9f4d-5c31bea66722.png)

**Comment by Hat52** [comment]
I would like to work on this issue.

**Comment by Hat52** [comment]
@krzysztofstudniarek  Do i need to fork the dev repo?

**Comment by Hat52** [comment]
@krzysztofstudniarek why do I need to fork two repositories?

**Comment by dziraf** [comment]
@Hat52 @krzysztofstudniarek not sure if forking `adminjs-design-system` will be required as it's possible it's already got required UI components. You might have to fork adapter's repositories, e. g. `adminjs-typeorm` so that it supports array filters.

**Comment by Hat52** [comment]
@dziraf do I need to configure both repo on my local to achive the desired result.

**Comment by dziraf** [comment]
```
mkdir adminjs-development
cd adminjs-development
git clone git@github.com:SoftwareBrothers/adminjs.git
cd adminjs
yarn install
yarn link
yarn dev
yarn bundle:globals
cd ..
git clone git@github.com:SoftwareBrothers/adminjs-typeorm.git
cd adminjs-typeorm
yarn install
yarn link
yarn dev
cd ..
mkdir adminjs-test-app # or clone e. g. adminjs-example-app repository
cd adminjs-test-app
yarn init # setup test app project if you're going to work on your own test app
yarn link "adminjs"
yarn link "@adminjs/typeorm"
```
the steps above should make you see your local changes in your test app

**Comment by Hat52** [comment]
@dziraf thanks🙂

**Comment by Hat52** [comment]
@tomtastico can you share the step to reach to the filter that you mentioned?

**Comment by tomtastico** [comment]
@Hat52 thanks for looking into this!

You can get this kind of filter by having a resource using a mongoose schema that has a property of type enum, something like this:

```ts
@Prop({
  type: String,
  enum: StatusEnum,
})
status: StatusEnum;
```

With the enum being something like:

```ts
enum StatusEnum {
  VERIFIED = 'verified',
  VERIFYING = 'verifying',
  UNVERIFIED = 'unverified',
  BLOCKED = 'blocked',
}
```

**Comment by Hat52** [comment]
![image](https://user-images.githubusercontent.com/44437268/179842068-7918333a-6b8e-47ae-a47f-f2aa684b6091.png)
this is how my project structure look for now

**Comment by krzysztofstudniarek** [comment]
This issue is a part of https://github.com/SoftwareBrothers/adminjs/issues/251, hence I'm closing it and move conversation there.
