### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by vincentwinkel** [SoftwareBrothers/adminjs#1170]
**Describe the problem feature solves**
I spend hours and hours to try to make this tool work, vainly.
- how to override a simple form component ? (I would like to dynamically change the input type (text, number...) based on a record field) -> I found a lot of sources, nothing fits my need
- how to customise the query applying filters etc? Just a basic example, what about and / or conditions, ... ? -> no doc anywhere
- how to properly create a custom create/edit page? -> we need to merge some pieces of code from stackoverflow here and there and, of course, it doesn't work in the end
- and so on...

This tool is supposed to be fully customisable but we have absolutely no idea how to do it. The doc is just an auto-generated codebase reference with often no explanation nor example. A nice starting point, but giving no help to go deeper in the features.

It's so time consuming that I'm wondering if I wont be faster coding my own dashboard from scratch.
It's too bad, because this project looks really promising. My only concern is about its documentation.

**Describe the solution you'd like**
A better documentation.

**Comment by dziraf** [comment]
Current documentation is 99% automatically generated based on source code JSDoc comments, we will soon be rewriting it to be more tutorial-oriented.

As for your questions:
1. This is similar to: https://github.com/SoftwareBrothers/adminjs/issues/1087
2. The filters are passed via request query params, e. g. if you have a `name` field and set filter value to `Fred` it will send `filters.name=Fred` in the query.
You can also modify filters using a `before` hook, for example:
```
...,
actions: {
    list: {
        before: [(request) => {
            const { query = {} } = request;
            const newQuery = { ...query };
            newQuery['filters.name'] = 'Fred';
            
            request.query = newQuery;
            return request;
        }]
    }
}
```
Filters in `before` hook will apply to all calls of a given action. All filters are currently `OR` filters. We plan to improve the filters programmatic interface though.
3. By `Page` do you mean AdminJS Page (as in static pages in your sidebar which appear at the bottom) or `new`/`edit` forms?

**Comment by vincentwinkel** [comment]
Thank you for your fast reply!

1. I'm not sure it fixes my problem. I actually "just" need to override the `type` attribute of the input element (I tried to build my own component, lacking design, or even using this doc https://styled-components.com/docs/api). Out of this scope, an ideal solution could me something like that (I dont know if it's possible):
```js
properties: {
  myField: { type: record => record.params.otherField ? 'number' : 'text' },
}
```
because in my case for example, I may need to use a textarea instead of input making the React override a bit more difficult I guess

2. Once again you give a super basic example, what if I want to filter by "scope needs to be A or B"?
`'filters.scope': ['A', 'B']` -> doesn't work (error in mikro-orm, since I use the adapter adminjs/mikroorm)
`filters: scope: { $in ['A', 'B'] }` -> same error:
```
TypeError: Cannot read property 'type' of undefined
    at /node_modules/@adminjs/mikroorm/src/utils/convert-filter.ts:18:84
    at Array.reduce (<anonymous>)
    at convertFilter (/node_modules/@adminjs/mikroorm/src/utils/convert-filter.ts:17:34)
    at Resource.find (/node_modules/@adminjs/mikroorm/src/Resource.ts:89:22)
    at Object.handler (/node_modules/adminjs/lib/backend/actions/list/list-action.js:86:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
```
Etc, I tried many syntaxes vainly.
Also, what about sorting, which syntax to use..? In my opinion, it's not really clear.
I also inspected the example-app from adminjs/mikroorm, it also uses a simple filter "key-value" with no complex conditions.

3. I meant New/Edit forms. My colleague found a (complex imo) way to do a custom New page, displaying the form in 3 sections like we want, and when I use it as Edit page, error. Bu I'm convinced it's not the good way to do it anyway. We actually just want to redesign a bit the page, not to change the logic.

Also, the mapping between resources arent super clear, I guess I misunderstood something, but I need to declare all the resources in the `resources` options, put the one I dont want in the navigation "ignore" that I hide from the sidebar, and then the mapping (joins) works. But out of this scope.

Thank you anyway. I cant wait to see the doc updated, as I use AdminJs to quickly build an admin panel that I need to deploy asap.
Once again, super project, I'm only complaining about the doc.

**Comment by dziraf** [comment]
```
  myField: { type: record => record.params.otherField ? 'number' : 'text' },
```
This wouldn't work in the current implementation. Current UI is a single page React application and communicates with AdminJS backend using an auto-generated REST API. The configuration that you specify in `ResourceOptions` is handled by the backend and it isn't possible to include a function in server's response. Instead, the configuration is evaluated in the backend and converted to plain JSON objects (`ResourceDecorator#toJSON`, `PropertyDecorator#toJSON`, `ActionDecorator#toJSON`) which are sent to the frontend to render the UI.
One of the things we're working on currently is a complete backend<>frontend separation which could technically allow you to have a separate frontend configuration and full customize it but it will probably come after another several months.

A component like this should probably work for you:
```
import React from 'react';
import { BasePropertyComponent, EditPropertyProps } from 'adminjs';

const DynamicInputTypeField: React.FC<EditPropertyProps> = (props) => {
  const { property, record: initialRecord } = props;
  const cleanProperty = React.useMemo(() => ({ ...property, components: {} }), [
    property,
  ]);

  const BaseComponent = BasePropertyComponent as any;
  if (record.params.otherField) {
    cleanProperty.props = { type: 'number' };
    cleanProperty.type = 'number';
  } else {
    cleanProperty.props = { type: 'text' };
    cleanProperty.type = 'string';
  }

  return <BaseComponent {...props} property={cleanProperty} />;
};

export default DynamicInputTypeField;
```

```
properties: {
  myField: {
      components: { edit: AdminJS.bundle(<path to component>) },
  },
}
```

> what if I want to filter by "scope needs to be A or B"?
Array filters are currently not supported either, we simply have no UI to handle this yet so it wasn't added.

> I meant New/Edit forms. My colleague found a (complex imo) way to do a custom New page, displaying the form in 3 sections like we want, and when I use it as Edit page, error. But I'm convinced it's not the good way to do it anyway. We actually just want to redesign a bit the page, not to change the logic.

You would have to show me the component to know more. All action components should use `ActionProps`: https://github.com/SoftwareBrothers/adminjs/blob/master/src/frontend/components/actions/action.props.ts
Example is the default edit action: https://github.com/SoftwareBrothers/adminjs/blob/master/src/frontend/components/actions/edit.tsx

In order to simply group your fields, you can just use `layout` configuration: https://docs.adminjs.co/Action.html#layout

**Comment by vincentwinkel** [comment]
About the input solution, it works like a charm, thank you. (in a perfect world, I would be able to integrate a custom component to manage JSON objects, but lets see later I guess)

About list filters, any workaround, like overriding the controller? Worst case, I can try to merge 2 requests.

About the layout, I forgot we have 3 resources joined, thats why we did something custom. But I'm refactoring the code, and get this:
<img width="247" alt="Screenshot 2022-07-15 at 10 17 05" src="https://user-images.githubusercontent.com/1402505/179184166-26bf7ed9-3009-4139-87c7-224004ddb7fa.png">

Now I'm trying to play with a custom layout, but I dont find a doc about the syntax I dont get the logics.
If I literally try (after removing the extra `]` from the doc):
```js
layout: [
  { width: 1 / 2 },
  [['@H3', { children: 'Organisation' }], 'name', 'description'],
  [
    ['@H3', { children: 'Company' }],
    [
      { flexDirection: 'row', flex: true },
      [
        ['company_name', { pr: 'default', flexGrow: 1 }],
        ['company_description', { flexGrow: 1 }],
      ],
    ],
  ],
  [
    ['@H3', { children: 'Admin' }],
    [
      { flexDirection: 'row', flex: true },
      [
        ['admin_id', { pr: 'default', flexGrow: 1 }],
        ['admin_email', { flexGrow: 1 }],
        ['admin_firstname', { flexGrow: 1 }],
        ['admin_lastname', { flexGrow: 1 }],
      ],
    ],
  ],
],
```
I get this, the `Organisation` section is not shown (I tried 10 different ways to write it).
<img width="1332" alt="Screenshot 2022-07-15 at 10 19 21" src="https://user-images.githubusercontent.com/1402505/179184533-ea27be7e-bbd5-4883-8545-e8d082e4e62c.png">

**Comment by nick-brady** [comment]
Just piping in to mention I've spent hours trying to find essentially this. The tool seems great, but I've asked myself the exact same question about just creating my own dashboard. Thank you for replying with the custom component (what I was trying to do, but for FileUpload type thing).

**Comment by krzysztofstudniarek** [comment]
I believe the documentation is much better right now. Please take a look at docs.adminjs.co ;)

**Comment by vincentwinkel** [comment]
I'm sorry but it's much worse.
For example, please tell me where we can find the list of available property types (text, number...).
https://docs.adminjs.co/basics/property this page gives absoutely no info, neither when I use the searchbar.
I randomly discovered we could pass the prop "rows" to a textarea thanks to your random example. Where we can see the list of props we can use per type?

Another example, I pass a reference to my resource, which displays a dropdown on the edit page. Great. But this dropdown is built after a query to get all the rows in my table. How can I filter it? I tried to directly filter the resource used as reference, nothing. Nothing again in the doc. I had to replace the refereence with a custom list + `availableValues`.

Because nothing is clear, we cannot automatize anything, and I have to manually build all my resource dependencies, and override all the create/updatee routes to correctly save in db all the joins, which takes more time than if I have built a handmade admin section.

Thanks for rebuilding a super fancy doc in night mode but it absolutely doesnt fix the problem which is a lack of access to informations. At least your previous doc gave access to some class references.
