### ISSUE TITLE
Please add a plugin for AdonisJS

### ISSUE THREAD

**Issue by MichaelNZ85** [SoftwareBrothers/adminjs#1171]
**Describe the problem feature solves**
lt would be great to see a plugin to use AdminJS on [AdonisJS](https://adonisjs.com/).

**Describe the solution you'd like**
A plugin for AdonisJS that allows you to easily add AdminJS to an AdonisJS app the way you can for Express or Fastify.

**Describe alternatives you've considered**
The only other alternative seems to be this package: [Adonisjs Crud Generator](https://github.com/Shagital/adonisjs-crud-generator)

**Acceptance criteria**
Able to be used with AdonisJS like with Express/Fastify/Hapi/NestJS

**Comment by dziraf** [comment]
There's an unofficial plugin for AdonisJS: https://github.com/chirgjin/adminjs-adonis

We do not plan to write an official plugin for now.
