### ISSUE TITLE
Better error handling in custom actions

### ISSUE THREAD

**Issue by AshotN** [SoftwareBrothers/adminjs#1172]
**Describe the problem feature solves**
Custom actions can only return errors related to property fields

**Describe the solution you'd like**
Allow for a error message to be shown to the user in a box

**Acceptance criteria**
[ ] - Allow passing custom error messages to the user without an associated field

For some context, the action I have is a button that make an API request and sometimes updates the record. It works fine, but I have no decent way to alert the user if the API call failed

**Comment by dziraf** [comment]
@edwardstumpf has recently done some improvements to error handling (v5.11.0 or higher), could you try to throw an `Error` that has `baseMessage` field in it's object and see if it shows that message?

https://github.com/SoftwareBrothers/adminjs/blob/bf2078fbdfdb7b5627858d3660a2e7e341afa278/src/backend/services/action-error-handler/action-error-handler.ts#L26

**Comment by AshotN** [comment]
Throwing a regular Error won't work, because `baseMessage` is not a property in a normal `Error` object

AdminJS has `ForbiddenError` that has a `baseMessage` property. It works if I throw that, but the semantics are not ideal. Throwing a `ForbiddenError` gives the impression this is an auth error or some other form of mistake. 

This is a good stop-gap, but I would like to see AdminJS default to a normal type error instead.

Thanks

**Comment by krzysztofstudniarek** [comment]
We won't allow normal `Error` object to be displayed, cause this will lead to showing all server error messages to the end users.

**Comment by AshotN** [comment]
Can we compromise with a new error type that isn't `ForbiddenError` just for semantics

**Comment by dziraf** [comment]
@AshotN 
I added a new error type: `AppError`
https://github.com/SoftwareBrothers/adminjs/pull/1232

Let me know if this is enough

**Comment by AshotN** [comment]
This looks great, thank you. Only ask I have is to make the second parameter optional. But it's not a big deal, thanks!
