### ISSUE TITLE
I have a dashboard question.

### ISSUE THREAD

**Issue by wngus606** [SoftwareBrothers/adminjs#1174]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/7146593/179404990-0392502f-1d9e-4d83-a63c-1b8796da7f09.png">
I want to change the dashboard like this, what should I do?
And I think the slack link is wrong.

**Comment by 1ay1** [comment]
You need to override the default Dashboard component, please refer to the docs.

**Comment by BarejaPawel** [comment]
You can hide the footnote in branding property:
`` 
...
 branding: {
    softwareBrothers: false,
  }
  ...
  ``

**Comment by Kitsutsuki-98** [comment]
> In AdminJS v6 and above `softwareBrothers` config option has been changed to `madeWithLove`

![image](https://user-images.githubusercontent.com/13228858/180480291-337f8794-a76e-46eb-a0d8-f42e22aecc4b.png)

this is not working for me,

**Comment by Kitsutsuki-98** [comment]
> In AdminJS v6 and above `softwareBrothers` config option has been changed to `madeWithLove`

It's actually withMadeWithLove

> @Kitsutsuki-98
> 
> did you find a way to remove this?
> 
> <img alt="image" width="203" src="https://user-images.githubusercontent.com/29349609/179547012-18836124-6ca9-4bc8-9f2e-cc4c7550cd5b.png">

![image](https://user-images.githubusercontent.com/13228858/180587819-de6c19cc-123a-44da-8792-84166288a202.png)

**Comment by krzysztofstudniarek** [comment]
AdminJS UI will be gradually improved to match the expectations. I see that the issue with `withMadeWithLove ` property was solved, so I'm closing this issue.
