### ISSUE TITLE
Wrapping around React App component 

### ISSUE THREAD

**Issue by omerabbas01** [SoftwareBrothers/adminjs#1175]
Hello,

Can we customise main App component or wrap it with some custom components? I am trying to integrate Web3 connectivity libraries and not sure where to start with. React libraries similar to [usedapp](https://usedapp.io/) ask you to wrap react App component with their provided component for library to work, Please help

**Comment by krzysztofstudniarek** [comment]
Hey, 

Here is the tutorial on how to write your own components: https://docs.adminjs.co/tutorial-writing-react-components.html

Is this something you were looking for?

**Comment by dziraf** [comment]
@omerabbas01 We've never had to do it, you could try to create your own function imitating:
https://github.com/SoftwareBrothers/adminjs/blob/master/src/frontend/layout-template.tsx
and serve it manually, although it's just a guess. AdminJS v7 should allow you to customize your frontend however you like but it will most likely take another several months of work before it's ready.

**Comment by dziraf** [comment]
Closing because no response from original poster
