### ISSUE TITLE
Show action handler

### ISSUE THREAD

**Issue by olegorelwork** [SoftwareBrothers/adminjs#1176]
Hey guys, there is a problem to handle big data on show action in my case.

The main problem in show action that data already comes in params, that mean that data not coming from show action handler but coming before handler I mean in show handler params like (request, response, data) instead of (request, response, context), i can't redefine data loading in handler, because data already loaded.

**Comment by krzysztofstudniarek** [comment]
Hey @olegorelwork, can you elaborate a bit and show examples?

**Comment by dziraf** [comment]
Closing because no response from original poster
