### ISSUE TITLE
Every time I open the admin or log in, 45MB worth of JS are loaded and it takes ages

### ISSUE THREAD

**Issue by CherryDT** [SoftwareBrothers/adminjs#1187]
**Describe the bug**
Every time I open the admin or log in, I sit for a minute on a white screen while my mobile data is getting wasted as 45 MB worth of JavaScript is getting downloaded (without gzip no less!).

**Installed libraries and their versions**

* adminjs@6.0.1
* @adminjs/koa@3.0.0
* @adminjs/mongoose@3.0.0
* koa@2.13.4

**Expected behavior**
I expect...

* ...the JS bundle size to be smaller (minified, tree-shaken, etc.)
* ...the files to be loaded with transfer compression (e.g. gzip)
* ...the files to be cached and loaded only once
* ...some loader to be visible instead of having an empty page for a minute (which causes users to hit reload, which just makes it worse)

Don't get me wrong, AdminJS is awesome otherwise, but this is a bit of a problem, I am somewhere with slower Internet right now and it's very hard to use the admin then.

**Screenshots**

![image](https://user-images.githubusercontent.com/6010463/180605250-651a45ea-52f8-4be5-b081-1f3d5fa67c78.png)

**AdminJSOptions with schema**

This is how I load AdminJS:

```javascript
import AdminJS from 'adminjs'
import { buildAuthenticatedRouter } from '@adminjs/koa'
import Router from '@koa/router'
import AdminJSMongoose from '@adminjs/mongoose'
import { app } from '../lib/server'
import config from 'config'
import mongoose from 'mongoose'

AdminJS.registerAdapter(AdminJSMongoose)

const adminConfig = config.get('admin')

export function createAdminRouter () {
  const adminJs = new AdminJS({
    databases: [mongoose],
    rootPath: '/admin',
    branding: {
      logo: '/images/logo.svg',
      companyName: 'Admin',
      softwareBrothers: false,
      favicon: '/images/favicon.png'
    },
    locale: {
      translations: {
        labels: {
          loginWelcome: ''
        },
        messages: {
          loginWelcome: ''
        }
      }
    },
    dashboard: {
      component: AdminJS.bundle('../../adminCustom/dashboard.jsx')
    },
    version: false
  })

  return buildAuthenticatedRouter(adminJs, app, {
    authenticate: async (email, password) => {
      if (email === adminConfig.auth.email && password === adminConfig.auth.password) {
        return {
          id: 'admin',
          email,
          title: 'The Boss'
        }
      } else {
        return null
      }
    }
  }, new Router({ prefix: '/admin' }))
}
```

Note: `dashboard.jsx` just has a box with links.

**Comment by ddresch** [comment]
<img width="896" alt="Design System Bundle" src="https://user-images.githubusercontent.com/986306/180665891-bea747d2-28bc-45ba-8310-c5a097088674.png">

The design system bundle is throwing this amount of weight on the scale.

**Comment by CherryDT** [comment]
Wait but then why do _you_ get a 304 and _I_ get it loaded every time? The files are served by your adapter, right? So how can I manage cache settings for it?

**Comment by ddresch** [comment]
No idea on my side it's just working but you are right - how to handle this properly?

**Comment by ddresch** [comment]
Okay just stumbled across [this](https://github.com/SoftwareBrothers/adminjs/issues/924#issuecomment-938023826) didn't test yet but looks promising

**Comment by CherryDT** [comment]
Ah, perhaps NODE_ENV is not production on the server for whatever reason... Will check, thanks

**Comment by dziraf** [comment]
Yes, the way AdminJS works by default is that it serves javascript bundles in runtime when your server starts:
```
app.bundle.js
global.bundle.js
components.bundle.js # your custom components
design-system.bundle.js
```
If your `NODE_ENV` is `production` it serves minified bundles, otherwise they're not minified. The size mostly comes from the design system.

To optimise this, you can prebundle AdminJS assets and disable runtime bundling (via env `ADMIN_JS_SKIP_BUNDLE=true`). You can have a look at `@adminjs/bundler` which is a tool which can help you do that. It's code-based, not CLI:
https://docs.adminjs.co/module-@adminjs_bundler.html

Here's a full example where I use it in one of our projects to pre-bundle assets and deploy them to S3 in release phase of our CI:

```
/* eslint-disable import/first */
// eslint-disable-next-line @typescript-eslint/no-var-requires
require('dotenv').config({ path: `${__dirname}/../../.env` });

import 'reflect-metadata';
import { promises as fs } from 'fs';
import { join, parse } from 'path';
import { bundle } from '@adminjs/bundler';
import AWS from 'aws-sdk';

import config from '../config';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as components from '../admin/components.bundler';
import getAdminOptions from '../admin/admin.options';

type UploadOptions = {
  keyPrefix: string;
  bucket: string;
  cacheControl?: string;
};

const aws = new AWS.S3({
  region: config.aws.region,
  accessKeyId: config.aws.s3accessKeyId,
  secretAccessKey: config.aws.s3secretAccessKey,
  signatureVersion: 'v4',
});

const uploadFile = async (
  { destinationPath: filePath }: { destinationPath: string },
  { keyPrefix, bucket, cacheControl }: UploadOptions,
): Promise<void> => {
  const file = await fs.readFile(filePath);
  const destinationName = parse(filePath).base;
  const s3Path = join(keyPrefix, destinationName);

  // eslint-disable-next-line no-console
  console.log(`Uploading ${filePath} to ${s3Path}`);

  return new Promise((resolve, reject) => {
    aws.upload(
      {
        Bucket: bucket,
        Key: s3Path,
        Body: file,
        CacheControl: cacheControl,
      },
      (err) => {
        if (err) reject(err);
        // eslint-disable-next-line no-console
        console.log(`Succesfully uploaded ${filePath} to ${config.app.assetsUrl}${destinationName}`);
        resolve();
      },
    );
  });
};

(async () => {
  // eslint-disable-next-line global-require
  require('@adminjs/passwords');
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { resources: _resources, databases: _databases, ...otherOptions } = getAdminOptions();
  const manifestPath = 'src/admin/assets-manifest.json';
  const files = await bundle({
    customComponentsInitializationFilePath: 'src/admin/components.bundler.ts',
    destinationDir: 'public',
    adminJsOptions: otherOptions,
    versioning: {
      manifestPath,
    },
  });

  // eslint-disable-next-line no-console
  console.log(files);

  const keyPrefix = `admin-${config.app.environment}`;
  await Promise.all(files.map((file) => uploadFile(
    file,
    { keyPrefix, bucket: config.aws.s3bucket },
  )));

  await uploadFile(
    { destinationPath: join(process.cwd(), manifestPath) },
    { keyPrefix, bucket: config.aws.s3bucket, cacheControl: 'no-store, no-cache' },
  );

  await Promise.all(files.map((file) => fs.unlink(file.destinationPath)));
})();
```
Afterwards I set `assetsCDN` in `AdminJSOptions` to the s3 bucket:
```
  assetsCDN: isProduction ? config.app.assetsUrl : undefined,
```
I also set `assets.coreScripts` to the versioning mapping generated by `@adminjs/bundler`:
```
  assets: {
    styles: ['/overrides.css'],
    coreScripts: isProduction && assetsManifest ? assetsManifest : undefined,
  },
```
https://github.com/SoftwareBrothers/adminjs/blob/master/src/core-scripts.interface.ts
