### ISSUE TITLE
Fix documentation of RBAC tutorial

### ISSUE THREAD

**Issue by ddresch** [SoftwareBrothers/adminjs#1189]
**Describe the bug**
In the complete code block of the tutorial app you define the actions of the user ressource with two `new` blocks. Like that the second overwrites the first definition.

<img width="629" alt="Code" src="https://user-images.githubusercontent.com/986306/180667259-e80ac93e-ca7e-497a-b779-970add72a58a.png">

With this setup you end up with a validation error: `There are validation errors - check them out below`.

Please remove this little piece :) Thx!

**Comment by krzysztofstudniarek** [comment]
We're currently working on new documentation where RBAC will be described with the corresponding examples. Closing the issue for now.
