### ISSUE TITLE
Action not related to Resource

### ISSUE THREAD

**Issue by wirekang** [SoftwareBrothers/adminjs#1205]
**Describe the problem feature solves**

Some logics are not related to certain Resource. 

**Describe the solution you'd like**

Add `actions` or something in `adminJsOptions`.

**Describe alternatives you've considered**
I defined actions in `resources` with unrelated resource.

**Acceptance criteria**

**Comment by dziraf** [comment]
Please give an example.

**Comment by krzysztofstudniarek** [comment]
Closing the issue due to lack of response. If it's still the problem please reopen it.
