### ISSUE TITLE
Upload feature not working

### ISSUE THREAD

**Issue by robikovacs** [SoftwareBrothers/adminjs#1208]
**Describe the bug**
Upload feature doesn't seem to load properly on the new/edit page.

**Installed libraries and their versions**

* "@adminjs/express": "^5.0.0"
* "@adminjs/prisma": "^3.0.1"
* "@adminjs/upload": "^3.0.0"

**To Reproduce**
1. Go to the admin dashboard
2. Click on create
3. Scroll down to imageUrl field.
4. Cannot see any upload component.

**Expected behavior**
An upload component or input should be rendered.

**Screenshots**
![Screenshot 2022-08-05 at 11 12 58](https://user-images.githubusercontent.com/5718030/183033297-839ce0f0-2a2b-4259-bf6d-ad4ea6ef7aa6.png)

**AdminJSOptions with schema**

```js
export const app = express()
const prisma = new PrismaClient()

const dmmf = (prisma as any)._baseDmmf

const admin = new AdminJS({
  resources: [
    {
      resource: { model: dmmf.modelMap.Address, client: prisma },
      options: {},
    },
    {
      resource: { model: dmmf.modelMap.Amenity, client: prisma },
      options: {},
    },
    {
      resource: { model: dmmf.modelMap.Office, client: prisma },
      options: {
        listProperties: ['name', 'kind', 'imageUrl', 'latitude', 'longitude'],
        features: [uploadFeature.default({
          provider: { gcp: { bucket: GCLOUD_BUCKET_NAME } },
          properties: {
            key: 'imageUrl',
            mimeType: 'imageMimeType'
          },
          validation: {
            mimeTypes: ['image/jpeg', 'image/png']
          }
        })]
      }
    },
    {
      resource: { model: dmmf.modelMap.Unit, client: prisma },
      options: {},
    },
    {
      resource: { model: dmmf.modelMap.Review, client: prisma },
      options: {},
    },
  ],
})

const router = AdminJSExpress.buildRouter(admin)
```

**Comment by dziraf** [comment]
`features` doesn't go inside of `options`, it should be on the same level as `resource` and `options`
