### ISSUE TITLE
Custom Component is not working (includes github repo)

### ISSUE THREAD

**Issue by dmastag** [SoftwareBrothers/adminjs#1214]
**Describe the bug**
I have tried to create a Custom Dashboard as per Documentation on
https://docs.adminjs.co/tutorial-writing-react-components.html

But I am getting an error Message 

```
Javascript Error
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `Dashboard`.
See development console for more details...
```

Repo is here
https://github.com/dmastag/adminjs-bug-custom-component

**Installed libraries and their versions**

* adminjs@^6.0.6
* @adminjs/express@^5.0.0
* express@^4.18.1
* express-formidable@^1.2.0"

**To Reproduce**
1. clone Repo
2. run `npx nodemon .`
3. open http://localhost:8080/admin in a Browser

**Expected behavior**
Dashboard gets replaced

**Screenshots**
![image](https://user-images.githubusercontent.com/5745805/184523451-fe88b8c6-b980-4c70-9535-7254f938bd0c.png)

**AdminJSOptions with schema**
```
const adminJs = new AdminJS({
  databases: [],
  rootPath: '/admin',
  dashboard: {
    component: AdminJS.bundle('./my-dashboard-component')
  },
})
```

**Desktop (please complete the following information if relevant):**
 - OS: Windows 10 and MaxOS 12
 - Browser Chrome

**Comment by dziraf** [comment]
The documentation (docs.adminjs.co) tutorials are outdated. I'm currently rewriting the documentation to be more tutorial-based but as of now there's only installation section.

Your problem can be solved by importing `Box` from `@adminjs/design-system` instead of `adminjs`.

**Comment by dmastag** [comment]
Thanks
That make it work
