### ISSUE TITLE
Can't install adminjs and adapters

### ISSUE THREAD

**Issue by VasilNikolov** [SoftwareBrothers/adminjs#1218]
**Describe the bug**
I assume that after a new version of adminjs was released the install broke on all local computers and two servers. We are using node 18 and adminjs 6.0.6 which produced some warnings but ultimately installed.
When trying to install one by one they also fail. Something to do with node-gyp?
After every install i npm clean cache, node_moduels and package-lock if any.

**Installed libraries and their versions**

* adminjs@6.0.6 and 6.1.2
* @adminjs/express@5.0.0
* @adminjs/mongoose@3.0.0

**To Reproduce**

**Expected behavior**
The install to complete

**Screenshots**
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\vasil\AppData\Roaming\nvm\v18.7.0\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\vasil\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm ERR! npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm ERR! npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm ERR! npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated core-js-pure@3.16.2: core-js-pure@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js-pure.
npm ERR! npm WARN deprecated core-js@3.16.2: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\vasil\AppData\Local\npm-cache\_cacache\tmp\git-clone1rR4ry\node_modules\lmdb-store
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\vasil\AppData\Local\Temp\install-0c39a6bc.cmd
npm ERR! npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
npm ERR! npm ERR!   midl.c
npm ERR! npm ERR!   chacha8.c
npm ERR! npm ERR!   lz4.c
npm ERR! npm ERR!   node-lmdb.cpp
npm ERR! npm ERR! c:\users\vasil\appdata\local\npm-cache\_cacache\tmp\git-clone1rr4ry\node_modules\nan\nan.h(2544): warning C4996: 'v8::ObjectTemplate::SetAccessor': Do signature check in accessor [C:\Users\vasil\AppData\Local\npm-cache\_cacache\tmp\git-clone1rR4ry\node_modules\lmdb-store\build\lmdb-store.vcxproj]
npm ERR! npm ERR!   c:\users\vasil\appdata\local\node-gyp\cache\18.7.0\include\node\v8-template.h(838): note: see declaration of 'v8::ObjectTemplate::SetAccessor'
npm ERR! npm ERR!   env.cpp
npm ERR! npm ERR! c:\users\vasil\appdata\local\npm-cache\_cacache\tmp\git-clone1rr4ry\node_modules\nan\nan.h(2544): warning C4996: 'v8::ObjectTemplate::SetAccessor': Do signature check in accessor [C:\Users\vasil\AppData\Local\npm-cache\_cacache\tmp\git-clone1rR4ry\node_modules\lmdb-store\build\lmdb-store.vcxproj]
npm ERR! npm ERR!   c:\users\vasil\appdata\local\node-gyp\cache\18.7.0\include\node\v8-template.h(838): note: see declaration of 'v8::ObjectTemplate::SetAccessor'
npm ERR! npm ERR!   compression.cpp
npm ERR! npm ERR! c:\users\vasil\appdata\local\npm-cache\_cacache\tmp\git-clone1rr4ry\node_modules\nan\nan.h(2544): warning C4996: 'v8::ObjectTemplate::SetAccessor': Do signature check in accessor [C:\Users\vasil\AppData\Local\npm-cache\_cacache\tmp\git-clone1rR4ry\node_modules\lmdb-store\build\lmdb-store.vcxproj]
npm ERR! npm ERR!   c:\users\vasil\appdata\local\node-gyp\cache\18.7.0\include\node\v8-template.h(838): note: see declaration of 'v8::ObjectTemplate::SetAccessor'
npm ERR! npm ERR!   ordered-binary.cpp
npm ERR! npm ERR! c:\users\vasil\appdata\local\npm-cache\_cacache\tmp\git-clone1rr4ry\node_modules\nan\nan.h(2544): warning C4996: 'v8::ObjectTemplate::SetAccessor': Do signature check in accessor [C:\Users\vasil\AppData\Local\npm-cache\_cacache\tmp\git-clone1rR4ry\node_modules\lmdb-store\build\lmdb-store.vcxproj]
npm ERR! npm ERR!   c:\users\vasil\appdata\local\node-gyp\cache\18.7.0\include\node\v8-template.h(838): note: see declaration of 'v8::ObjectTemplate::SetAccessor'
npm ERR! npm ERR! c:\users\vasil\appdata\local\npm-cache\_cacache\tmp\git-clone1rr4ry\node_modules\lmdb-store\src\ordered-binary.cpp(138): error C2660: 'v8::Symbol::Description': function does not take 0 arguments [C:\Users\vasil\AppData\Local\npm-cache\_cacache\tmp\git-clone1rR4ry\node_modules\lmdb-store\build\lmdb-store.vcxproj]
npm ERR! npm ERR!   c:\users\vasil\appdata\local\node-gyp\cache\18.7.0\include\node\v8-primitive.h(588): note: see declaration of 'v8::Symbol::Description'
npm ERR! npm ERR! c:\users\vasil\appdata\local\npm-cache\_cacache\tmp\git-clone1rr4ry\node_modules\lmdb-store\src\ordered-binary.cpp(138): error C2672: 'v8::Local<v8::String>::Cast': no matching overloaded function found [C:\Users\vasil\AppData\Local\npm-cache\_cacache\tmp\git-clone1rR4ry\node_modules\lmdb-store\build\lmdb-store.vcxproj]
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@9.0.0
npm ERR! npm ERR! gyp info using node@18.7.0 | win32 | x64
npm ERR! npm ERR! gyp info find Python using Python version 3.10.4 found at "C:\Users\vasil\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! npm ERR! gyp info find VS using VS2017 (15.9.28307.1974) found at:
npm ERR! npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
npm ERR! npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! npm ERR! gyp info spawn C:\Users\vasil\AppData\Local\Programs\Python\Python310\python.exe
npm ERR! npm ERR! gyp info spawn args [
npm ERR! npm ERR! gyp info spawn args   'C:\\Users\\vasil\\AppData\\Roaming\\nvm\\v18.7.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! npm ERR! gyp info spawn args   '-f',
npm ERR! npm ERR! gyp info spawn args   'msvs',
npm ERR! npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! npm ERR! gyp info spawn args   '/nologo',
npm ERR! npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! npm ERR! gyp info spawn args ]
npm ERR! npm ERR! gyp ERR! build error
npm ERR! npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\vasil\AppData\Roaming\nvm\v18.7.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vasil\\AppData\\Roaming\\nvm\\v18.7.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! npm ERR! gyp ERR! cwd C:\Users\vasil\AppData\Local\npm-cache\_cacache\tmp\git-clone1rR4ry\node_modules\lmdb-store
npm ERR! npm ERR! gyp ERR! node -v v18.7.0
npm ERR! npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! npm ERR! gyp ERR! not ok
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\vasil\AppData\Local\npm-cache\_logs\2022-08-21T10_12_26_791Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vasil\AppData\Local\npm-cache\_logs\2022-08-21T10_11_55_382Z-debug-0.log

**AdminJSOptions with schema**
Paste your AdminJS config with database schema if it could be related to the issue

**Desktop (please complete the following information if relevant):**
 - OS: Windows 10, Windows 11, Buster 10

**Additional context**

**Comment by dziraf** [comment]
I advise against using Node.js 18 until it's LTS release. We build AdminJS packages with Node 16.

If there have been engine updates in Node 18, it can fail building some low-level packages until they're updated.

**Comment by petrakoww** [comment]
I downloaded your repo from here https://github.com/SoftwareBrothers/adminjs.git in search for the problem

The install was unsuccessful, but found that the dependency which was causing the problem was:  
"@adminjs/design-system": "3.0.1", i changed the version to 3.0.0 and managed to install it successfully.

Going back to my project which uses:
"@adminjs/express": "5.0.0",
"@adminjs/mongoose": "3.0.0",
"adminjs": "6.0.6",

I added "@adminjs/design-system": "3.0.0" but got the same error.

So I think there is a problem with the version of @adminjs/design-system which adminJS depends on.

**Comment by dziraf** [comment]
Hmm, 3.0.1 uses one repository I forked: https://github.com/dziraf/react-currency-input-field as a direct github link. I'm not sure what could be the issue here but I can release it as a npm package tomorrow.

**Comment by dziraf** [comment]
@VasilNikolov You should be able to create a PR but you have to fork the repository first

**Comment by VasilNikolov** [comment]
> @VasilNikolov You should be able to create a PR but you have to fork the repository first

Hey, can you review it? I thinks its a solid fix.

**Comment by dziraf** [comment]
I merged your PR @VasilNikolov
