### ISSUE TITLE
Unable to pass data with ApiClient to handler

### ISSUE THREAD

**Issue by AshotN** [SoftwareBrothers/adminjs#1225]
**Describe the bug**
Data passed through the ApiClient getPage() method does not make it to the handler

**Installed libraries and their versions**

* adminjs@5.11.0
* @adminjs/express@4.1.3"
* body-parser: "^1.19.1"
*  express: "^4.17.2"

**To Reproduce**
A custom page like so

```
  pages: {
      Management: {
        handler: async (request: Request, response, context) => {
          console.log("TEST", request.method, request.query, request.body)
          return {
            text: "I am fetched from the backend",
          }
        },
        component: AdminJS.bundle("./components/Management"),
      },
    },
```
and in the page
```
 const api = new ApiClient()

  const res = await api.getPage({
    pageName: "Management",
    data: { asdf: "FDSA" },
    params: { test: "fdas" }
  })
```

The `request.body` property is an empty object. `request.query` does receive the params correctly. 

Setting the method to `POST` in the getPage() function causes the server not to receive the request at all

I have body-parser enabled with

```

// parse application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: false }))

// parse application/json
app.use(bodyParser.json())
```

**Comment by dziraf** [comment]
@AshotN can you check `request.payload`? This is what's used in other AdminJS requests and actions. Let me know if this helps.

Bodyparser should only be used *after* setting up AdminJS router. AdminJS uses `express-formidable` which conflicts with bodyparser.

**Comment by AshotN** [comment]
`request.payload` is empty

If I setup bodyparser after AdminJS router, `request.body` is `undefined`

**Comment by AshotN** [comment]
I just realized, `GET` requests can't have a body. The issue is I can't get the `POST` request to make it to the server.

**Comment by dziraf** [comment]
You should be able to add `method: "post"` here:
```
  const res = await api.getPage({
    pageName: "Management",
    data: { asdf: "FDSA" },
    params: { test: "fdas" },
    method: "post"
  })
```

**Comment by AshotN** [comment]
That's what I tried, the handler doesn't trigger if you supply and `data`

```
api.getPage({
    pageName: "Management",
    data: { asdf: "FDSA" },
    method: "post",
  })
```
Doesn't trigger handler

```
api.getPage({
    pageName: "Management",
    method: "post",
  })
```

Does

**Comment by dziraf** [comment]
I'll try to take a look at this tomorrow

**Comment by AshotN** [comment]
@dziraf any luck with this?

**Comment by dziraf** [comment]
Sorry, I forgot about this.

I've just tested in our example app (https://github.com/SoftwareBrothers/adminjs-example-app/blob/master/src/admin/index.ts#L109) locally and this look to be working for me:

```
  useEffect(() => {
    api.getPage({ pageName: 'Custom Page', method: 'post', data: { test: '123abc' } }).then((res) => {
      setText(res.data.text);
    });
  });
```

```
    'Custom Page': {
      component: SOME_STATS,
      icon: 'Purchase',
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      handler: async (request, response, context) => {
        console.log(request.payload);
        return {
          text: 'I am fetched from the backend',
        };
      },
    },
```

**Comment by AshotN** [comment]
I messed around with it further, `body-parser` is definitely the cause of my issues. With `body-parser` enabled, if I `console.log` out `req.body` from my auth middleware, I can see the data. But in the handler it's missing. 

If I remove `body-parser`, `req.payload` works the same as your example. But I lose the ability to see the data in my Express middleware.

Any suggestions on how to get `body-parser` to play nice with AdminJS?

**Comment by dziraf** [comment]
The recommended solution is to `app.use(admin.options.rootPath, adminRouter)` before you `app.use(bodyParser.json())`
