### ISSUE TITLE
Can't Install adminJS

### ISSUE THREAD

**Issue by ReisoAphi** [SoftwareBrothers/adminjs#1230]
**Describe the bug**
I'm getting issues when installing adminjs.

**Installed libraries and their versions**

**To Reproduce**
1. Try to install adminjs the normal way "npm install adminjs @adminjs/express"

**Expected behavior**

Terminal is giving,

npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-text-mask@5.4.3
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0" from use-memo-one@1.1.2
npm WARN   node_modules/@react-forked/dnd/node_modules/use-memo-one
npm WARN     use-memo-one@"^1.1.2" from @react-forked/dnd@15.0.0
npm WARN     node_modules/@react-forked/dnd
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-text-mask@5.4.3
npm WARN node_modules/react-text-mask
npm WARN   react-text-mask@"^5.4.3" from @adminjs/design-system@3.0.1
npm WARN   node_modules/@adminjs/design-system
npm WARN
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-text-mask@5.4.3
npm WARN   node_modules/react-text-mask
npm WARN     react-text-mask@"^5.4.3" from @adminjs/design-system@3.0.1
npm WARN     node_modules/@adminjs/design-system
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Desktop (please complete the following information if relevant):**
 - OS: Windows
 - Browser: chrome
 - Version 10

**Comment by dziraf** [comment]
Have you tried `npm install --force` or just `yarn install`?

**Comment by dziraf** [comment]
Closing because no response from OP
