### ISSUE TITLE
Retrieve request IP in authenticate method

### ISSUE THREAD

**Issue by itamar-owlytics** [SoftwareBrothers/adminjs#1233]
I want to retrieve the request IP in the `authenticate: async (email, password) => {` method
There is an option to do it?

**Comment by dziraf** [comment]
Not really, the `authenticate` method only has `email` and `password` as arguments. We plan to improve authentication in the future but if you want to customize it your best option is to use non-authenticated admin router and create custom endpoints for auth.

**Comment by itamar-owlytics** [comment]
I created this PR:
https://github.com/SoftwareBrothers/adminjs-expressjs/pull/88

It's will be very helpful if you can approve it

Thanks.

**Comment by itamar-owlytics** [comment]
🥲
