### ISSUE TITLE
Custom action component does not get bundled 

### ISSUE THREAD

**Issue by danielpowster** [SoftwareBrothers/adminjs#1238]
**Describe the bug**
I am trying to implement a custom edit action with a custom component according to the documentation. I have implemented the handler, added the action to the resource and implemented the component. When executing the action, I receive the following error: You have to implement action component for your Action, although I have implemented it and bundled it with AdminJs

**Installed libraries and their versions**
* adminjs@6.0.6
* @adminjs/express@^5.0.0
* @adminjs/sequelize@^3.0.0

**To Reproduce**
Steps to reproduce the behavior, giving a minimal example that reproduces the bug without adding the actual logic 
1. Add custom action to adminjs:
```
const admin = new AdminJS({
resource: sequelize_st.models.movieRegion,
      options:{
          actions:{
            match: {
                  actionType: 'record',
                  icon: 'Compare',
                  isVisible: true,
                  handler: matchMovies,
                  component: AdminJS.bundle('./customisation/components/match-movies'),
                }
            }
        }
```
2. Custom component `./customisation/components/match-movies.jsx`:
```
import React from 'react';
import { NoticeBox } from "adminjs";

/**
 * @name MatchMovies
 * @category Actions
 * @description Shows a given record.
 * @component
 */
const MatchMovies = (props) => {
    const { resource, record, action } = props;
    action.name = 'match'
    const properties = resource.showProperties;
    return (<NoticeBox>Testing custom component</NoticeBox>);
};
export default  MatchMovies;`
```
3. Custom handler:
```
const matchMovies: ActionHandler<RecordActionResponse>  = async (
    request,
    response,
    context
    ) => {
        // Logic to retrieve record
        return {record: record}
```

**Expected behavior**
Custom component is rendered. 

**Screenshots**
![Screenshot 2022-09-06 at 18 14 30](https://user-images.githubusercontent.com/109143753/188698785-49121e87-2a2c-4e84-80e4-c82992a3c66c.png)

**Comment by dziraf** [comment]
```
      options:{
          match: {
                actionType: 'record',
                icon: 'Compare',
                isVisible: true,
                handler: matchMovies,
                component: AdminJS.bundle('./customisation/components/match-movies'),
              }
        }
```
This doesn't look like a correct configuration, actions should be defined under `options -> actions`, not directly under `options`.

**Comment by danielpowster** [comment]
Thank you for your quick response. I had this configured correctly in my example, this mistake got introduced when I copied the code snippet to report the issue, apologies for that. This is the code I use and still face the issue, I will update the original post as well. 
```
const admin = new AdminJS({
resource: sequelize_st.models.movieRegion,
      options:{
          actions:{
            match: {
                  actionType: 'record',
                  icon: 'Compare',
                  isVisible: true,
                  handler: matchMovies,
                  component: AdminJS.bundle('./customisation/components/match-movies'),
                }
            }
        }
```

**Comment by dziraf** [comment]
What's your operating system (the system where you're running AdminJS)?

Do you use Typescript? I see that you have types in your handler but your component is `jsx`. Are you sure the component is copied into `dist`?

Have you tried with minimal component, e. g. a component returning `<div>something</div>`?

**Comment by danielpowster** [comment]
I am on macOS Monterey v 12.4

I am using typescript. Here is the minimal component:
`./customisation/components/match-movies.tsx`

```
import React from 'react';
import { ActionProps, } from "adminjs";

/**
 * @name MatchMovies
 * @category Actions
 * @description Shows a given record.
 * @component
 */
const MatchMovies: React.FC<ActionProps> = (props) => {
    return (<div>Some Action Content</div>);
};
export default  MatchMovies;
```

This is the resulting .jsx file, which is generated into the same folder `./customisation/components/match-movies.jsx`: 
```
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = __importDefault(require("react"));
/**
 * @name MatchMovies
 * @category Actions
 * @description Shows a given record.
 * @component
 */
const MatchMovies = (props) => {
    return (<div>Some Action Content</div>);
};
export default MatchMovies;
```

I have noticed that on starting adminjs I get the following warning, I am including it in case they are relevant:
`The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten`

**Comment by dziraf** [comment]
That warning shouldn't matter. Is the action definition file in the same folder as the original one or is it moved to `build`, `dist`, `lib` etc?

**Comment by danielpowster** [comment]
The handler function is defined in `./customisation/ActionHandlers.ts`. tsc compiles the .js file into the same folder:
`./customisation/ActionHandlers.js`. 

> For more context, AdminJS doesn't rely on Typescript to build React files, instead it uses rollup to do this. That's why when you put a relative path in AdminJS.bundle it has to be relative to the file in Typescript's output directory.

So I should not use tsc to compile the .tsx file to .jsx? I tried re-running after removing the .jsx file but I am still getting the same result. The relative path to both files is/was the same

Really appreciate your help in figuring this out

**Comment by dziraf** [comment]
The files can be compiled to `jsx`, what matters is that the file should preserve ES Module syntax (`jsx: "react"` in tsconfig). You can also consider specifying an absolute path to the file or a path from the root directory like:

```
AdminJS.bundle(path,join(process.cwd(), 'dist/customisation/components/match-movies'))
```

**Comment by dziraf** [comment]
Can you try to change contents of your component to?

```
import React from 'react';
import { ActionProps } from "adminjs";

const MatchMovies: React.FC<ActionProps> = (props) => {
    return (<div>Some Action Content</div>);
};
export default  MatchMovies;
```

Also, can you check if `.adminjs` folder is created when you start the server?

Another reason why this happens could be something wrong inside of your component. I haven't used jsdoc in custom components personally so there might be some kind of parsing problem?

**Comment by danielpowster** [comment]
I have tried with updating my component to your example. I can confirm that the .adminjs folder is created when I start the server, it is created in the root directory, not in dist. I have also tried copying this folder to dist to see if that makes a difference, but still same result
