### ISSUE TITLE
Adapter without ORM

### ISSUE THREAD

**Issue by wirekang** [SoftwareBrothers/adminjs#1239]
**Describe the problem feature solves**
It would be great if `adminjs` supports raw sql adapter.

**Describe the solution you'd like**
I'm trying to make this adapter using `INFORMATION_SCHEMA` database on mysql/mariadb.

**Comment by dziraf** [comment]
@wirekang Thanks for contributing to the project 😄 If you need any technical help with maintaining or developing this, send us a message (preferably on our [Slack](https://adminjs.page.link/slack))

CC @krzysztofstudniarek
