### ISSUE TITLE
AdminJS doesn't work anymore with node slim docker image

### ISSUE THREAD

**Issue by felix-zg** [SoftwareBrothers/adminjs#1244]
**Describe the bug**
After upgrade the version from 6.1.1 to any version 

**Installed libraries and their versions**

* adminjs@6.2.2
* @adminjs/express@4.1.3
* @adminjs/sequelize@2.1.5

**To Reproduce**
```
FROM node:16-slim

WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./
RUN npm install -g npm
```

**Screenshots**
`#9 144.6 npm ERR! npm ERR! code 1
#9 144.6 npm ERR! npm ERR! path /root/.npm/_cacache/tmp/git-clonelCpAxN/node_modules/@parcel/watcher
#9 144.6 npm ERR! npm ERR! command failed
#9 144.6 npm ERR! npm ERR! command sh -c -- node-gyp-build
#9 144.6 npm ERR! npm ERR! gyp info it worked if it ends with ok
#9 144.6 npm ERR! npm ERR! gyp info using node-gyp@9.1.0
#9 144.6 npm ERR! npm ERR! gyp info using node@16.17.0 | linux | arm64
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python 
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python checking if "python3" can be used
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python checking if "python" can be used
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python 
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python **********************************************************
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python You need to install the latest version of Python.
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python you can try one of the following options:
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python For more information consult the documentation at:
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python **********************************************************
#9 144.6 npm ERR! npm ERR! gyp ERR! find Python 
#9 144.6 npm ERR! npm ERR! gyp ERR! configure error 
#9 144.6 npm ERR! npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
#9 144.6 npm ERR! npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#9 144.6 npm ERR! npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#9 144.6 npm ERR! npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#9 144.6 npm ERR! npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#9 144.6 npm ERR! npm ERR! gyp ERR! stack     at exithandler (node:child_process:408:5)
#9 144.6 npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:420:5)
#9 144.6 npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#9 144.6 npm ERR! npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#9 144.6 npm ERR! npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
#9 144.6 npm ERR! npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#9 144.6 npm ERR! npm ERR! gyp ERR! System Linux 5.10.104-linuxkit
#9 144.6 npm ERR! npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#9 144.6 npm ERR! npm ERR! gyp ERR! cwd /root/.npm/_cacache/tmp/git-clonelCpAxN/node_modules/@parcel/watcher
#9 144.6 npm ERR! npm ERR! gyp ERR! node -v v16.17.0
#9 144.6 npm ERR! npm ERR! gyp ERR! node-gyp -v v9.1.0
#9 144.6 npm ERR! npm ERR! gyp ERR! not ok`

**Comment by dziraf** [comment]
This should be solvable in your Dockerfile: https://stackoverflow.com/questions/59470406/how-to-solve-could-not-find-any-python-installation-to-use-with-docker-node-al
