### ISSUE TITLE
 "Join our community on Slack" link on homepage is dead again #1186 

### ISSUE THREAD

**Issue by on21life** [SoftwareBrothers/adminjs#1248]
The big button "Join our community on Slack" on your [homepage](https://adminjs.co/) is no longer working:
![image](https://user-images.githubusercontent.com/40256435/189511335-dfa6c3cc-f850-4be3-8a84-480c01f08910.png)

**Comment by dziraf** [comment]
The correct link is:
https://adminjs.page.link/slack

We will update the button on the website

**Comment by on21life** [comment]
> The correct link is: https://adminjs.page.link/slack
> 
> We will update the button on the website

[ttps://adminjs.page.link/slack](https://adminjs.page.link/slack) your link is redirected at same page 
![image](https://user-images.githubusercontent.com/40256435/189719026-261c0b11-4f93-40a8-8024-87ffbbd550cd.png)

**Comment by dziraf** [comment]
@on21life the link should now be working. It looks like there's a limit of 100 people that can join through an invite link so we'll have to refresh those regularly.
