### ISSUE TITLE
Can't install adminjs

### ISSUE THREAD

**Issue by king-sley-o** [SoftwareBrothers/adminjs#1252]
Getting this error when trying to install adminjs

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Tried yarn install and npm install --force still the same thing

**Comment by dziraf** [comment]
Can you share more information about your environment, operating system, etc? I've just tried to install it in a new app and there were no issues except for some warnings:
```
rafaldziegielewski@Rafas-MacBook-Pro adminjs-test % npm i
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-text-mask@5.4.3
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.1.0" from adminjs@6.2.3
npm WARN   node_modules/adminjs
npm WARN     adminjs@"^6.2.3" from the root project
npm WARN     1 more (@adminjs/express)
npm WARN   22 more (@adminjs/design-system, react-dom, styled-components, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-text-mask@5.4.3
npm WARN node_modules/react-text-mask
npm WARN   react-text-mask@"^5.4.3" from @adminjs/design-system@3.0.1
npm WARN   node_modules/@adminjs/design-system
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-text-mask@5.4.3
npm WARN   node_modules/react-text-mask
npm WARN     react-text-mask@"^5.4.3" from @adminjs/design-system@3.0.1
npm WARN     node_modules/@adminjs/design-system
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 558 packages, and audited 559 packages in 2m

77 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by king-sley-o** [comment]
Docker on windows, node version 16

**Comment by ReisoAphi** [comment]
This issue is happening because you don't have Git installed or the terminal from where you are running "npm i adminjs" doesnt have access to it, just do a quick test on the terminal and run 'Git' command to make sure its running.

**Comment by king-sley-o** [comment]
> This issue is happening because you don't have Git installed or the terminal from where you are running "npm i adminjs" doesnt have access to it, just do a quick test on the terminal and run 'Git' command to make sure its running.

I usually exec into the container (docker exec -it container_name sh) and install packages. I installed adminbro that way last week and other packages without issues. Seems the adminbro site is down and I think it's right to move on with adminjs. There is git but git commands don't run in the container

**Comment by dziraf** [comment]
Does the problem still exist on the latest versions of our packages? We currently don't have any dependencies that link to github repositories instead of npm registry.
