### ISSUE TITLE
How to pass CSS to the dashboard?

### ISSUE THREAD

**Issue by ReisoAphi** [SoftwareBrothers/adminjs#1254]
I'm trying to create my own dashboard but when I send the react to it, it doesnt work with the CSS, how can I set this up ?
![image](https://user-images.githubusercontent.com/87125229/190484139-a253dcd6-581e-4f41-911c-7a5fe1fa734c.png)

**Comment by Adeshpreet-Singh** [comment]
![XD](https://user-images.githubusercontent.com/95892485/190578729-04164212-e77d-471d-ad8e-953b084f6bf1.jpg)

This will help you. 
Make sure you use JSX or TSX extension only for dashboard component.
