### ISSUE TITLE
Tooltip removes special characters

### ISSUE THREAD

**Issue by GuiziBr** [SoftwareBrothers/adminjs#1259]
**Describe the bug**
When adding a description to a property so the tooltip can be displayed in the edit page, all special characters are removed (even using html code), all text words are capitalized and long texts are covered by side menu

**Installed libraries and their versions**

* adminjs@5.5.1
* @adminjs/express@4.0.1
* @adminjs/nestjs": "^4.0.1",
* "react": "^16.13.1",

**To Reproduce**
1. Add the property "description" to any resource
2. Enter a text with special characters like "%"or "$" (tried using html codes as well)

**Expected behavior**
Tooltip should display special characters
Tooltip should not capitalize all words
There should be a way to control how the tooltip is displayed so it not be covered by the menu

**Screenshots**
<img width="1119" alt="Screen Shot 2022-09-20 at 2 42 11 PM" src="https://user-images.githubusercontent.com/20206194/191370084-f0c7f0f8-0526-467a-b6be-aeb70b260243.png">

**AdminJSOptions with schema**
Paste your AdminJS config with database schema if it could be related to the issue

**Desktop (please complete the following information if relevant):**
 - OS: MacOS
  - Browser Chrome
 - Version 105.0.5195.125

**Comment by dziraf** [comment]
Can you share your property configuration? To support special characters you might have to use locale/translation like in the example here:
https://github.com/SoftwareBrothers/adminjs/blob/master/src/backend/decorators/property/property-options.interface.ts#L117
