### ISSUE TITLE
Allow properties to be disabled for certain users

### ISSUE THREAD

**Issue by wdfinch** [SoftwareBrothers/adminjs#1260]
**Describe the problem feature solves**
I have a resource, and within that resource there are properties. I want to disable the editing of certain properties **only** for certain users. I can hide actions using an `IsFunction` which gets the current user and returns a boolean. I would like something similar for the `isDisabled` options on `PropertyOptions`.

**Describe the solution you'd like**
On `PropertyOptions` allow `isDisabled` to be of type `boolean` or `IsFunction`.

**Describe alternatives you've considered**
Setting the variable to false for everyone and manually making changes myself when requested to the restricted fields.

**Acceptance criteria**
NA

**Comment by dziraf** [comment]
You could try to use `layout` in an action:
```
  edit: {
      layout: (currentAdmin) => {
          if (currentAdmin.role === 'admin') {
              return ['name', 'email', 'consulLocation', 'roles', 'userPassword'];
          }
          return ['name', 'userPassword'];
      },
  },
```
There is currently no way to differentiate `edit` and `new` using layout though and if you want different properties to be displayed in `new`, then you'd need a custom component for that.
