### ISSUE TITLE
Block properties and actions

### ISSUE THREAD

**Issue by olucasandrade** [SoftwareBrothers/adminjs#1261]
I'm new on AdminJS so sorry if i don't know about something. But i have on my database some properties like `active` and `creationDate` that cannot be created by admin, because on creation, they are default values (`true` and `new Date()`, respectively). I need to disable this fields or something like that.

Besides that, i need also to block some resource actions, like delete and create in some collections. I appreciate any help everyone can give me, i'm lost LOL

**Installed libraries and their versions**

* adminjs@4.0.1
* @adminjs/express@2.0.0
* @adminjs/mongoose@1.4.0

**Comment by dziraf** [comment]
For actions: https://docs.adminjs.co/basics/action#changing-visibility-and-accessibility-of-an-action
For properties: https://docs.adminjs.co/basics/resource#changing-visibility-of-properties

**Comment by olucasandrade** [comment]
Thank you! @dziraf! I still have some things to solve but you helped me most
