### ISSUE TITLE
Support for AdonisJS

### ISSUE THREAD

**Issue by pinkynrg** [SoftwareBrothers/adminjs#1279]
I quickly read the "getting started" documentation and it looks like AdonisJS is not supported.  Am I correct? If yes, will it be supported in the future? 

It looks to be a pretty popular MVC server written in Node and I was sad not to find support for it.

Thanks :)

**Comment by dziraf** [comment]
cc @krzysztofstudniarek

**Comment by krzysztofstudniarek** [comment]
Hey @pinkynrg 

Currently we're focusing on different aspects of AdminJS. Adding AddonisJS is not on our roadmap currently.

Kind regards,
Krzysztof Studniarek
