### ISSUE TITLE
User gets Stuck b/w "Edit" and "Show" Screen ,when User taps on Back button from Edit Screen

### ISSUE THREAD

**Issue by hasrat-malik** [SoftwareBrothers/adminjs#1281]
The user gets Stuck on b/w "Edit" and "Show" Screen when the User taps on the Back button from Edit Screen in the admin js

* adminjs@5.10.0
* @adminjs/express@4.1.0
* @adminjs/sequelize@2.1.5
... mongo, express (whatever you think is relevant)

1. Open one Record from the list
2. Click on “Edit” >> Click on the “Back” Button
3. Again Click on the “ Back” Button
4. See the error

Expected behavior:
User should navigate out from the record list page

Actual result  :
The user gets Stuck b/w  "Edit"  and "Show" Screen

**Comment by dziraf** [comment]
@hasrat-malik we're currently working on fixing this.

**Comment by dziraf** [comment]
This should now be fixed.

- actions displayed in the default page view do not have back button next to breadcrumbs anymore, use browser's back button
- actions displayed in the drawer have a back button which navigates back to parent route
