### ISSUE TITLE
Rest API & API Client Don't work

### ISSUE THREAD

**Issue by goldylucks** [SoftwareBrothers/adminjs#1284]
**Describe the bug**
Rest API
All requests redirect, even when passing auth:
```
$ curl http://localhost:8002/admin/api/resources/Users/records/6353a5c5c88b2dfadeb6ba27/login -u goldy@adamgoldman.me:1234
Found. Redirecting to /admin/login
```

API Client
Inside a cypress e2e test, this crashes:

```
import { ApiClient } from "adminjs"
```

so had to do:
```
import ApiClient from "adminjs/lib/frontend/utils/api-client.js"
const adminjsApi = new ApiClient()
adminjsApi.baseUrl = "http://localhost:8002"

adminjsApi.recordAction({
          resourceId: "Users",
          recordId: this.user._id,
          actionName: "delete",
        })
```

but the baseUrl doesn't do anything.

**Installed libraries and their versions**

* adminjs@6.2.2
* @adminjs/express@5.0.0
* @adminjs/mongoose@3.4.0
"express": "4.17.2",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",

**To Reproduce**
1. bootstrap adminjs app
2. try to use rest API or api client outside adminjs

**Expected behavior**
Rest API and API client should work by somehow passing authorization. I see two options here:
1. make a login request thus setting the cookie, then make subsequent requests
2. pass auth header to each request, like user:pass

**Comment by rodrigorssa** [comment]
Same here.

**Comment by dziraf** [comment]
`ApiClient` was never meant to be used outside of AdminJS panel, it's an internal client for the ui to communicate with the backend

**Comment by goldylucks** [comment]
Is there a reason for that?

**Comment by dziraf** [comment]
No particular reason, we've just never had a reason to use it outside of AdminJS and it's purpose was to be an internal client. We can consider making it a client that works outside of AdminJS, but tbh it's just a wrapper around `axios`.

**Comment by goldylucks** [comment]
Gotcha.

What about the API endpoints?
That doesn't work as well, eg

```
$ curl http://localhost:8002/admin/api/resources/Users/records/6353a5c5c88b2dfadeb6ba27/login -u goldy@adamgoldman.me:1234
Found. Redirecting to /admin/login
```

**Comment by dziraf** [comment]
I think you'd first have to retrieve the cookie from `/admin/login` and use it in subsequent requests although I'm unsure, haven't had a need to use it outside of AdminJS as well 🤔

**Comment by goldylucks** [comment]
hmm, so not very usable :)

ok, closing
