### ISSUE TITLE
Import an external package from within a custom component

### ISSUE THREAD

**Issue by jdme** [SoftwareBrothers/adminjs#1286]
I'm trying to create a custom component to edit a property, but struggled with an issue.
[Documentation](https://docs.adminjs.co/tutorials/writing-your-own-components#dependencies) says:

> AdminJS bundler gives you the ability to import following dependencies without the need of requiring them in your package.json file:

But what if I want to use an external package, how should I require it?
I've installed a package to the main `package.json` file, added an import to the custom component `edit.jsx`, but got the error:

> Unexpected token (Note that you need plugins to import files that are not JavaScript)

It seems like the AdminJS bundler can't import a package from outside the adminjs directory. 
What's the correct way to do the import?

**Comment by dziraf** [comment]
Please share your code. Currently it's impossible to directly import css files into your components

**Comment by jdme** [comment]
> Please share your code. Currently it's impossible to directly import css files into your components

@dziraf thank you for the reply and sharing the idea about css. It seems the react component, which I import [jsoneditor-react](https://github.com/vankop/jsoneditor-react), is importing css file internally. With another library [vanilla-jsoneditor](https://www.npmjs.com/package/vanilla-jsoneditor) it works just fine.
