### ISSUE TITLE
Selecting multiple categories

### ISSUE THREAD

**Issue by twensons** [SoftwareBrothers/adminjs#1287]
Hello! Thank you for such a great admin panel!
I have small problem. I can't get multiple categories to be selected.

I have "Categories" mongo model:
```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const CategoriesSchema = new Schema({
    name: { type: String, required: true, unique: true },
    uri: { type: String, required: true, unique: true },
})

module.exports = mongoose.model('Categories',CategoriesSchema)
```

And i have "Products" mongo model:
```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ProductsSchema = new Schema({
    name: { type: String, required: true, unique: true },
    uri: { type: String, required: true, unique: true },
    productBrand: { type: Schema.Types.ObjectId, ref: 'Brands' },
    productCategory: { type: Schema.Types.ObjectId, ref: 'Categories' },
    productIngridients: { type: String, required: false, unique: false },
    description: { type: String, required: false, unique: false }
});

module.exports = mongoose.model('Products',ProductsSchema)
```

As you can see, i am passing the list of categories via:
    `productCategory: { type: Schema.Types.ObjectId, ref: 'Categories' }`

And for adding one category, it works perfect!

But, i can't understand how to select multiple categories, not only one: https://prnt.sc/rB8NSEwgnQOU

I try to add in options for Products `isArray: true`, and i can select multiple categories, but when try to save, got error:
`Cast to ObjectId failed for value "63514925e55a76ee21284976,63511b1502c7ecd6f0bb19fb" (type string) at path "categoryId" because of "BSONTypeError"`

Can you please help me, maybe there is another method?

**Comment by matex1024** [comment]
Currently, we don't support out of the box many to many relations in any ORMS that we have plugin. For mongo you will have to create your own solution that allows you to connect multiple categories. We have plan to add this in futurefor all ORM. Here is some useful information for how this should work in monoose https://stackoverflow.com/a/17223701

**Comment by twensons** [comment]
Thanks for your answer!
