### ISSUE TITLE
'isAccessible' action property throws undefined when using custom action/component

### ISSUE THREAD

**Issue by AndiLuo** [SoftwareBrothers/adminjs#1293]
**Describe the bug**
I'm trying to implement access control using the 'isAccessible' action property. Currently, I'm storing a 'permissions' array in the 'CurrentAdmin' context of adminJs and accessing it through the isAccessible parameter. 

So far, this works for the base AdminJS CRUD operations (new, delete, show, list...etc). However, it's not working when I pass 'isAccessible' in to a **custom action** tied to a **custom component**. When doing so, the 'CurrentAdmin' object returns undefined. I have provided some screenshots, any help would be appreciated! Thank you.

For Example:

**This Works:**
`edit: {
        isAccessible: ({ currentAdmin }) =>
           currentAdmin.permissions.includes('edit-user');
},`

**This does not:**
![image](https://user-images.githubusercontent.com/32887729/200390285-902e5d95-8a67-4b77-8736-801eadfd516e.png)

In this console, it sees the users permissions on initial click but then throws UNDEFINED once it enters the custom component.
![image](https://user-images.githubusercontent.com/32887729/200389782-23f64208-1e25-4e83-9a91-521d610f26ee.png)

I followed these docs: https://docs.adminjs.co/tutorials/adding-role-based-access-control

**Installed libraries and their versions**
* adminjs@6.4.1
* @adminjs/express@4.0.0
* @adminjs/nestjs@4.0.1

**Comment by dziraf** [comment]
I've just checked in one of our projects and it looks to be working correctly, can you show your custom component?

**Comment by dziraf** [comment]
Closing due to lack of response
