### ISSUE TITLE
React error in production

### ISSUE THREAD

**Issue by dhwaj1902** [SoftwareBrothers/adminjs#1298]
**Describe the bug**
While going for production, I am getting this error for the react when I implement the authentication.

```Minified React error #321```

![image](https://user-images.githubusercontent.com/57860123/201385216-083891cd-ea51-4e69-98a3-25b25e7c91d1.png)

**Comment by matex1024** [comment]
please check our example-app authentication integration.

**Comment by dziraf** [comment]
You seem to be using `admin-bro` which is outdated, we rebranded to `adminjs` in June 2021.

Make sure all your packages are `adminjs` and `@adminjs/*` for subpackages.
