### ISSUE TITLE
Custom dashboard link is broken

### ISSUE THREAD

**Issue by rayryu7** [SoftwareBrothers/adminjs#1301]
**Describe the bug**
Custom dashboard link is broken. https://docs.adminjs.co/tutorial-custom-dashboard.html
How I can customize dashboard? 
I tried to revise this file "adminjs/src/frontend/components/app/default-dashboard.tsx" and build but nothing changed

**Comment by dziraf** [comment]
https://docs.adminjs.co/ui-customization/writing-your-own-components#overriding-internal-adminjs-components

You can use component loader `override` to override `'Dashboard'`.

**Comment by BrandonNunes** [comment]
Hi everyone, error trying to overwrite component
_Error: Component 'Dashboard' is not defined, use .add() instead
    at ComponentLoader.override_ 
    my code:
 ```
import { ComponentLoader } from 'adminjs'
const componentLoader = new ComponentLoader()

const Components = {
    MyDashboard: componentLoader.override('Dashboard', './components/my-dashboard', ),
}
export { componentLoader, Components }
```
There is something wrong?

**Comment by dziraf** [comment]
@BrandonNunes try `.add` instead of `.override`. It seems `Dashboard` is not a part of `OverridableComponent`

**Comment by BrandonNunes** [comment]
> @BrandonNunes try `.add` instead of `.override`. It seems `Dashboard` is not a part of `OverridableComponent`

Thanks!, work for me. :)
