### ISSUE TITLE
All errors are 500 w/o any meaningful info

### ISSUE THREAD

**Issue by goldylucks** [SoftwareBrothers/adminjs#1308]
**Describe the bug**
All errors we've encountered so far are 500 errors w/o any info, so there's no way of knowing what went wrong. This is true for bad data sent, 404s masking as 500, and bad get requests eg:

```
// throws 500
http://localhost:8002/admin/api/resources/ToolRecord/actions/list?filters.user=Adam&page=1

// works
http://localhost:8002/admin/api/resources/ToolRecord/actions/list
```

**Installed libraries and their versions**

* adminjs@6.2.2
* @adminjs/express@5.0.0
* @adminjs/mongoose@3.0.0
* mongoose 6.4.7
* 4.17.2
* 

**To Reproduce**
Any error would do

**Expected behavior**
Get back the real error, not a meaningless 500

**Comment by dziraf** [comment]
```
http://localhost:8002/admin/api/resources/ToolRecord/actions/list?filters.user=Adam&page=1
```
This is likely related to a database error where e. g. `user` field does not exist or is not a `string` type. From my experience with TypeORM/Sequelize, you should be able to see the exact database error in your server's console as long as you enable logging. In case of database errors 500 is a valid status code and it shouldn't be expected to return server/database error to the end user in the app.

**Comment by goldylucks** [comment]
why not return a meaningful error?

**Comment by dziraf** [comment]
Most of the time, as long as database logging is enabled you will see both AdminJS error and the database error in server's console.

Any database error is a valid 5XX error which should not be displayed to the end user, a non-technical person. It should be logged in server's logs so that developer can investigate it but it should never reach end users.
