### ISSUE TITLE
No drop-down menu for a string array field with pre-defined enum values.

### ISSUE THREAD

**Issue by XaFaK-01** [SoftwareBrothers/adminjs#1315]
**Describe the bug**
I have defined a field in my collection as an array of enums. When in editing mode, those enum values are not being shown in the drop-down menu.

Here's the screenshot for the collection of the String type array with defined enums:
![String type array with defined enums](https://user-images.githubusercontent.com/65566056/204407407-257a4a29-f6f1-4789-98e7-6097cec4a880.png)

Here's the field for the animals' string array with defined enums, for which no drop-down menu is provided:
![Here's the field for the animals' string array with defined enums, for which no drop-down menu is provided](https://user-images.githubusercontent.com/65566056/204407655-940554f1-8fa8-46d2-b4f8-3aefbdcf5d95.png)

Here's how it should appear:
![A drop-down menu should appear at the right end showing all the available pre-defined enums](https://user-images.githubusercontent.com/65566056/204408263-0a5ff9bd-1917-453a-9755-30ba11a690a0.png)

**Installed libraries and their versions**

* adminjs@^6.6.5
* @adminjs/express@^5.0.1
* @adminjs/mongoose@^3.0.1
* mongoose@^6.7.2

**Comment by dziraf** [comment]
You can use `availableValues` in resource options for your property:

```
properties: {
  animals: {
    type: 'string',
    isArray: true,
    availableValues: ['cat', 'dog', 'etc']
  }
}
```

**Comment by XaFaK-01** [comment]
> You can use `availableValues` in resource options for your property:
> 
> ```
> properties: {
>   animals: {
>     type: 'string',
>     isArray: true,
>     availableValues: ['cat', 'dog', 'etc']
>   }
> }
> ```

Thanks for replying. 

That didn't exactly work as I expected, so this is how I overcame this issue:

` properties: {
  animals: {
    type: "string";
    isArray: true;
    availableValues: [{ value: "cat"; label: "Cat" }, { value: "dog"; label: "Dog" }];
  };
};
`
