### ISSUE TITLE
Slack invite - Expired

### ISSUE THREAD

**Issue by RoseyWasTaken** [SoftwareBrothers/adminjs#1326]
**Describe the bug**
Slack invite has expired.

**Installed libraries and their versions**
n/a

**To Reproduce**
1. Go to https://github.com/SoftwareBrothers/adminjs
2. Click on [Join the community](https://join.slack.com/t/adminbro/shared_invite/zt-1c7z4k0v9-kBNAivB8lX3OWLWu6TLE7A) to get help and be inspired.
3. See error.

**Expected behavior**
An invite for the slack server should be provided. 

**Screenshots**
![image](https://user-images.githubusercontent.com/112476500/205767277-fb84e947-e7aa-425f-a02b-78dbc69ed959.png)
![image](https://user-images.githubusercontent.com/112476500/205767440-7e6a2e02-d24d-4084-baec-eab2d68cc135.png)

**AdminJSOptions with schema**
n/a

**Desktop (please complete the following information if relevant):**
n/a

**Smartphone (please complete the following information if relevant):**
n/a

**Additional context**
Hire me :^)

**Comment by dziraf** [comment]
Slack invitation link should be working now
