### ISSUE TITLE
Deployment not working on Heroku.

### ISSUE THREAD

**Issue by XaFaK-01** [SoftwareBrothers/adminjs#1331]
**Describe the bug**

I can run it on my local system but cannot run it on Heroku.
After deploying to Heroku and defining all the environment variables in the Heroku "Config Vars" section, the deployment is not working.

The following are the configurations:
Scripts in: `packachange.json`:
 
```
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "nodemon app.ts",
    "start": "ts-node app.ts"
  }, 

```
and I only have a single `app.ts` configuration:

```

const adminJS = new AdminJS({
  databases: [],
  rootPath: "/",
  branding: {
   ...
  },
  componentLoader,
  dashboard: {
    component: Components.Dashboard,
    handler: dashboardHandler,
  },
  resources: [
  ...
  ],
});


// @ts-ignore
const authenticate = async (email, password) => {
  // @ts-ignore
  const user = await Admin.findOne({ email });
  if (user) {
    if (await bcrypt.compare(password, user.password)) {
      return user;
    }
  }
  return false;
};

const adminJSRouter = AdminJSExpress.buildAuthenticatedRouter(
  adminJS,
  {
    authenticate,
    cookieName: process.env.COOKIE_NAME,
    // @ts-ignore
    cookiePassword: process.env.COOKIE_PASSWORD,
  },
  null,
  {
    store: MongoStore.create({
      mongoUrl: process.env.MONGO_URI_DEV,
      touchAfter: 24 * 3600, // time period in seconds
    }),
    resave: true,
    saveUninitialized: true,
    secret: process.env.SESSION_SECRET,
    cookie: {
      httpOnly: process.env.NODE_ENV === "production",
      secure: process.env.NODE_ENV === "production",
    },
    name: process.env.COOKIE_NAME,
  },
);


// mount adminJS route and run express app
const app = express();

const PORT = process.env.PORT || 3000;

app.use(adminJS.options.rootPath, adminJSRouter);

mongoose.connect(
  `${
    process.env.NODE_ENV === "development" ? process.env.MONGO_URI_DEV : process.env.MONGO_URI_PROD
  }`,
);

app.listen(PORT, () =>
  console.log(`AdminJS started on http://localhost:${PORT}${adminJS.options.rootPath}`),
);

```

To be specific, I am getting the following error: 
`FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`

Any help will be really appreciated!

**Installed libraries and their versions**

* "adminjs": "^6.6.5",
* "@adminjs/express": "^5.0.1",
* "@adminjs/mongoose": "^3.0.1",
* "express": "^4.18.2",
* "mongoose": "^6.7.2",

**Comment by dziraf** [comment]
Try to add this env in heroku:
```
NODE_OPTIONS=--max_old_space_size=2048
```

**Comment by dziraf** [comment]
Do you have `NODE_ENV` set to `production`?

**Comment by XaFaK-01** [comment]
> Do you have `NODE_ENV` set to `production`?

yes

**Comment by dziraf** [comment]
How many custom components do you have? Do you use any heavy weight UI libraries like MUI?

**Comment by XaFaK-01** [comment]
So, what do you suggest I do?

**Comment by dziraf** [comment]
Are you able to check the size of `components.bundle.js` locally? Honestly, can't really help much here, I've deployed two apps to Heroku this week without issues.

**Comment by XaFaK-01** [comment]
I ended up using another platform probably because my bundle size was too large for Heroku to handle. Thank you for the explanation along the way.
