### ISSUE TITLE
No routes matched location "/admin"

### ISSUE THREAD

**Issue by wtime** [SoftwareBrothers/adminjs#1332]
**Describe the bug**
With a fresh install of latest version of AdminJS i get some warnings on console:

**emotion-react.esm.js:399** You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.

**global.bundle.js:37577** No routes matched location "/admin" 
warning @ global.bundle.js:37577

**global.bundle.js:37577** No routes matched location "/admin" 
warning @ global.bundle.js:37577

**global.bundle.js:37577** No routes matched location "/admin" 
warning @ global.bundle.js:37577

**Installed libraries and their versions**

*@adminjs/express@5.0.1
*adminjs@6.7.0",
*express@4.18.2",
*express-formidable@1.2.0",
*express-session@1.17.3",
*tslib@2.4.1"

```
import AdminJS from 'adminjs'
import AdminJSExpress from '@adminjs/express'
import express from 'express'

const PORT = 3000

const start = async () => {
  const app = express()

  const admin = new AdminJS({})

  const adminRouter = AdminJSExpress.buildRouter(admin)
  app.use(admin.options.rootPath, adminRouter)

  app.listen(PORT, () => {
    console.log(`AdminJS started on http://localhost:${PORT}${admin.options.rootPath}`)
  })
}

start()
```

**Comment by dziraf** [comment]
These warnings can be safely ignored. The reasoning for why they appear is commented in the library's code. If you set `NODE_ENV` to `production` they shouldn't be visible to your end users.
