### ISSUE TITLE
Add possibility to add links to rich text editor

### ISSUE THREAD

**Issue by ksewo** [SoftwareBrothers/adminjs#1333]
**Describe the problem feature solves**
For now it's only possible to unlink a link in rich text editor. There should be an option to add one too.

**Describe the solution you'd like**
Implement tiptap command for adding links to rich text editor. It would be nice if there could be an option to modify menu bar of richtext editor from adminjs configuration.

**Describe alternatives you've considered**
I've considered implementing it myself, but currently it's really hard to modify menu bar of tiptap editor. I would have to rewrite whole rich text editor component.

**Acceptance criteria**
List of checkpoints which has to be met to mark the issue as completed

**Comment by matex1024** [comment]
Hi, 
   for now you can fork the design system(https://github.com/SoftwareBrothers/adminjs-design-system) and add plugins for tiptap and link this to your project. The reason why we don't add all possible plugins from tiptap is that our bundle size will be too big and that will make also your application loading time increase which we want to avoid. Btw we fixed tiptap issue that we had you can chack the latest version of adminjs.
