### ISSUE TITLE
Richtext component: RangeError: Adding different instances of a keyed plugin (plugin$)

### ISSUE THREAD

**Issue by LarsBehrenberg** [SoftwareBrothers/adminjs#1336]
**Describe the bug**
When trying to add the richtext option to a property I am seeing this output in adminjs. The editor component does not get rendered and I am seeing an error message. I am using adminjs inside a pnpm workspace. This might be the issue? Does anybody have an idea how I can solve this? Big blocker atm...

```
RangeError: Adding different instances of a keyed plugin (plugin$)
```

**Installed libraries and their versions**
```
"devDependencies": {
    "@types/express": "^4.17.15",
    "@types/node": "18.11.15",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.4"
  },
  "dependencies": {
    "@adminjs/express": "^5.0.1",
    "@adminjs/mongoose": "^3.0.1",
    "adminjs": "^6.7.0",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",
    "express-sessions": "^1.0.6",
    "mongoose": "^6.8.0",
    "tslib": "^2.4.1"
  }
```

**To Reproduce**
1. Create a pnpm workspace
2. Add "richtext" to a resource property
3. Run adminjs

**AdminJSOptions with schema**
```
const adminOptions: AdminJSOptions = {
    rootPath: "/",
    resources: [
      {
        resource: Job,
        options: {
          properties: {
            description: { type: "richtext" },
          },
        },
      },
      { resource: Tag, options: {} },
      { resource: Company, options: {} },
      // { resource: Feedback, options: {} },
    ],
  };
```

<img width="776" alt="Screenshot 2022-12-14 at 22 24 35" src="https://user-images.githubusercontent.com/32539217/207607001-bb479949-097e-4e61-bce7-328d3587a00d.png">

<img width="533" alt="Screenshot 2022-12-14 at 22 31 28" src="https://user-images.githubusercontent.com/32539217/207608465-b17c1a90-5d3c-4962-9af7-781816c938d8.png">

**Comment by dziraf** [comment]
This should be fixed once we release:
https://github.com/SoftwareBrothers/adminjs-design-system/pull/66/files

In short, the library we use as a richtext editor (TipTap) made some of it's dependencies peer dependencies, requiring us to install them. NPM/Yarn resolved some of them incorrectly though. Despite all of the packages having `prosemirror-state@^1.4.1` as a dependency, it installed both version `1.4.1` and `1.4.2` resulting in two separate instances being created, hence the error. In the fix I linked, we tell the package manager to resolve the version to `1.4.2`.

Once this is released you will have to either:
a) wait until we release `adminjs` as well with updated `@adminjs/design-system` min. version required
b) update `@adminjs/design-system` yourself if you have it installed in your app
c) remove `adminjs` and reinstall it (it should install `adminjs` with updated design system):
```
$ yarn remove adminjs
$ yarn add adminjs
```

**Comment by LarsBehrenberg** [comment]
@dziraf thanks for the quick reply! Any estimate on when the PR will be released?

**Comment by LarsBehrenberg** [comment]
@dziraf Thanks a lot. All working now. Updating to @adminjs/design-system did the trick.
