### ISSUE TITLE
Cannot find @tiptap/prosemirror-tables module

### ISSUE THREAD

**Issue by TusharRoy23** [SoftwareBrothers/adminjs#1337]
**Describe the bug**
Cannot find **@tiptap/prosemirror-tables** module while building the packages under docker environment.
* node:14-alpine

**Installed libraries and their versions**

* adminjs@6.7.0
* @adminjs/express@5.0.1
* @adminjs/typeorm@4.0.0
* express@4.18.1
* express-formidable@1.2.0
* express-session@1.17.3
* @types/express@4.17.13
* ts-node@10.7.0

**Error**
Error: Cannot find module '@tiptap/prosemirror-tables'
Require stack:
/app/node_modules/@tiptap/extension-table/dist/tiptap-extension-table.cjs
/app/node_modules/@adminjs/design-system/build/molecules/rich-text-editor/rich-text-editor.js
/app/node_modules/@adminjs/design-system/build/molecules/rich-text-editor/index.js

**Expected behavior**
Should Build without facing any error

**Dockerized environment:**
 - Docker version 20.10.17
 - Docker Compose version v2.10.2

**Comment by dziraf** [comment]
What's the version of `@adminjs/design-system` in `node_modules/@adminjs/design-system`'s `package.json`?

**Comment by TusharRoy23** [comment]
> @adminjs/design-system

`"@adminjs/design-system": "^3.0.3"`

**Comment by dziraf** [comment]
I'll release `adminjs` version `6.7.1` soon, it should fix the issue by installing `@adminjs/design-system@^3.1.5`
