### ISSUE TITLE
How to hide properties on list based at logged admin role?

### ISSUE THREAD

**Issue by radekdp** [SoftwareBrothers/adminjs#1340]
Hi,
it is possible to hide some properties on list based at logged admin role?

something like this:

`properties: {     
  password: {
	type: 'password',
	isVisible: {
	  list: function(context) {
		return context.currentAdmin?.role === ERole.ADMIN;
	  },
	  edit: true,
	  filter: false,
	  show: false,
	},
  },
}`
That is, according to above in the user list, only the administrator can see the password column.

I know isVisible doesn't accept functions, but maybe it can be done differently?

**Comment by matex1024** [comment]
this is not possible currently out of the box. it is a custom feature(and custom component) that will change the default behavior.
