### ISSUE TITLE
Bulk action doesn't work

### ISSUE THREAD

**Issue by VladMeleshko** [SoftwareBrothers/adminjs#1341]
Hi! When I try to edit some records using bulkAction, I received next error:
`Record of given id ("undefined") could not be found`
I'm using `ApiClient` instance
```
const api = new ApiClient();

  await api.bulkAction({
    recordIds: ['3', '4'],
    actionName: 'edit',
    resourceId: 'SomeResource',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    data: {
      key: 'value'
    }
  })
```

What I'm doing wrong?

**Comment by dziraf** [comment]
Hi, `edit` is a `record` action, meaning it can only edit a single record at the same time. There is no bulk action for editing available out of the box, you would have to create a new action, e.g.:
```
actions: {
  bulkEdit: {
    actionType: 'bulk',
    component: <your component for editing multiple records at once>,
    handler: <your handler for editing multiple records at once>
  }
}
```

**Comment by VladMeleshko** [comment]
> Hi, `edit` is a `record` action, meaning it can only edit a single record at the same time. There is no bulk action for editing available out of the box, you would have to create a new action, e.g.:
> 
> ```
> actions: {
>   bulkEdit: {
>     actionType: 'bulk',
>     component: <your component for editing multiple records at once>,
>     handler: <your handler for editing multiple records at once>
>   }
> }
> ```

Thanks for your answer!
