### ISSUE TITLE
problem migration admin-bro to adminjs

### ISSUE THREAD

**Issue by faroukbouzouita** [SoftwareBrothers/adminjs#1344]
@dziraf  
I migrated from admin bro to adminjs(last version)
I changed the config but when i start application i have this error:
Error: Cannot find module 'react' i added react dependency after that i have another error
(node:21508) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'useState' of
null
at Object.useState (D:\projets\equipe\back\Equipty-Admin\node_modules\react\cjs\react.development.js:1622:21)
at ae (D:\projets\equipe\back\Equipty-Admin\node_modules\styled-components\src\models\StyleSheetManager.js:34:33)

**Comment by matex1024** [comment]
Hi [faroukbouzouita](https://github.com/faroukbouzouita) follow the that will fix this problem https://github.com/SoftwareBrothers/adminjs/blob/master/CONTRIBUTING.md#basic-example
