### ISSUE TITLE
Error: Resource: "tableName" does not have an id property

### ISSUE THREAD

**Issue by nikola-cyberlab** [SoftwareBrothers/adminjs#1350]
**Describe the bug**

The table name doesn't have "id" as a column inside, I got the error:
The table has only the composite key.

The snippet of table:
```
model VendorFeatures {
  featureId String
  feature   Feature   @relation(fields: [featureId], references: [id])
  vendorId  String
  vendor    Vendor    @relation(fields: [vendorId], references: [id])
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  deletedAt DateTime?
  createdBy String?
  updatedBy String?
  deleted   Boolean   @default(false)

  @@id([featureId, vendorId])
  @@map(name: "vendor_features")
}
```

![image](https://user-images.githubusercontent.com/106950827/208686654-e91ac5db-a49c-49da-a033-bbb13ea16bc1.png)
![image](https://user-images.githubusercontent.com/106950827/208687587-5281f922-264e-4da2-8562-1b658952b34e.png)

**Installed libraries and their versions**
"adminjs": "^6.7.2",
"@adminjs/nestjs": "^5.0.1",
"@adminjs/prisma": "^3.0.1",
postgreSQL

**Expected behavior**
It should render all items from table.

**Comment by dziraf** [comment]
AdminJS requires a primary key, I think you have to add `@id` next to `featureId` in your schema.
