### ISSUE TITLE
Pre fill values redirect

### ISSUE THREAD

**Issue by AshotN** [SoftwareBrothers/adminjs#1354]
**Describe the problem feature solves**
I have an action button that redirects 

```ts
 handler: async (req, res, context) => {
          const { record, currentAdmin, h } = context
          return {
            record: record?.toJSON(currentAdmin),
            redirectUrl: h.resourceActionUrl({
              resourceId: 'invoice_item',
              actionName: 'new'
            })
          }
        }
```
I want to be able to pre-populate some of the fields with the redirect. 

**Describe the solution you'd like**
A property that would allow us to map key: value properties
Or the ability to pass the values in the URL with params like `?myPropery=asdf`

**Describe alternatives you've considered**
Wrapping a custom component, but that just seems really messy.

**Acceptance criteria**
Either the mentioned property or URL based solution

**Comment by AshotN** [comment]
@dziraf any suggestions on how to tackle this if I were to try?

**Comment by dziraf** [comment]
@AshotN 

This should now be possible in the latest versions of AdminJS for `new` action:
https://github.com/SoftwareBrothers/adminjs/blob/da412320e61fe2dddd15ee6ee33adde73dec5565/src/frontend/components/actions/new.tsx#L31

```ts
const search = new URLSearchParams();
search.set('name', 'some_name');

h.resourceActionUrl({
  resourceId: 'invoice_item',
  actionName: 'new',
  search: search.toString(),
})
```
