### ISSUE TITLE
PropertyLabel is not exported correctly

### ISSUE THREAD

**Issue by AshotN** [SoftwareBrothers/adminjs#1355]
**Describe the bug**
Importing PropertyLabel like this
`import { PropertyLabel } from 'adminjs'`

and console.log it you get `undefined`

But if you import it like this
`import { PropertyLabel } from 'adminjs/src/frontend/components/property-type/utils/property-label/property-label'`

and console.log it you get the correct component `function WrapperComponent(props)`

**Installed libraries and their versions**

* adminjs@6.7.2

**Comment by dziraf** [comment]
This should be fixed now

**Comment by nickgieschen** [comment]
This is still a bug for me

**Comment by wtime** [comment]
@dziraf hasn't fixed the bug yet. 
DefaultPropertyValue, convertToSubProperty and removeSubProperty have the same import/export error.
