### ISSUE TITLE
make api client responses simple json

### ISSUE THREAD

**Issue by goldylucks** [SoftwareBrothers/adminjs#1362]
**Describe the problem feature solves**

currently the api returns an non-standard object:
```
redirects.0._id: "63b063da2717f35fa82fa78a"
redirects.0.code: "UL7H"
redirects.0.redirectId: "63b063da2717f35fa82fa788"
```

**Describe the solution you'd like**
Return the same json we all know and love :)

**Describe alternatives you've considered**
N/A

**Acceptance criteria**
Return simple json

**Comment by dziraf** [comment]
The entirety of AdminJS is based on flat data model and rewriting it would consume too much time for little benefit. You can use `flat` library to unflatten the response if needed.
