### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by AshotN** [SoftwareBrothers/adminjs#1363]
**Describe the problem feature solves**
The current version of `react-select` doesn't have the required prop available.

**Describe the solution you'd like**
Please update to the latest version
https://github.com/JedWatson/react-select/releases

**Acceptance criteria**
- [ ] Update react-select

**Comment by dziraf** [comment]
We updated react-select to 5.7.2 in `@adminjs/design-system@^4.0.0`
