### ISSUE TITLE
Remove the default nested resources

### ISSUE THREAD

**Issue by ReisoAphi** [SoftwareBrothers/adminjs#1368]
**Describe the bug**
I want to know how to remove the nested resources on the sidebar, I mean remove the Database Name

![image](https://user-images.githubusercontent.com/87125229/210438598-5c2dc760-4304-4bbb-a541-60bef466257f.png)

How can I do that ?, I want the resources to be always there.

**Comment by dziraf** [comment]
Configure your resources to include `navigation: null` in the options or `navigation: { icon: 'Settings' }`, example:

```
const UserResource = {
  resource: User,
  options: {
    navigation: usersNavigation,
  },
}
```
