### ISSUE TITLE
Middleware not getting called

### ISSUE THREAD

**Issue by slidenerd** [SoftwareBrothers/adminjs#1371]
**Describe the bug**
The adminjs router is not executing middleware function. I am trying to log accesses to admin endpoints along with the details of the adminUser that executed them but it is not working.

**Installed libraries and their versions**

* adminjs@6.7.4
* @adminjs/express@5.0.1

**To Reproduce**
1. Go to admin page for any database model
2. Open the console to check if the path was logged
3. There is no log

**Expected behavior**
The path and the adminUser must be logged

**Screenshots**

**AdminJSOptions with schema**
Paste your AdminJS config with database schema if it could be related to the issue

**Desktop (please complete the following information if relevant):**
 - OS: Mac OS Ventura 13.1
 - Browser Firefox
 - Version 108.0.1

**Additional context**
Why is the middleware below not getting executed?
```

const adminbroRouter = AdminBroExpress.buildAuthenticatedRouter(
  adminBro,
  {
    authenticate: async (email, password) => {
      try {
        const account = await AuthService.getByEmail(email);
        if (!account) {
          return false;
        }
        const { password: accountPassword } =
          await AuthService.getPasswordByEmail(email);
        if (!(await isHashEqual(accountPassword, password))) {
          return false;
        }
        if (!AuthService.isAdmin(account as any)) {
          return false;
        }
        return account;
      } catch (error) {
        return false;
      }
    },
    cookiePassword: ADMINJS_COOKIE_PASSWORD,
    cookieName: ADMINJS_COOKIE_NAME,
    maxRetries: {
      count: ADMINJS_MAX_RETRIES_COUNT,
      duration: ADMINJS_MAX_RETRIES_DURATION,
    },
  },
  null,
  sessionOptions,
);
 
adminbroRouter.use((req, res, next) => {
  // Why is this not being called?
  console.log(req.path, req.adminUser);
  return next();
});

```

**Comment by krzysztofstudniarek** [comment]
As far as I can see you're using the old version of AdminJS. Could you migrate to newest version and check if the issue persists?
