### ISSUE TITLE
Change Visibility of Property but its a subdocumment

### ISSUE THREAD

**Issue by ReisoAphi** [SoftwareBrothers/adminjs#1373]
![image](https://user-images.githubusercontent.com/87125229/211066837-9b48db60-b9e3-4518-ad7f-de6b3f23720d.png)

I have that structure on my mongoose DB,

I'm trying to hide the status property, but its a subdocument. Im trying to do it this way but it doesnt work

properties: {
        equipment: {
         status:{
            isVisible: {
            edit: true,
            show: true,
            list: false,
            filter: false,
          },
         }
        },
      },

Any clue on how to hide thise subdocumments ?

**Comment by dziraf** [comment]
Could you try to define `Status` as subschema? Example:

```
const StatusSchema = new Schema(...);
// ...
status: [StatusSchema]
```

And in your `Controller` resource, try this:

```
'equipment.status': { isVisible: false }
```

AdminJS uses flat model for data, so you cannot nest properties like you did.

**Comment by dziraf** [comment]
Closing due to lack of response
