### ISSUE TITLE
AdminJS.bundle issue on IOS

### ISSUE THREAD

**Issue by fedot199614** [SoftwareBrothers/adminjs#1381]
In production on any IOS device receved this JS error for cudtom jsx components
`Error: Minified React error #130;`
It is reproduced only on IOS
Android and Windows - ok

I am using this code for enabling custom components
1) 
Initialize components 
```const TextEditor = AdminJS.bundle('./adminJsComponents/TextEditor')
        const PhotoComponentSmallPreview = AdminJS.bundle('./adminJsComponents/photoComponent/showPhotoComponentSmallPreview')
        const ShowPhotoComponent = AdminJS.bundle('./adminJsComponents/photoComponent/showPhotoComponent')
        const NewDashBoard = AdminJS.bundle('./adminJsComponents/dashBoardsComponent/newMainDashboard')
        const Logs = AdminJS.bundle('./adminJsComponents/dashBoardsComponent/Logs')
        const DbBackUp = AdminJS.bundle('./adminJsComponents/dashBoardsComponent/DbBackUp')
        const StatusInfo =  AdminJS.bundle('./adminJsComponents/dashBoardsComponent/statusInfo')
        const GoogleAnalytics =   AdminJS.bundle('./adminJsComponents/dashBoardsComponent/googleAnalytics')`
```
 ```
const adminJsOptions = AdminJsOptions({
            TextEditor,
            PhotoComponentSmallPreview,
            ShowPhotoComponent,
            NewDashBoard,
            Logs,
            DbBackUp,
            StatusInfo,
            GoogleAnalytics
        });
```
        
  2) My  AdminJsOptions
  ```
module.exports.AdminJsOptions = (components) => {
    return {
        resources: [
            {
                resource: AdminUsers,
                options: {
                       __Some Code__
            },
             {
                resource: Profile,
                options: {
                    properties: {
                        nickName: {
                            isTitle: true,
                        },
                        owner: {
                            position: 1,
                        },
                        about: {
                            type: 'richtext',
                            components: {
                                edit: components.TextEditor, //here components adding to option example
                            },
                        }
                    },
                    __Some Code__
```
generated .entry.js looks ok 
```AdminJS.UserComponents = {}
import Component1 from '../adminJsComponents/TextEditor'
AdminJS.UserComponents.Component1 = Component1
import Component2 from '../adminJsComponents/photoComponent/showPhotoComponentSmallPreview'
AdminJS.UserComponents.Component2 = Component2
import Component3 from '../adminJsComponents/photoComponent/showPhotoComponent'
AdminJS.UserComponents.Component3 = Component3
import Component4 from '../adminJsComponents/dashBoardsComponent/newMainDashboard'
AdminJS.UserComponents.Component4 = Component4
import Component5 from '../adminJsComponents/dashBoardsComponent/Logs'
AdminJS.UserComponents.Component5 = Component5
import Component6 from '../adminJsComponents/dashBoardsComponent/DbBackUp'
AdminJS.UserComponents.Component6 = Component6
import Component7 from '../adminJsComponents/dashBoardsComponent/statusInfo'
AdminJS.UserComponents.Component7 = Component7
import Component8 from '../adminJsComponents/dashBoardsComponent/googleAnalytics'
AdminJS.UserComponents.Component8 = Component8
```

**Comment by fedot199614** [comment]
I am using this code for enabling custom components
1) 
Initialize components 
`const TextEditor = AdminJS.bundle('./adminJsComponents/TextEditor')
        const PhotoComponentSmallPreview = AdminJS.bundle('./adminJsComponents/photoComponent/showPhotoComponentSmallPreview')
        const ShowPhotoComponent = AdminJS.bundle('./adminJsComponents/photoComponent/showPhotoComponent')
        const NewDashBoard = AdminJS.bundle('./adminJsComponents/dashBoardsComponent/newMainDashboard')
        const Logs = AdminJS.bundle('./adminJsComponents/dashBoardsComponent/Logs')
        const DbBackUp = AdminJS.bundle('./adminJsComponents/dashBoardsComponent/DbBackUp')
        const StatusInfo =  AdminJS.bundle('./adminJsComponents/dashBoardsComponent/statusInfo')
        const GoogleAnalytics =   AdminJS.bundle('./adminJsComponents/dashBoardsComponent/googleAnalytics')

        const adminJsOptions = AdminJsOptions({
            TextEditor,
            PhotoComponentSmallPreview,
            ShowPhotoComponent,
            NewDashBoard,
            Logs,
            DbBackUp,
            StatusInfo,
            GoogleAnalytics
        });`
        
  2) My  AdminJsOptions
  `module.exports.AdminJsOptions = (components) => {
    return {
        resources: [
            {
                resource: AdminUsers,
                options: {
                      ...
            },
             {
                resource: Profile,
                options: {
                    properties: {
                        nickName: {
                            isTitle: true,
                        },
                        owner: {
                            position: 1,
                        },
                        about: {
                            type: 'richtext',
                            components: {
                                edit: components.TextEditor,
                            },
                        }
                    },
                    ...`

**Comment by fedot199614** [comment]
generated .entry.js looks ok 
`AdminJS.UserComponents = {}
import Component1 from '../adminJsComponents/photoComponent/showPhotoComponentSmallPreview'
AdminJS.UserComponents.Component1 = Component1
import Component2 from '../adminJsComponents/photoComponent/showPhotoComponent'
AdminJS.UserComponents.Component2 = Component2
import Component3 from '../adminJsComponents/dashBoardsComponent/newMainDashboard'
AdminJS.UserComponents.Component3 = Component3
import Component4 from '../adminJsComponents/dashBoardsComponent/Logs'
AdminJS.UserComponents.Component4 = Component4
import Component5 from '../adminJsComponents/dashBoardsComponent/DbBackUp'
AdminJS.UserComponents.Component5 = Component5
import Component6 from '../adminJsComponents/dashBoardsComponent/statusInfo'
AdminJS.UserComponents.Component6 = Component6
import Component7 from '../adminJsComponents/dashBoardsComponent/googleAnalytics'
AdminJS.UserComponents.Component7 = Component7`

**Comment by dziraf** [comment]
Does this happen for all components or only specific ones?

**Comment by fedot199614** [comment]
@dziraf For all

**Comment by fedot199614** [comment]
May be one of component, are broken and all not working because of that. But why all works in windows and android.
I will try disabled components one by one to see what happens

**Comment by fedot199614** [comment]
@dziraf should i use componentLoader
’’’
const AdminJS = require('adminjs');
const ComponentLoader = AdminJS.ComponentLoader;

const componentLoader = new ComponentLoader()
’’’
Instead of AdminJS.bundle() ?

**Comment by dziraf** [comment]
`AdminJS.bundle` should work, I'm still using it in some older projects. What libraries do you use in your custom components? Maybe one of them doesn't have ios support? We've tested one of our apps on iOS and it displayed all custom components.

**Comment by fedot199614** [comment]
I discovered that **TextEditor** custom component is the cause of my issue.
In that component i use two libraries CKEditor 4 and LottiePlayer

I think we can close the ticket.
