### ISSUE TITLE
Custom page context doesn't work.

### ISSUE THREAD

**Issue by cesarzxk** [SoftwareBrothers/adminjs#1384]
```Js
//adminjs.ts
const adminJs = new AdminJS({
 pages: {
    ExportData: 
      component: Components.ExportData,
      handler: async (request, response, context) => {
        const { userdata } = context;
        console.log(request);
        console.log(response);
        console.log(context);
        const data = userService.findAllUsersProgress();
        return {
          userdata: { teste: 1254 },
        };
      },
    },
  },
componentLoader,
}),
```

```Js
//Components.ts
import { ComponentLoader } from "adminjs";

const componentLoader = new ComponentLoader();

const Components = {
  ExportData: componentLoader.add("ExportData", "./export"),
  // other custom components
};

export { componentLoader, Components };

```

```Js
//Export.tsx

export default function ExportData({ userdata }: ExportProps) {
  const exportData = async () => {
    const jsonString = `data:text/json;chatset=utf-8,${encodeURIComponent(
      JSON.stringify(userdata)
    )}`;
    const link = document.createElement("a");
    link.href = jsonString;
    link.download = "data.json";

    link.click();
  };
  return (
    <Box padding="24px">
      <Header>
        <H2 margin-bottom="32px">Export user data content</H2>
        <H2>{JSON.stringify(userdata)}</H2>
      </Header>
      <Boddy gap="1rem">
        <Button onClick={() => {}}>CSV</Button>
        <Button onClick={exportData}>JSON</Button>
        <Button>XML</Button>
      </Boddy>
    </Box>
  );
}

```

The userdata always returns undefined in this implementation, I didn't find anything that could help me in the documentation.

* adminjs@6.7.5
* @adminjs/express@5.0.1
* @adminjs/mongoose@3.0.1

**Comment by dziraf** [comment]
I'm not sure where you're putting `userdata` into context though for it to be not `undefined`?

**Comment by cesarzxk** [comment]
> ```js
> handler: async (request, response, context) => {
>         const { userdata } = context;
>         console.log(request);
>         console.log(response);
>         console.log(context);
>         const data = userService.findAllUsersProgress();
>         return {
>           userdata: { teste: 1254 },
>         };
>       },
> ```

Would I have to put it somewhere else besides this one?

**Comment by cesarzxk** [comment]
> I'm not sure where you're putting `userdata` into context though for it to be not `undefined`?



> I'm not sure where you're putting `userdata` into context though for it to be not `undefined`?

> ```js
> handler: async (request, response, context) => {
>         const { userdata } = context;
>         console.log(request);
>         console.log(response);
>         console.log(context);
>         const data = userService.findAllUsersProgress();
>         return {
>           userdata: { teste: 1254 },
>         };
>       },
> ```

Would I have to put it somewhere else besides this one?

**Comment by dziraf** [comment]
Whatever you return in `handler` is sent to the frontend, it has nothing to do with `context`. `context` is a global object scoped to a request with predefined values; you can find currently logged in user in `context.currentAdmin`.

**Comment by cesarzxk** [comment]
> Whatever you return in `handler` is sent to the frontend, it has nothing to do with `context`. `context` is a global object scoped to a request with predefined values; you can find currently logged in user in `context.currentAdmin`.

How do I get these parameters sent by the handler?

**Comment by dziraf** [comment]
Use `ApiClient#getPage`: https://github.com/SoftwareBrothers/adminjs/blob/master/src/frontend/utils/api-client.ts

```
import { ApiClient } from 'adminjs';

// ...

const api = new ApiClient();

// ...

api.getPage({
  pageName: 'ExportData',
  // other axios params, example:
  // method: 'post',
  // data: { /* some json */ } // will be available in request.payload in handler
}).then((response) => ...)
```

**Comment by karanjhinga** [comment]
What's the purpose of getPage function? I'm able to execute it but I needed to pass data from 1 custom page to another custom page but I'm not able to do that.
