### ISSUE TITLE
[Bug]:  can't remove a resource form the admin panel, even though deleted from admin.js

### ISSUE THREAD

**Issue by frikinomad** [SoftwareBrothers/adminjs#1390]
### What happened?

List what you are trying to do?

- I added a resource and when I deleted it it is showing up in the panel 
![image](https://user-images.githubusercontent.com/59007034/213847761-8f1bf570-a87c-451f-a575-1920b3c74072.png)

### Bug prevalence

often

### AdminJS dependencies version

"admin-bro": "^2.9.0",
    "admin-bro-expressjs": "^2.1.1",
    "admin-bro-mongoose": "^0.5.2",

**Comment by frikinomad** [comment]
here the cart was removed from admin.js but it stays there

**Comment by dziraf** [comment]
Please update to the most recent version of AdminJS. AdminBro is a very old package, especially v2 and we rebranded to AdminJS in June 2021. We can't afford time to support old versions of our libraries.

**Comment by frikinomad** [comment]
yeah done.
P.S. : the solution was to remove the database: [<db_name>] which was causing the issue
