### ISSUE TITLE
[Feature]: Sveltekit support

### ISSUE THREAD

**Issue by weepy** [SoftwareBrothers/adminjs#1394]
### Description

Is this possible / planned ?!

### Suggested Solution

Get it working with Sveltekit

**Comment by matex1024** [comment]
Sveltekit is a meta-framework for Svelte using SSR and file system routing. We are using react on frontend and react UI components with react-router. It's impossible for now to port it to Svelte.

**Comment by weepy** [comment]
This is incorrect.
Sveltekit uses a server (vite) but can also be run as a node.js server with express. The fact that adminjs uses react is neither here nor there. 
I suppose a better question would be - can AdminJS be connected to Vite ?

**Comment by dziraf** [comment]
> The fact that adminjs uses react is neither here nor there.

How does it not matter? AdminJS is a SPA application built with React, how do you expect it to work with Svelte without rewriting the entirety of the UI?

**Comment by weepy** [comment]
Sveltekit uses vite as a backend which is agnostic to rendering engine.  So
if Adminjs worked with vite then it would work with Sveltekit.
