### ISSUE TITLE
How to change onClick event on record field to redirect them to edit page instead of show page[Feature]: 

### ISSUE THREAD

**Issue by nitesh-userfacet** [SoftwareBrothers/adminjs#1395]
### Description

When ever User clicks on a record they should be redirected to edit page not on show page

### Suggested Solution

Add any property on resource to modify such onclick actions

**Comment by davoscript** [comment]
Hi @nitesh-userfacet, you can use action hooks to achieve the behavior you are describing:

```
actions: {
    new: {
        after: async (response) => {

          // Redirect to the edit page
          if (response.record)
            response.redirectUrl = `/admin/resources/YOUR_RESOURCE_ID/records/${response.record.id}/edit`;

          return response;
        },
    },
}
```

Hope this helps anyone who may need it. I use to only display a few form fields when creating the record and then presenting the rest once created. This also helps me set some default values in the process.

**Comment by nitesh-userfacet** [comment]
Thanks for responding
