### ISSUE TITLE
[Bug]: adminjs error after installing

### ISSUE THREAD

**Issue by dhwaj1902** [SoftwareBrothers/adminjs#1398]
### What happened?

While installing adminjs I got the below error:
![image](https://user-images.githubusercontent.com/57860123/216476793-da8920ae-584b-4e08-9a10-fef8bf5ca9e4.png) 

### AdminJS dependencies version

@adminjs/design-system: 3.1.6
@adminjs/express: 5.1.0
@adminjs/mongoose: 3.0.1
adminjs: 6.8.2

### What browsers do you see the problem on?

Chrome

**Comment by treyreynolds** [comment]
I am experiencing this problem also. This looks like it could be a problem with tiptap, but I can't find it on their issues

**Comment by krzysztofstudniarek** [comment]
We're taking a look at this issue and fix it as soon as possible

**Comment by krzysztofstudniarek** [comment]
The issue should be fixed in the newest version of AdminJS
