### ISSUE TITLE
Unable to use a .tsx file with Nodejs using commonjs

### ISSUE THREAD

**Issue by eakenbor** [SoftwareBrothers/adminjs#1418]
### What happened?

I tried to override the login template but the .tsx example in the documentation breaks my code. My project uses commonjs and so  I had to convert the code to the following:

````
//Login.tsx
const React = require('react');
const styled = require('styled-components');
const { createGlobalStyle } = require('styled-components');
const { useSelector } = require('react-redux');
const {
  Box,
  H5,
  H2,
  Label,
  Illustration,
  Input,
  FormGroup,
  Button,
  Text,
  MessageBox,
  MadeWithLove,
  themeGet,
} = require('@adminjs/design-system');
const { useTranslation, ReduxState } = require('adminjs');

const GlobalStyle = createGlobalStyle`
  html, body, #app {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
  }
`;

const Wrapper = styled(Box)`
  align-items: center;
  justify-content: center;
  flex-direction: column;
  height: 100%;
`;

const StyledLogo = styled.img`
  max-width: 200px;
  margin: ${themeGet('space', 'md')} 0;
`;

type LoginProps = {
  message?: string;
  action: string;
};

const Login: React.FC<LoginProps> = (props) => {
  const { action, message } = props;
  const { translateLabel, translateButton, translateProperty, translateMessage } = useTranslation();
  const branding = useSelector((state: ReduxState) => state.branding);

  return (
    <>
      <GlobalStyle />
      <Wrapper flex variant="grey">
        <Box bg="white" height="440px" flex boxShadow="login" width={[1, 2 / 3, 'auto']}>
          <Box
            bg="primary100"
            color="white"
            p="x3"
            width="380px"
            flexGrow={0}
            display={['none', 'none', 'block']}
            position="relative"
          >
            <H2 fontWeight="lighter">{translateLabel('loginWelcome')}</H2>
            <Text fontWeight="lighter" mt="default">
              {translateMessage('loginWelcome')}
            </Text>
            <Text textAlign="center" p="xxl">
              <Box display="inline" mr="default">
                <Illustration variant="Planet" width={82} height={91} />
              </Box>
              <Box display="inline">
                <Illustration variant="Astronaut" width={82} height={91} />
              </Box>
              <Box display="inline" position="relative" top="-20px">
                <Illustration variant="FlagInCog" width={82} height={91} />
              </Box>
            </Text>
          </Box>
          <Box as="form" action={action} method="POST" p="x3" flexGrow={1} width={['100%', '100%', '480px']}>
            <H5 marginBottom="xxl">
              {branding.logo ? <StyledLogo src={branding.logo} alt={branding.companyName} /> : branding.companyName}
            </H5>
            {message && (
              <MessageBox
                my="lg"
                message={message.split(' ').length > 1 ? message : translateMessage(message)}
                variant="danger"
              />
            )}
            <FormGroup>
              <Label required>{translateProperty('email')}</Label>
              <Input name="email" placeholder={translateProperty('email')} />
            </FormGroup>
            <FormGroup>
              <Label required>{translateProperty('password')}</Label>
              <Input
                type="password"
                name="password"
                placeholder={translateProperty('password')}
                autoComplete="new-password"
              />
            </FormGroup>
            <Text mt="xl" textAlign="center">
              <Button variant="primary">{translateButton('login')}</Button>
            </Text>
            <Text mt="lg" textAlign="center">
              {translateMessage('forgotPasswordQuestion')}{' '}
              <a href="/forgot-password">{translateMessage('forgotPassword')}</a>
            </Text>
          </Box>
        </Box>
        {branding.withMadeWithLove ? (
          <Box mt="xxl">
            <MadeWithLove />
          </Box>
        ) : null}
      </Wrapper>
    </>
  );
};

// export default Login;

module.exports = Login
````

I imported the .tsx file like so:
````
const Login = require('../customAdminTemplates/Login.tsx')
admin.overrideLogin({ component: Login });

````

However, I get the following error:

````
type LoginProps = {
     ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at compileFunction (<anonymous>)
````

Please can someone explain what I am doing wrong or show an example of what I need to do?

### Bug prevalence

Whenever I start the server

### AdminJS dependencies version

//Node v-14.16.1
{
  "name": "project 1",
  "version": "1.0.0",
  "description": "A backend project",
  "author": "",
  "private": true,
  "scripts": {
    "start": "node src/index.js ts-node src/index.ts",
    "dev": "env-cmd ./config/dev.env nodemon src/index.js",
    "test": "env-cmd ./config/test.env jest --watch --runInBand"
  },
  "jest": {
    "testEnvironment": "node"
  },
  "dependencies": {
    "@adminjs/express": "^5.1.0",
    "@adminjs/mongoose": "^3.0.1",
    "@googlemaps/google-maps-services-js": "^3.3.16",
    "@sendgrid/mail": "^6.3.1",
    "adminjs": "^6.8.4",
    "apple-signin-auth": "^1.7.4",
    "authy-client": "^1.1.2",
    "aws-sdk": "^2.465.0",
    "axios": "^0.18.1",
    "base64-arraybuffer": "^0.2.0",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.19.0",
    "bootstrap": "^4.3.1",
    "compression": "^1.7.4",
    "connect-history-api-fallback": "^2.0.0",
    "cookie-parser": "^1.4.5",
    "cors": "^2.8.5",
    "countrycitystatejson": "^0.2.12",
    "cron": "^1.7.1",
    "crypto": "^1.0.1",
    "express": "^4.18.2",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",
    "googleapis": "^107.0.0",
    "handlebars": "^4.1.1",
    "hbs": "^4.0.4",
    "helmet": "^3.21.1",
    "i18n": "^0.8.5",
    "image-thumbnail": "^1.0.15",
    "jsonwebtoken": "^8.5.1",
    "libphonenumber-js": "^1.10.15",
    "moment": "^2.24.0",
    "mongodb": "^3.2.7",
    "mongodb-stitch-browser-sdk": "^4.3.2",
    "mongoose": "^6.8.3",
    "morgan": "^1.9.1",
    "multer": "^1.4.1",
    "multer-s3": "^2.9.0",
    "otplib": "^12.0.1",
    "passport": "^0.6.0",
    "passport-google-oauth": "^2.0.0",
    "path": "^0.12.7",
    "socket.io": "^4.5.4",
    "socketio-auth": "^0.1.1",
    "stripe": "^7.9.1",
    "tslib": "^2.5.0",
    "twilio": "^3.32.0",
    "validator": "^10.9.0",
    "vhost": "^3.0.2"
  },
  "devDependencies": {
    "@types/node": "^18.13.0",
    "chalk": "^2.0.1",
    "env-cmd": "^8.0.2",
    "jest": "^24.8.0",
    "nodemon": "^1.18.11",
    "supertest": "^4.0.2",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5"
  }
}

**Comment by eakenbor** [comment]
@dziraf that was actually the beginning of the problem which made me convert them to using the "require" syntax. I used import/export syntax in the .tsx file and I got the following error:

````
import React from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)````

**Comment by dziraf** [comment]
You should be able to import it into any typescript file but if you're using plain CommonJS you might need an additional library ie https://www.npmjs.com/package/require-jsx

**Comment by eakenbor** [comment]
@dziraf that library does not work and it has not been updated for 10 years. Please can you run your .tsx example using my environment to see what happens? It seems the problem is similar to my last issue that led to you releasing the latest version of adminjs.

**Comment by eakenbor** [comment]
@dziraf please any luck?
