### ISSUE TITLE
[Feature]: @adminjs/sql does not have options to configure PSQL schema name

### ISSUE THREAD

**Issue by dev-jiwonchoi** [SoftwareBrothers/adminjs#1478]
### Description

As written in https://docs.adminjs.co/installation/adapters/sql, the official doc introduces that the Adapter instance options are based on knex options but it seems like it is not able to set an option for the custom PSQL schema name other than 'public'.

example code:
```typescript
const db = await new Adapter('postgresql', {
  connectionString: '<your database url>',
  database: '<your database name>',
}).init()
``` 

### Suggested Solution

Add a schema name option for Adapter > ConnectionOptions > PostgresConnectionConfig which is currently as below:
```typescript
export interface PostgresConnectionConfig {
    user?: string;
    database?: string;
    password?: string | (() => string | Promise<string>);
    port?: number;
    host?: string;
    connectionString?: string;
    keepAlive?: boolean;
    stream?: stream.Duplex;
    statement_timeout?: false | number;
    parseInputDatesAsUTC?: boolean;
    ssl?: boolean | ConnectionOptions;
    query_timeout?: number;
    keepAliveInitialDelayMillis?: number;
    idle_in_transaction_session_timeout?: number;
    application_name?: string;
    connectionTimeoutMillis?: number;
    types?: PgCustomTypesConfig;
    options?: string;
}
``` 
and modify raw query to receive the schema option data.

**Comment by matex1024** [comment]
Hi, @dev-jiwonchoi you are right we should add the schema option but you are wrong about the place. I've made a change here (https://github.com/SoftwareBrothers/adminjs-sql/pull/4/files). Please next time add an issue to @adminjs/sql as you should.

**Comment by dev-jiwonchoi** [comment]
> Hi, @dev-jiwonchoi you are right we should add the schema option but you are wrong about the place. I've made a change here (https://github.com/SoftwareBrothers/adminjs-sql/pull/4/files). Please next time add an issue to @adminjs/sql as you should.

Apologize for the confusion. Thank you for guiding.
