### ISSUE TITLE
where to get the file component-loader.js

### ISSUE THREAD

**Issue by weilitao** [SoftwareBrothers/adminjs#1481]
### What happened?

Hello, I try to do the migration of my project to v7. When I deal with the features part, the docs say:

import componentLoader from './component-loader.js';

So where is "component-loader.js"? would you please show me the file content? Since I use javascript so I can't get hint from the example project.

Thanks.

### Bug prevalence

question

### AdminJS dependencies version

v7

**Comment by dziraf** [comment]
https://docs.adminjs.co/ui-customization/writing-your-own-components

**Comment by weilitao** [comment]
it works. Thanks
