### ISSUE TITLE
[Bug]: How to report a security issue ?

### ISSUE THREAD

**Issue by Techbrunch** [SoftwareBrothers/adminjs#1507]
### What happened?

I would like to report a security issue. I tried sending an email directly to kris@adminjs.co <kris@adminjs.co> but did not get any reply. What is the best way to do this ?

**Comment by Techbrunch** [comment]
I don't recommend anyone taking security seriously to use this project in the meantime.

See: 

- #1447
- #1509

**Comment by dziraf** [comment]
This should be resolved now since GET requests don't trigger mutating behaviours anymore.
