### ISSUE TITLE
[Bug/Feature]: isAccessible Promise<boolean>

### ISSUE THREAD

**Issue by ashcowey** [SoftwareBrothers/adminjs#1519]
### What happened?

Custom resource action handler needs to verify claims from Firebase token which requires async. 

Added types Promise<boolean> Promise<IsFunction> in action.interface.d.ts but isAccessible doesn't seem to care if it's true or false.

Is there a way to make isAccessible, and I suppose isVisible, wait for response?

I haven't really investigated too much ... hoping someone has an answer.

### Bug prevalence

Custom Resource Action

### AdminJS dependencies version

    "adminjs": "^6.8.7",    
    "@adminjs/custom-components": "^2.0.0",
    "@adminjs/design-system": "^3.1.8",
    "@adminjs/express": "^5.0.1",
    "@adminjs/logger": "^4.0.1",
    "@adminjs/typeorm": "^4.0.0",
    "@adminjs/upload": "^3.0.1",

### What browsers do you see the problem on?

Chrome

### Relevant log output

```bash
Log output for user with claims.admin true is true and false for undefined.
```

### Relevant code that's giving you issues

```TypeScript
// Resource Action 

isAccessible: async ({ currentAdmin }) =>  { return await isAdminUser(currentAdmin) }

// isAdminUser
async function isAdminUser(currentAdmin){
  let admin: boolean = false;
  const claims = await getAuth().verifyIdToken(currentAdmin.token)
  if ( claims.admin && claims.admin === true ) {
    admin = true
  }
  return admin
}
```

**Comment by ashcowey** [comment]
Can be performed in handler.

**Comment by carmof** [comment]
I'm a bit late but do you know where I can find an example of how to perform it in handler? I still don't get it.
@ashcowey

**Comment by dziraf** [comment]
@carmof 

You can just perform any async actions in a `before` hook and assign results to `context`. Context is shared between hooks, so `isAccessible` can directly access data without having to be async.

**Comment by carmof** [comment]
@dziraf Thanks for the reply (=

Now I understand the way but I'm having a problem at finding where the variable is in "context":

![image](https://github.com/SoftwareBrothers/adminjs/assets/10501569/40fdc937-c081-40ab-8e0c-f3a9868ff509)

Do you know where it is? I've been looking for it for a while.

**Comment by dziraf** [comment]
Do it more like:

```ts
const doSomethingAsync = (req, ctx) => {
  const someAsyncData = await getData();
  
  ctx.someAsyncData = someAsyncData; // you can assign anything
  
   return req;
}

// ...

actions: {
  edit: {
    before: [doSomethingAsync],
    isAccessible: (context) => {
      const { someAsyncData, currentAdmin } = context; // access your data from before hook
      
      return someAsyncData.permittedRole === currentAdmin.role;
    }
  }
}
```

**Comment by carmof** [comment]
@dziraf Got it!!!! Thank you so much 💯

**Comment by carmof** [comment]
@ashcowey 

![image](https://github.com/SoftwareBrothers/adminjs/assets/10501569/1e7ac367-405f-4cda-b9ff-476665cefb31)

I tryed and it's not working for me.

```
"@adminjs/express": "^6.1.0",
"@adminjs/relations": "^1.1.2",
"@adminjs/typeorm": "^5.0.0",
"adminjs": "^7.7.2",
```
