### ISSUE TITLE
[Bug]: Cannot import AdminJSTypeOrm and AdminJS in app.module nestjs

### ISSUE THREAD

**Issue by shellking4** [SoftwareBrothers/adminjs#1524]
### What happened?

List what you are trying to do?

### Bug prevalence

The imports are giving errors in the editor and code wont run

### AdminJS dependencies version

7.0.9

### What browsers do you see the problem on?

Chrome

### Relevant code that's giving you issues

```TypeScript
import * as AdminJSTypeorm from '@adminjs/typeorm'
import AdminJS from 'adminjs'
```

**Comment by dziraf** [comment]
To run Nest.js app with ESM syntax make sure to set `module` to `NodeNext` in your `tsconfig.json`. Also make sure there is no `moduleResolution` option at all (remove it from tsconfig if it exists - this breaks ESM compatibility).
