### ISSUE TITLE
Impove the bundling of Adminjs and make it user friendly

### ISSUE THREAD

**Issue by shellking4** [SoftwareBrothers/adminjs#1528]
Adminjs is a great project. It makes me feel like there is another way than adding directus or strapi in order to achieve content management. But to be fair with you guys, this library is a pain to work with. A big pain because of the bundling kata and all stuffs. Cannot even import adminjs like (import AdminJS from 'adminjs') without getting an error and yet the docs states that we can do it that way. I think you could do better.

**Comment by dziraf** [comment]
The docs also state that the library supports only ESM projects. Importing `adminjs` in a CJS project will result in an error.

**Comment by shellking4** [comment]
Thanks for your reply. would be great to have some support for using the library in CJS though
