### ISSUE TITLE
[Bug]: Custom Dashboard Not Found

### ISSUE THREAD

**Issue by HThanh-how** [SoftwareBrothers/adminjs#1531]
### What happened?

[Custom Dashboard Components ](https://docs.adminjs.co/tutorial-custom-dashboard.html) in first page AdminJS was not found
I believe a correct link is [here](https://docs.adminjs.co/ui-customization/dashboard-customization) 
![image](https://github.com/SoftwareBrothers/adminjs/assets/114163977/6c36ee8b-d28e-4a20-8661-3e022e0e1120)
![image](https://github.com/SoftwareBrothers/adminjs/assets/114163977/c1d43c49-d8c6-4b54-8425-338b9e3ca09b)

### Bug prevalence

First time

### AdminJS dependencies version

{
  "type": "module",
  "dependencies": {
    "@adminjs/express": "^6.0.0",
    "@adminjs/mongoose": "^4.0.0",
    "adminjs": "^7.0.9",
    "connect-pg-simple": "^9.0.0",
    "express": "^4.18.2",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",
    "tslib": "^2.6.0"
  }
}

### What browsers do you see the problem on?

Chrome

**Comment by dziraf** [comment]
The default dashboard's been updated
