### ISSUE TITLE
[Bug]: StoryBook "No Code Available"

### ISSUE THREAD

**Issue by abbasharoon** [SoftwareBrothers/adminjs#1534]
### What happened?

The StoryBook for Design System documentation lacks written documentation, and the code button isn't working for any of the components. Is there anywhere else where we should look for the docs? 
![image](https://github.com/SoftwareBrothers/adminjs/assets/6374851/f3680639-e508-4f3c-be34-5cbce284c672)

### Bug prevalence

All of the components on StoryBook

### AdminJS dependencies version

Latest Version

### What browsers do you see the problem on?

Firefox, Chrome

**Comment by fedot199614** [comment]
up

**Comment by fedot199614** [comment]
any updates?

**Comment by dziraf** [comment]
@fedot199614 @abbasharoon 
Code examples should now work: https://storybook.adminjs.co/?path=/docs/designsystem-atoms-avatar--docs
