### ISSUE TITLE
[Bug]: Styling/Color Issue on Confirmation Modals in Dark Theme (Guard Component)

### ISSUE THREAD

**Issue by Ellenek** [SoftwareBrothers/adminjs#1540]
#### Expected Behavior:
When using the Dark theme in AdminJS, the colors of the Confirmation Modals should match the theme. The text should be easily readable and aligned with the theme's aesthetic.

#### Actual Behavior:
The Confirmation Modal appears completely white when the Dark theme is used. This results in unreadable text and misaligned aesthetics.

#### Steps to reproduce:
1. Switch to the Dark theme in AdminJS.
2. Press the Delete button or create a custom action with a guard option.
3. The Confirmation Modal that appears is completely white, regardless of the Dark theme setting.

#### Screenshots or Log Errors:

https://github.com/SoftwareBrothers/adminjs/assets/26671103/7f282818-2907-4435-9d51-a5043bb3f72d

<img width="996" alt="image" src="https://github.com/SoftwareBrothers/adminjs/assets/26671103/f97bfd80-0423-44d5-8810-0911a269e3eb">

<img width="1081" alt="image" src="https://github.com/SoftwareBrothers/adminjs/assets/26671103/e34cfaf0-d43f-417a-bfc3-b3197bfa0171">

### Environment:
- Version of the software/project: "@adminjs/design-system": "^4.0.2", "@adminjs/express": "^6.0.0", "@adminjs/sequelize": "^4.0.0", "@adminjs/themes": "^1.0.0", "adminjs": "^7.0.1"
- Operating System: MacOS 13.2.1

### Additional context
The expected behavior is based on the assumption that all UI components should adjust their colors according to the currently set theme. In this case, the Confirmation Modal is not updating its colors when the Dark theme is activated, leading to usability and aesthetic issues.

### Bug prevalence

Whenever I try to use custom component with a guard option or delete a record.

### AdminJS dependencies version

- Version of the software/project: "@adminjs/design-system": "^4.0.2", "@adminjs/express": "^6.0.0", "@adminjs/sequelize": "^4.0.0", "@adminjs/themes": "^1.0.0", "adminjs": "^7.0.1"

**Comment by jedlikowski** [comment]
@Ellenek I'm experiencing the same issue. Mitigated it like this in custom css:

```css
.adminjs_Overlay + .adminjs_Box {
    background-color: #1a1a1e;
}
```

**Comment by Ellenek** [comment]
@jedlikowski works like a charm, many thanks!

**Comment by dziraf** [comment]
This should be fixed via https://github.com/SoftwareBrothers/adminjs-design-system/releases/tag/v4.0.3

The theme should fix itself after you reinstall node modules but you may have to add the following lines to your `package.json` until the version is updated in main library:

```json
 "resolutions": {
     "@adminjs/design-system": "4.0.3"
 }
```
