### ISSUE TITLE
There was an error fetching records. Check out console to see more information

### ISSUE THREAD

**Issue by eakenbor** [SoftwareBrothers/adminjs#1550]
### What happened?

I get this error whenever I try to load the list of documents: "There was an error fetching records. Check out console to see more information". However, I do not know where I can catch and read off the detailed error message to know what exactly went wrong. Please how can I do that?
![Company (5)](https://github.com/SoftwareBrothers/adminjs/assets/30095266/ff58cbe1-81c5-4222-a117-18453172c4c3)

### Bug prevalence

Every time

### AdminJS dependencies version

"adminjs": "^7.0.5",

**Comment by TousifProvat** [comment]
You can read the details in your IDE terminal.

If you're using ExpressJs and MongoDB as your database. I may be able to help.
