### ISSUE TITLE
[Bug]: I can not view link of logger record

### ISSUE THREAD

**Issue by nguyenvanvy1999** [SoftwareBrothers/adminjs#1553]
### What happened?

I want to view records what was recored by adminjs/logger
But it can not link with id to another record.
And it throw an error like image below
I was check information of logger record: Record and record id correct
![image](https://github.com/SoftwareBrothers/adminjs/assets/61955009/30c5da12-fec9-4c30-b779-488ce2989999)

![image](https://github.com/SoftwareBrothers/adminjs/assets/61955009/68a0be0e-8daa-4e2e-8349-739fdb7ba345)

### Bug prevalence

Yes

### AdminJS dependencies version

    "@adminjs/express": "^6.0.0",
    "@adminjs/import-export": "^3.0.0",
    "@adminjs/logger": "^5.0.1",
    "@adminjs/mongoose": "^4.0.0",
    "adminjs": "^7.2.1"

### Relevant log output

```bash
Error: Component "RecordLink" has not been bundled, ensure it was added to your ComponentLoader instance (the one included in AdminJS options).
See development console for more details...
```

### Relevant code that's giving you issues

```TypeScript
resources: [
        {
          resource: this.userModel,
          features: [
            importExportFeature({ componentLoader }),
            loggerFeature({ componentLoader }),
          ],
          options: userOptions(this.userModel),
        },
        {
          resource: this.roleModel,
          features: [
            importExportFeature({ componentLoader }),
            loggerFeature({ componentLoader }),
          ],
          options: roleOptions(this.roleModel),
        },
        {
          resource: this.adminjsLoggerModel,
          features: [importExportFeature({ componentLoader })],
          options: adminjsLoggerOptions,
        },
        createLoggerResource({
          resource: this.adminjsLoggerModel,
          componentLoader,
          featureOptions: {
            componentLoader,
            userIdAttribute: 'userId',
            propertiesMapping: {
              user: 'userId',
              resource: 'resource',
              action: 'action',
              recordId: 'recordId',
              recordTitle: 'recordTitle',
            },
            resourceOptions: {
              navigation: {
                name: 'SectionName',
                icon: 'iconName',
              },
            },
          } as any,
        }),
      ],
```

With componentLoader is:

```ts
    const componentLoader = new ComponentLoader();
```

**Comment by taichi-asari-sti** [comment]
I am facing the same issue as you. Have you resolved this problem? If so, could you please share the solution?

**Comment by nguyenvanvy1999** [comment]
> I am facing the same issue as you. Have you resolved this problem? If so, could you please share the solution?

Hello. This bug happen because you missing passing component loader when you config adminjs. this is solution:

`ts
    const componentLoader = new ComponentLoader();
    const admin = new AdminJS({
      componentLoader, // Pass it here. Then it will work correctly
.....
}
`
