### ISSUE TITLE
Weebpack configuration

### ISSUE THREAD

**Issue by golu7679** [SoftwareBrothers/adminjs#1557]
I am using typescript in my expressjs project and I am adminjs too, so can I build my expressjs project with webpack, is it possible or not?

**Comment by dziraf** [comment]
If you mean the frontend, then no. AdminJS uses it's own Rollup configuration for bundling custom components which you'd have to replicate in Webpack to produce the same type of files.

**Comment by golu7679** [comment]
Okay, Thank you
