### ISSUE TITLE
[Bug]: Wrong Path Generated in .adminjs/.entry.js file

### ISSUE THREAD

**Issue by Kunkka0822** [SoftwareBrothers/adminjs#1558]
### What happened?

![image](https://github.com/SoftwareBrothers/adminjs/assets/101172481/2f7f73a2-e9f8-4679-b6b9-686a1d6489a9)

Wrong Path for Login Component is generated.

How could I fix this issue?

### Bug prevalence

Everytime I run the code.

### AdminJS dependencies version

"adminjs": "^7.2.1",

### What browsers do you see the problem on?

Chrome

**Comment by dziraf** [comment]
Can you share how you add your Login component to ComponentLoader?
