### ISSUE TITLE
[Bug]: Filtering does not work if you are not on the first page

### ISSUE THREAD

**Issue by CodeXiD** [SoftwareBrothers/adminjs#1581]
### What happened?

Hi! Thanks for the great package, it makes our life incredibly easy, but we have a bug, if I am on the first page of the table and start filtering by ID (or any other field) everything works fine, but if I first go to the second page of the table and make a filtering in which the result will be for example 1 record, we do not automatically go to the first page and adminjs will say that there are no records, although in fact there is a record. I think when filtering should automatically send the user to the first page of the table.List what you are trying to do?

### Bug prevalence

I think customers often encounter this bug and don't understand why there are no results, so I think it's a common mistake

### AdminJS dependencies version

"@adminjs/design-system": "^4.0.3",
"@adminjs/express": "^6.0.1",
"@adminjs/import-export": "^3.0.0",
"@adminjs/nestjs": "^6.0.1",
"@adminjs/relations": "^1.0.0",
"@adminjs/typeorm": "^5.0.0",
"adminjs": "^7.3.0",

### What browsers do you see the problem on?

Chrome

**Comment by dziraf** [comment]
@CodeXiD this should be fixed in 7.4.1
