### ISSUE TITLE
[Bug]: Cannot get custom css to work 

### ISSUE THREAD

**Issue by scottrules44** [SoftwareBrothers/adminjs#1585]
### Contact Details

Just on here

### What happened?

List what you are trying to do?

I'm trying to change the color of my sidebar but the custom css is not applying.
Also trying to use tailwind (did try removing tailwind piece but does not work still)

Note custom logo is working fine and see the style sheet in my sources but it's just not applying

### Bug prevalence

Ever time I try to use it

### AdminJS dependencies version

AdminJS 7.4.2
@adminjs/express 6.1.0

![Screenshot 2023-12-01 at 2 54 46 PM](https://github.com/SoftwareBrothers/adminjs/assets/7820808/77f815fe-d59f-44fe-a548-437d7955e103)

### What browsers do you see the problem on?

Chrome, Safari

### Relevant code that's giving you issues

```TypeScript
adminJsOptions: {
        dashboard: {
          handler: async () => {

          },
          component: Components.Dashboard
        },
        branding: {
          companyName: 'Coflyt Admin',
          logo: "/logo.png",          
        },
        assets: {
          styles: ["/custom-adminjs.css"],
        },
}


custom-admin.css>

@tailwind base;
@tailwind components;
@tailwind utilities; 


:root {
    --topbar-color: blue;
    --sidebar-bg-color: darkgray;
    --sidebar-color: blue;
    --sidebar-link-color: orange;
  }
  ​
  section[data-css="sidebar"] {
    background-color: var(--sidebar-bg-color) !important;
    color: var(--sidebar-color);
    border: none;
  }
  ​
  section[data-css="sidebar"] svg {
    fill: var(--sidebar-color) !important;
  }
  ​
  a[data-css="sidebar-logo"] {
    background-color: var(--sidebar-bg-color) !important;
  }
  ​
  section[data-css="sidebar-resources"] {
    background: var(--sidebar-bg-color) !important;
  }
  ​
  [data-css="sidebar"] section a {
    background: var(--sidebar-bg-color) !important;
    color: var(--sidebar-color);
  }
  ​
  [data-css="sidebar"] a:hover {
    color: var(--sidebar-link-color);
  }
```

**Comment by dziraf** [comment]
@scottrules44 

Yes, it's currently at the latest version. You can see an example of modified CSS here: https://cloud.adminjs.co/app

The CSS file is public:
https://cloud.adminjs.co/css/overrides.css
