### ISSUE TITLE
[Bug]: Cant get custom dashboard to display

### ISSUE THREAD

**Issue by mattrochon** [SoftwareBrothers/adminjs#1586]
### What happened?

Followed the documentation to setup a custom dashboard:

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/27f66c91-4710-4d77-b0d6-64af3895573e)

MainDashboard.tsx

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/3f7d0ecd-d409-4d61-b856-badff0099bdb)

ComponentConfig.ts

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/80c844bd-6de3-4387-a6e2-a66674f8fd0f)

Application.ts

Log output:

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/c27b280f-6ccf-4bcd-829d-1ebebea8eace)

It all seems to be setup correctly but all i see if the default dashboard.

### Bug prevalence

Always

### AdminJS dependencies version

"dependencies": {
    "@adminjs/express": "^6.1.0",
    "@adminjs/prisma": "^5.0.1",
    "@adminjs/themes": "^1.0.1",
    "@types/express": "^4.17.21",
    "adminjs": "^7.4.2",
    "express": "^4.18.2",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",
    "nodemon": "^3.0.2",
    "prisma": "^5.6.0",
    "tslib": "^2.6.2"
  },
  "devDependencies": {
    "tsx": "^4.6.2"
  },

### Relevant log output

```bash
ComponentLoader {
  components: {
    Dashboard: {
      overrides: false,
      filePath: 'g:\\workspace\\REDACTED\\view\\MainDashboard''
    }
  }
}
{ Dashboard: 'Dashboard' }
```

### Relevant code that's giving you issues

```TypeScript
const adminOptions: AdminJSOptions = {
            componentLoader,
            resources: ResourceConfig.buildResourceList(prisma),
            rootPath: "/app",
            defaultTheme: dark.id,
            availableThemes: [dark, light, noSidebar],
            locale: ResourceConfig.buildNavList(),
            dashboard: {
                component: Components.Dashboard,
            },
        }

        const admin = new AdminJS(adminOptions);
```

**Comment by dziraf** [comment]
1. Can you check if `components.bundle.js` appears in your browser's Network tab and if there're any contents?
2. Can you check if the file actually exists at:`'g:\\workspace\\REDACTED\\view\\MainDashboard''` (to make sure the resolved path is correct)? You can try to use `path.join` to provide an absolute path in case it works incorrectly with relative path.

**Comment by mattrochon** [comment]
1. It exists and is loaded, but appears empty
![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/b3bbd2dd-5b50-4e2e-9bce-8cc0a7721663)
2. The file definitely exists and its resolved by the path resolver
![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/db2ddb22-2ff1-4a4a-9667-a13da3587f48)

**Comment by mattrochon** [comment]
Solved it! Thanks so much
