### ISSUE TITLE
[Bug]: Trouble adding custom component for property

### ISSUE THREAD

**Issue by mattrochon** [SoftwareBrothers/adminjs#1590]
### What happened?

On my user resource, I added an ephemeral field for password, as authentication is handled by a 3rd party.

It largely worked with no configuration, except that the browser things that because I have 'email' and 'password' int he form it should auto populate with my credentials.

I tried passing autocomplete="new-password" tot he props section of the property definition, but that attribute is not passed on to the react component.

From what I can tell, only these properties are passed on:

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/919f6690-fcb9-4968-bb34-1229d36b60d8)

In another place, I found a component that seems like it should be passing on the property, but inspecting the element never showed the prop in question.

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/0a5ad60e-4729-4c9c-9324-7d0132127712)

So, moving on, I *followed* the documentation at https://docs.adminjs.co/ui-customization/writing-your-own-components. I have *followed* highlighted because i must have missed something.

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/b91e4d45-d520-49f0-8ab6-8663136d91a9)

in the documentation I found this section:

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/beceecf6-3b12-4e11-9aa3-fd48cd869f4b)

and in the link for useRecord(), there is a readme file, which i followed:

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/9fab53e4-21b8-499a-a3c2-f9dffd9142a1)

Here is my component:

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/8de6f692-28a2-44ec-b13d-62fa0f9c0dd5)

I had to change the imports as they threw errors with the ones in the readme.

The issue I am having, is showing this component seems to cause an infinite loop of re-rendering.

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/d3cddb47-c6ff-4b76-9a9e-decd8548a8fe)

And obv this locks up the browser and explodes everything.

### Bug prevalence

Always

### AdminJS dependencies version

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/74536b15-0fe2-4f43-a5e6-6412d93d7f33)

**Comment by dziraf** [comment]
> The issue I am having, is showing this component seems to cause an infinite loop of re-rendering.

Try importing `CleanPropertyComponent` from `adminjs` instead of `BasePropertyComponent`. `CleanPropertyComponent` strips your custom component part from `property` to prevent the infinite loop.

https://github.com/SoftwareBrothers/adminjs/blob/master/src/frontend/components/property-type/clean-property-component.tsx

**Comment by mattrochon** [comment]
I see that this wont work either.

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/caefaed8-77a9-4edf-8dfe-eeb237281938)

BaseProperty doesnt pass the props into the component.

**Comment by dziraf** [comment]
Is that from core or is that your custom component? The props from config should be in `property` as `property.props`.

**Comment by mattrochon** [comment]
autoComplete seems to have worked
