### ISSUE TITLE
[Bug]: Issue with AdminJSOptions.env when pre-bundling for deployment

### ISSUE THREAD

**Issue by mattrochon** [SoftwareBrothers/adminjs#1593]
### What happened?

When I bundle for deployment I host all my static/public assets on a CDN. Not just the js files adminJS uses, but also images, css, config etc.

To that end, in my code I dynamically build the urls based on an environment variable CDN_PATH, which is really only available on the server, as its part of the build automation to create that.

On the UI side, I tried passing this down to the components using AdminJSOptions.env:

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/08297a27-964b-4116-b558-386e40e629e2)

but it doesnt seem this this is passed on when rendering the app using bundled files:

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/99ea1b35-216a-444f-8453-d0493176c3bd)

Almost everything works, except when I'm using a component that requires a url source, like an `<img>` tag, for example.

Since the node app is the one initiating the app rendering, even if it ultimately uses components fromt he CDN, couldnt it still pass the adminjs env info tot he frontend for use by the react app?

### Bug prevalence

Always

### AdminJS dependencies version

"dependencies": {
    "@adminjs/bundler": "^3.0.0",
    "@adminjs/express": "^6.1.0",
    "@adminjs/prisma": "^5.0.1",
    "@adminjs/themes": "^1.0.1",
    "@adminjs/upload": "^4.0.1",
    "@aws-sdk/client-api-gateway": "^3.465.0",
    "@aws-sdk/client-cognito-identity-provider": "^3.468.0",
    "@fortawesome/fontawesome-free": "^6.5.1",
    "@types/express": "^4.17.21",
    "adminjs": "^7.4.2",
    "amazon-cognito-identity-js": "^6.3.7",
    "cors": "^2.8.5",
    "express": "^4.18.2",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",
    "memorystore": "^1.6.7",
    "prisma": "^5.6.0",
    "tslib": "^2.6.2"
  },
  "devDependencies": {
    "@types/cors": "^2.8.17",
    "@types/express-session": "^1.17.10",
    "tsx": "^4.6.2",
    "nodemon": "^3.0.2"
  },

### Relevant log output

```bash
n/a
```

**Comment by dziraf** [comment]
It seems to be an issue with `@adminjs/bundler`. I will probably have to update it so that it requires `AdminJSOptions`.

You should be able to add missing envs by creating a custom script.

```typescript
import fs from 'fs/promises'

const setEnvs = async (admin: AdminJS) => {
  const { env = {} } = admin.options

  const script = Object.keys(env).map((envKey) => (
    `AdminJS.env.${envKey} = ${JSON.stringify(env[envKey])}\n`
  )).join('')

  await fs.writeFile('<destination path>', script, 'utf8');
}
```

You can run it in the same file where you use `@adminjs/bundler`. If you don't want to create an `AdminJS` instance for the script, it's enough if you pass only `AdminJSOptions` object or envs object.

Afterwards, add the generated script to AdminJS assets:

```typescript
const admin = new AdminJS({
  // ...
  assets: {
    scripts: process.env.NODE_ENV === 'production' ?  ['/envs.js'] : [],
  }
})
```

**Comment by mattrochon** [comment]
This doesnt quite work as expected, though it might just be a timing issue.

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/955eb4f6-0bab-409d-b500-6e9acf392a1a)

And we can see it getting downloaded here:

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/31f2f75b-f28d-4099-8c12-84ccf39c733c)

And heres some code that uses those values on the FE:

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/093adbd0-ee67-4b33-be5b-078af01a3fd5)

But theres still no/undefined values for those envs:

![image](https://github.com/SoftwareBrothers/adminjs/assets/1702787/d3dc3475-a70b-4a03-bfef-630970695b0d)

I assume this is some sort of timing issue, where that script executes, but then AdminJS.env is likely overridden by a default {}

**Comment by Dauniusha** [comment]
Just copy env string is working too:
`    env: {
      IMAGES_PATH: `${process.env.IMAGES_PATH}`,
    }`
