### ISSUE TITLE
[Bug]: Some spanish words aren't properly translated

### ISSUE THREAD

**Issue by RGkevin** [SoftwareBrothers/adminjs#1603]
### Contact Details

https://github.com/SoftwareBrothers/adminjs/pull/1602

### What happened?

Fix a couple of wrong translated words. I created a PR
https://github.com/SoftwareBrothers/adminjs/pull/1602

### Bug prevalence

Always

### AdminJS dependencies version

N/A

### What browsers do you see the problem on?

Chrome

**Comment by dziraf** [comment]
Hi I merged your PR
