### ISSUE TITLE
How to migrate from adminbro to adminjs

### ISSUE THREAD

**Issue by lumayara** [SoftwareBrothers/adminjs#1608]
Hi all,
I was wondering if there are instructions available on how to migrate to adminjs from adminbro?

Thank you!

**Comment by becelli** [comment]
Looking forward to it.

**Comment by dziraf** [comment]
`admin-bro` to `adminjs` migration is simply rewriting all occurrences of `admin-bro` to `adminjs` and `AdminBro` to `AdminJS`. There were more changes later, but not directly related to brand name migration. Most breaking changes are in v7:
https://docs.adminjs.co/installation/migration-guide-v7
