### ISSUE TITLE
[Bug]: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `Edit`.

### ISSUE THREAD

**Issue by Vo0oX** [SoftwareBrothers/adminjs#1615]
### What happened?

List what you are trying to do?Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `Edit`.

<img width="1128" alt="Снимок экрана 2024-01-27 в 18 57 59" src="https://github.com/SoftwareBrothers/adminjs/assets/20887300/d78e0755-79c4-42ca-83be-e99d48cfdf4e">

### Bug prevalence

.

### AdminJS dependencies version

.

### Relevant log output

```bash
.
```

### Relevant code that's giving you issues

```TypeScript
.
```

**Comment by dziraf** [comment]
Please fill in the form, this issue is missing relevant information
