### ISSUE TITLE
[Bug]: Filter UI issue

### ISSUE THREAD

**Issue by NITHISH-1609** [SoftwareBrothers/adminjs#1617]
### What happened?

I have a custom component for creating or updating a record. Upon saving, the filter component moves down, as shown in the screenshot. This issue has only occurred with this specific custom component

<img width="954" alt="Screenshot 2024-02-05 at 2 37 28 PM" src="https://github.com/SoftwareBrothers/adminjs/assets/61798905/fd81fe8d-2185-4baa-b128-7a39219f860c">
<img width="577" alt="Screenshot 2024-02-05 at 2 38 29 PM" src="https://github.com/SoftwareBrothers/adminjs/assets/61798905/0e0f3f55-813b-42f6-8893-929f220085cf">

### Bug prevalence

Every-time when we save through custom component

### AdminJS dependencies version

    "@adminjs/express": "6.0.0",
    "@adminjs/typeorm": "5.0.0",
    "adminjs": "7.5.9"

### What browsers do you see the problem on?

Chrome

**Comment by dziraf** [comment]
Are you 100% sure you're on version 7.5.9? 7.5.8 should've fixed this bug.

Alternatively, could you try:

```ts
const redirectUrl = h.resourceUrl({
  resourceId: 'Workflow'
})
```

and see if it also appears?
