### ISSUE TITLE
[Bug]: AdminPages type is different from the example provided

### ISSUE THREAD

**Issue by ESnark** [SoftwareBrothers/adminjs#1686]
### What happened?

```
@example

pages: {
  customPage: {
    label: "Custom page",
    handler: async (request, response, context) => {
      return {
        text: 'I am fetched from the backend',
      }
    },
    component: 'CustomPage',
  },
  anotherPage: {
    label: "TypeScript page",
    component: 'TestComponent',
  },
},
```
According to the example, It's possible to label pages, but label property is not included in AdminPages type.

Is this an unintended typing error, or is the example not updated?

### Bug prevalence

-

### AdminJS dependencies version

- adminjs@7.8.7
- @adminjs/express@6.1.0

**Comment by dziraf** [comment]
The example seems to be outdated although I don't think `label` has ever been usable 🤔 

To label/translate pages you should use `pages` in `locale`:

```ts
{
  language: 'en',
  debug: false,
  availableLanguages: ['en'],
  translations: {
    pl: {
      pages: {
        customPage: 'My custom page'
      }
    }
  }
}
```

**Comment by ESnark** [comment]
Thank you for clarifying this. It will be helpful for future contributions.
