### ISSUE TITLE
[Feature]: Add select as base PropertyType interface

### ISSUE THREAD

**Issue by CharlesParmentier** [SoftwareBrothers/adminjs#1687]
### Description

When I have a field in my database that is represented by a boolean (like this) 
<img width="250" alt="Capture d’écran 2024-07-23 à 09 41 45" src="https://github.com/user-attachments/assets/66c75147-8f9e-4bc8-a724-19feae5bea23">

If I want to be able to display a select dropdown input with two values instead of radio button, just having the availableProperties set is not enough

<img width="189" alt="Capture d’écran 2024-07-23 à 09 43 30" src="https://github.com/user-attachments/assets/d95563f9-77c6-4ff1-a0b6-4ca1771d8515">

This still result in a radio button: 

![Capture d’écran 2024-07-23 à 09 45 23](https://github.com/user-attachments/assets/fc05293d-874d-406c-8993-15b895c1726b)

If I add the type 'select' to my property, then it became a dropdown list because the type is forwarded to the input, however since the type 'select' is not part of the PropertyType interface, it results in a build error which needs a ts-ignore to avoid (not ideal) 

<img width="162" alt="Capture d’écran 2024-07-23 à 09 47 08" src="https://github.com/user-attachments/assets/174199d7-e0f2-4ab8-9087-1daa923576ea">

But with that it's working as expected: 

![Capture d’écran 2024-07-23 à 10 33 29](https://github.com/user-attachments/assets/59a165d9-b766-4eda-95df-b3d2ddb0c978)

### Suggested Solution

My proposed solution is to just add the type select in the PropertyType interface to avoid the build error. I already have a branch and a PR ready but since i'm not a contributor it looks like I can't push anything. 

### Additional Context

Not quite sure if it's a small feature or a small fix, but it's a good idea to allow a boolean to be displayed in dropdown list for some purpose.

**Comment by dziraf** [comment]
We usually just create custom components to represent values in a non-default way.

In your case changing the type to `string` and adding `props: { type: 'select' }` might be enough:

```ts
myField: {
  type: 'string',
  props: {
    type: 'select',
  },
  availableValues: [...]
}
```

**Comment by CharlesParmentier** [comment]
> We usually just create custom components to represent values in a non-default way.
> 
> In your case changing the type to `string` and adding `props: { type: 'select' }` might be enough:
> 
> ```ts
> myField: {
>   type: 'string',
>   props: {
>     type: 'select',
>   },
>   availableValues: [...]
> }
> ```

Yes I agree but creating a custom component here might be a bit overkill and it seems to be low impact to support natively the select property type, what do you think ?

**Comment by dziraf** [comment]
It is supported for `string` type and your `availableValues` are all `string` options so changing the `type` to `string` should be enough
