### ISSUE TITLE
[Feature]: Support (adapter) for ElysiaJS

### ISSUE THREAD

**Issue by dy0gu** [SoftwareBrothers/adminjs#1693]
### Description

An official adapter to support [ElysiaJS](https://elysiajs.com/) would be awesome!

### Suggested Solution

Ideally, an adapter solution would work much like the existing ones except compatible with ElysiaJS right out of the box.

### Alternatives

Tried using the [Elysia Connect Middleware](https://github.com/kravetsone/elysia-connect-middleware) plugin with [@adminjs/express](https://www.npmjs.com/package/@adminjs/express), but couldn't seem to make it work.

**Comment by AdamVerner** [comment]
Not an official one, but i have made my own adapter for Elysia, so maybe check it out https://github.com/AdamVerner/adminjs-elysia. It should be available on NPM as well.

I have started programming in typescript very recently, and havent used Elysia nor AdminJS very thorouly yet, so there might be some obvious bugs, feel free to open new issues if you came across any.

**Comment by dy0gu** [comment]
Awesome, thanks!

**Comment by kravetsone** [comment]
oh my elysia-express connect library mentioned :3
