### ISSUE TITLE
[Bug]: Error: Resource: "..." does not have an id property

### ISSUE THREAD

**Issue by Habubinator** [SoftwareBrothers/adminjs#1695]
### What happened?

I have an  Prisma model with  composite ID
```
model TasksUsers {
  user_id     String   @db.VarChar(64)
  user        Users    @relation(fields: [user_id], references: [id])
  task_id     Int      @db.Integer
  task        Tasks    @relation(fields: [task_id], references: [id])
  task_status String   @default("") @db.VarChar(255)
  assignedAt  DateTime @default(now())

  @@id([user_id, task_id])
}
```

When fetching with table from adminjs frontend i get
api-client.js:168 GET http://localhost:3000/admin/api/resources/TasksUsers/actions/list 500 (Internal Server Error)
With Error: Resource: "TasksUsers" does not have an id property on backend

```
Error: Resource: "TasksUsers" does not have an id property
    at BaseRecord.id (.../node_modules/adminjs/lib/backend/adapters/record/base-record.js:213:13)
    at BaseRecord.toJSON (.../node_modules/adminjs/lib/backend/adapters/record/base-record.js:289:16)
    at (.../node_modules/adminjs/lib/backend/actions/list/list-action.js:84:44
    at Array.map (<anonymous>)
    at Object.handler (.../node_modules/adminjs/lib/backend/actions/list/list-action.js:84:33)
    at async ActionDecorator.handler (.../node_modules/adminjs/lib/backend/decorators/action/action-decorator.js:56:19)
    at async(.../node_modules/@adminjs/express/lib/buildRouter.js:24:22
```

### Bug prevalence

Every time  try to access TaskUsers table

### AdminJS dependencies version

{
    "version": "1.0.0",
    "private": true,
    "type": "module",
    "scripts": {
        "build": "tsc",
        "lint": "eslint \"src\"",
        "start": "dotenv -c '.env' -- node dist/app"
    },
    "dependencies": {
        "@adminjs/express": "^6.1.0",
        "@adminjs/prisma": "^5.0.1",
        "@prisma/client": "^5.6.0",
        "adminjs": "^7.7.2",
        "express": "^4.18.2",
        "express-formidable": "^1.2.0",
        "express-session": "^1.17.3",
        "pg": "latest"
    },
    "devDependencies": {
        "@types/express": "^4.17.17",
        "@types/node": "^18.15.11",
        "@typescript-eslint/eslint-plugin": "^5.58.0",
        "@typescript-eslint/parser": "^5.58.0",
        "dotenv-cli": "^7.2.1",
        "eslint": "^8.38.0",
        "eslint-config-airbnb": "^19.0.4",
        "eslint-plugin-import": "^2.27.5",
        "eslint-plugin-jsx-a11y": "^6.7.1",
        "eslint-plugin-prettier": "^5.0.1",
        "eslint-plugin-react": "^7.32.2",
        "eslint-plugin-react-hooks": "^4.6.0",
        "prettier": "^3.1.0",
        "prisma": "^5.6.0",
        "tslib": "^2.5.0",
        "typescript": "^5.0.4"
    },
    "prisma": {
        "schema": "prisma/schema.prisma"
    }
}

### What browsers do you see the problem on?

Chrome

**Comment by dziraf** [comment]
AdminJS doesn't support composite PKs

**Comment by Habubinator** [comment]
> AdminJS doesn't support composite PKs

I see, but is there particular reason to not support it even as paramethers for options to models?
Bc it would be a huge QoL feature.

**Comment by dziraf** [comment]
Supporting composite keys would require us to rewrite most of AdminJS since everything's based on `recordId` being a single ID. We usually just add an autoincremented column in junction tables and use it as ID internally.
