### ISSUE TITLE
[Bug]: Dashboard and locale isn't changing 

### ISSUE THREAD

**Issue by Villva-vinoth** [SoftwareBrothers/adminjs#1696]
### What happened?

want display mydashboard screen and set locale both are not changing ?

import { componentLoader, Components } from './componentLoader.js';
import EmployeeResources from './resources/Employee.resource.js';

const options = () => {
    let resources = [EmployeeResources];
    const locale = {
        translations: {
            buttons: {
                save: 'Saving',
                edit: 'editing',
                login:"logging",
            },
            actions: {
                new: "add"
            }
        }
    };
    console.log(locale.translations)
    console.log(componentLoader)
    return {
        rootPath: "/admin",

        resources: resources,
        branding: {
            companyName: 'Management Tool'
        },
        // database: [sequelize],
        componentLoader,
        dashboard: {
            component: Components.Dashboard
        },
       locale:locale.translations,

    }
}

export default options

but in the console 

ComponentLoader {
  components: {
    Dashboard: {
      overrides: false,
      filePath: '/var/www/html/training/admin/src/admin/custom-components/dashboard'
    }
  }
}
Sequelize connection established !
DB synced
{
  buttons: { save: 'Saving', edit: 'editing', login: 'logging' },
  actions: { new: 'add' }
}
AdminJS started on http://localhost:4000/admin

everything is seems to crt but can't get the expected output still login button is login and dashboard is default dashboard 

### Bug prevalence

1

### AdminJS dependencies version

{
  "name": "admin",
  "version": "1.0.0",
  "main": "app.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon src/app.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "@adminjs/custom-components": "^2.0.1",
    "@adminjs/express": "^6.1.0",
    "@adminjs/sequelize": "^4.1.1",
    "@babel/core": "^7.25.2",
    "@babel/node": "^7.25.0",
    "@babel/preset-env": "^7.25.3",
    "@babel/preset-react": "^7.24.7",
    "adminjs": "^7.8.8",
    "babel-register": "^6.26.0",
    "bcrypt": "^5.1.1",
    "dotenv": "^16.4.5",
    "express": "^4.19.2",
    "express-formidable": "^1.2.0",
    "express-session": "^1.18.0",
    "nodemon": "^3.1.4",
    "pg": "^8.12.0",
    "pg-hstore": "^2.3.4",
    "sequelize": "^6.37.3",
    "tslib": "^2.6.3"
  }
}

### Relevant log output

```bash
ComponentLoader {
  components: {
    Dashboard: {
      overrides: false,
      filePath: '/var/www/html/training/admin/src/admin/custom-components/dashboard'
    }
  }
}
Sequelize connection established !
DB synced
{
  buttons: { save: 'Saving', edit: 'editing', login: 'logging' },
  actions: { new: 'add' }
}
AdminJS started on http://localhost:4000/admin
```

**Comment by dziraf** [comment]
Your `locale` structure is invalid, take a look at: https://docs.adminjs.co/tutorials/internationalization-i18n
If you used Typescript, it'd have marked the incorrect structure.

Your dashboard might not be loading and defaulting to the original dashboard if there are errors in the component. Do you see any errors when you open browser's `Console`?

**Comment by Villva-vinoth** [comment]
The Errors are fixed i made a small mistake with configuring Component Loader, Thanks for the reply, but the locale is not change i used js for development process , I made  

import { componentLoader, Components } from './componentLoader.js';
import EmployeeResources from './resources/Employee.resource.js';
import workResource from './resources/work.resource.js';
import ImageResource from './resources/Image.resource.js';


const options = () => {
  let resources = [EmployeeResources, workResource , ImageResource];

  return {
    rootPath: "/admin",

    resources: resources,
    branding: {
      companyName: 'Management Tool'
    },
    database: [sequelize],
    componentLoader,
    dashboard: {
      component: Components.Dashboard
    },

    locale: {
      language: 'en',
      en: {
        translation: {
          labels: {
            EmployeeResources: 'People',
            workResource: "works"
          },
          components: {
            Login: {
              welcomeHeader: "Welcome ",
              welcomeMessage: "",
              properties: {
                email: "phone number",
                password: "password"
              },
              loginButton: "sign in"
            }
          }
        },
      }
    },



  }
}

export default options

for Locale its also wrong can you tell me what correction i need to made for it worked !, Thanks in advance.

**Comment by dziraf** [comment]
Your locale structure is invalid. Compare it with documentation's example:

```ts
locale: { 
  language: 'pl', 
  availableLanguages: ['en', 'pl'], 
  localeDetection: true, 
  translations: { 
    pl: { 
      messages: { 
        welcomeOnBoard_title: 'Nowy tyluł pulpitu', 
      }, 
    }, 
    en: { 
      messages: { 
        welcomeOnBoard_title: 'New dashboard title', 
      }, 
    }, 
  }, 
},
```

**Comment by Villva-vinoth** [comment]
Thanks its working !
