### ISSUE TITLE
[Bug]: Cannot access the website

### ISSUE THREAD

**Issue by niraj-khatiwada** [SoftwareBrothers/adminjs#1712]
### What happened?

The website says "Bandwidth quota exceeded".
![image](https://github.com/user-attachments/assets/7661f6db-d1f8-413f-80f1-6b6247222996)

### Bug prevalence

Everytime I visit the website recently

### AdminJS dependencies version

.

**Comment by logsol** [comment]
+1

**Comment by brunoxmetal** [comment]
+1

**Comment by dziraf** [comment]
We're aware of that. I've already reported this to someone who can manage the hosting, but still waiting for some kind of action

**Comment by dziraf** [comment]
The website is back up.
