### ISSUE TITLE
[Bug]: Adminjs Resource's Hamburger menu disappears on large screen but works fine on smaller screens

### ISSUE THREAD

**Issue by hossamhamzahm** [SoftwareBrothers/adminjs#1714]
### What happened?

I am using Admin.js as a control panel for my application. Adminjs navbar contains a hamburger menu on the left to access the defined resources. This hamburger menu disappears automatically on large screens but works fine on smaller screens or if I zoomed in. What should I do to make it always visible.

![image](https://github.com/user-attachments/assets/c3bcbda5-a3bd-4a2a-a584-c04a47ec1e11)

### Bug prevalence

always

### AdminJS dependencies version

```
"dependencies": {
    "@adminjs/design-system": "^4.1.1",
    "@adminjs/express": "^6.1.0",
    "@adminjs/passwords": "^4.0.0",
    "@adminjs/relations": "^1.1.2",
    "@adminjs/sequelize": "^4.0.0",
    "@adminjs/themes": "^1.0.1",
    "adminjs": "^7.7.2"
}
```

**Comment by dziraf** [comment]
This is not a bug, the sidebar hides only on narrow screens and that's when the hamburger appears

**Comment by hossamhamzahm** [comment]
Actually, the sidebar is hidden on large screens too.

![image](https://github.com/user-attachments/assets/2019aa87-15c4-481b-9c05-39d3987a1cd9)

**Comment by hossamhamzahm** [comment]
If you mean custom components by customization, no I did not.

**Comment by hossamhamzahm** [comment]
Thanks for ur time @dziraf. I tried to open the dashboard from Edge instead of Chrome and the sidebar appeared. Furthermore, I tried ur demo (https://demo.adminjs.co/app) on Chrome and it has the same issue but it works fine on Edge. It is probably an issue with one of the extensions installed on Chrome. Again thanks for ur time : )
