### ISSUE TITLE
Firebase Datastore Adapter

### ISSUE THREAD

**Issue by vikeen** [SoftwareBrothers/adminjs#291]
I build apps for clients and almost always use Firebase as my backend service. Is there a Firebase plugin support on the roadmap? How hard would it be for me to dive in the knock that out with no admin-bro experience under my belt?

**Comment by wojtek-krysiak** [comment]
we tried to deploy this in firebase last week - unfortunately without a success. Probably we will try out this again in ~3-4 weeks.

**Comment by vikeen** [comment]
Sorry to be about your initial efforts. What were you trying to deploy / experiment with?

Just to be clear I don't to deploy **in** I want to utilize Firebase as my data persistance layer. As I mentioned I build apps (React Native / Firebase) for clients and often they want to manage some aspects of their data.

Ideally, I'm looking for a simple admin tool that is similar to Rails Admin / Dango Admin to integrate with the documents in Firebase.

**Comment by wojtek-krysiak** [comment]
aaa - ok - I meant: We tried to deploy to `firebase functions`. We haven't tried to utilize Firebase Datastore, and don't have this in the roadmap so far.

But this will be super interesting to have those 2 integrations. So let's leave this open for now, but no ETA - maybe someone will try to make an adapter for that.

**Comment by JonaszJestem** [comment]
I think I can try to write an adapter to resolve this issue. I will post an update soon.

**Comment by JonaszJestem** [comment]
[GitHub - Admin Bro Firebase](https://github.com/JonaszJestem/admin-bro-firebase)
[NPM - Admin Bro Firebase](https://www.npmjs.com/package/admin-bro-firebase)
Initial version - working resources, actions - create/find/show/delete. Known issues are described in README. Feel free to contribute, I'm probably going to resolve those issues next weekend.

**Comment by dziraf** [comment]
Closing as the firestore adapter is complete. Any related issues should be reported in it's repository.
