### ISSUE TITLE
Enhancement: Add more useful methods like list, delete, edit, show to ApiClient and ViewHelpers

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/adminjs#294]
Right now ApiClient has functions like recordAction, resourceAction etc. This is totally cool because it relates to the AdminBro architecture but it would be good to have an alias functions.

So instead of calling 
```
api.recordAction({actionName: 'show', recordId: 'xxx', resourceId: 'zzz'})
```

it would be good to have:

```
api.show(recordId, resourceId)
```

the same for list, edit, delete, bulkDelete.

**Comment by dziraf** [comment]
This is done for `ViewHelpers` only: https://github.com/SoftwareBrothers/adminjs/blob/master/src/backend/utils/view-helpers/view-helpers.ts#L162

TODO in `ApiClient`

**Comment by krzysztofstudniarek** [comment]
We don't plan to do it.
