### ISSUE TITLE
Document a way of wrapping Existing api with BaseResource

### ISSUE THREAD

**Issue by user753** [SoftwareBrothers/adminjs#306]
**Original question:**

I have my own rest crud api and I would like to use only frontend part of admin-bro.
Does admin-bro support such scenario?

**Proposed solution: MVP**

* document how to wrap existing API by BaseResource

**End Solution**

* extend admin-bro core that, instead of asking own API, asks external API
* this could be a method in Action interface: `externalAPI` (but we have to think of how to copy this function to the 'frontend' side)

**Comment by wojtek-krysiak** [comment]
yes, but it is not the same as in react-admin. You will have to write your custom resource adapter which extends from BaseResource class.

I recently wrote an example app in typescript which shows this approach:

Here is the adapter which wraps JIRA API for projects: https://github.com/wojtek-krysiak/admin-bro-workshop/blob/master/src/jira-projects/jira-project.adapter.ts

and here is how to add this to AdminBroOptions: https://github.com/wojtek-krysiak/admin-bro-workshop/blob/master/src/admin/router.ts#L25

Example uses the latest beta version but it should work with the 1.6.x as well.

Here you can find the documentation for all methods in BaseResource: file:///Users/wojciechkrysiak/Documents/projekty/admin-bro-dev/docs/BaseResource.html (1.6v)

or:

file:///Users/wojciechkrysiak/Documents/projekty/admin-bro-dev/docs/v2/BaseResource.html (2.0 v)

**Comment by user753** [comment]
@wojtek-krysiak Thanks. Is it possible to use AdminBro UI as SPA without any server routing? If so, how could I render root component?

**Comment by user753** [comment]
@wojtek-krysiak any help?

**Comment by wojtek-krysiak** [comment]
you can reuse our design system. It is here: https://github.com/SoftwareBrothers/admin-bro/tree/master/src/frontend/components/design-system. You can copy it to your project and use all the components we build (we have plan to extract this to a separate npm package)

**Comment by user753** [comment]
@wojtek-krysiak No, I mean I would like if it would be possible to use auto generated UI for `BaseResource` as SPA application. 
For example in react-admin you need to implement `DataProvider` and it is possible to create UI for it
```
render(
    <Admin dataProvider={dataProvider}>
        <Resource name="posts"/>
    </Admin>,
    document.getElementById('root')
);
```
Is there any plans to support something like this?

**Comment by wojtek-krysiak** [comment]
no. we dont have this in plans unfortunately :(. but may I ask why you dont want to use react-admin?

**Comment by user753** [comment]
It have a pure support for typescript and also it doesn't have something like `ResourceOptions` so one need to configure everything through components.

**Comment by user753** [comment]
What is the advantages of using frontend UI through server instead of SPA approach?

**Comment by wojtek-krysiak** [comment]
in server version, you have everything out of the box. So, in order to build a working admin panel you just need a database connection - admin generates api routes on the backend with all the CRUD logic. In SPA version you have to maintain backend on our own.

I am leaving this task open. Maybe someone will do this.

**Comment by Inoir** [comment]
why is this closed? this isnt documented https://docs.adminjs.co/basics/resource or do i miss something?!
