### ISSUE TITLE
New ResourceAction: export files

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/adminjs#322]
- option to pick export all or only currently filtered record.
- in the MVP it could be in the root process - in the documentation, there should be a info how to move this to the background job (example)

**Comment by sharath-mallikarjuna** [comment]
Hi @wojtek-krysiak 
Any progress made on this?
I'm looking for an option to Export the resource data into csv

**Comment by ayushbhat** [comment]
Hi, is this still getting worked on or we have dropped this idea?

**Comment by mohamednazmi1** [comment]
Hi @wojtek-krysiak
What is the status of this feature?

**Comment by arunim2405** [comment]
Any progress on this?

**Comment by marcjoancr** [comment]
Any news? There will also be any import from csv feature?

**Comment by CarlosQ96** [comment]
Hello! any news?

**Comment by dziraf** [comment]
There's `@adminjs/import-export`, any related issues should be posted there
