### ISSUE TITLE
Improve schema definition in BaseResource

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/adminjs#323]
Right now BaseResource has 2 methods which have to be implemented: property() and properties(). The common implementation is something like this

```
// in constructor
  this.rawProperties = [
      new BaseProperty({
        path: 'name',
        isId: false,
        isSortable: true,
        type: 'string',
      }),
      new BaseProperty({
        path: 'key',
        isId: true,
        isSortable: true,
        type: 'string',
      }),
      new BaseProperty({
        path: 'image',
        isId: false,
        isSortable: false,
        type: 'string',
      }),
    ];
// ...

  properties() {
    return this.rawProperties;
  }

  property(path: string) {
    return this.rawProperties.find((p) => p.path() === path) ?? null;
  }
```

this is not super elegant. The simplest would be to allow users defining schema and propety and properties should be generated automaticaly (implement them in root class)

**Comment by KrishnaPG** [comment]
Also, please consider making all the accessor methods of the schema / resource properties as async. For example, these resource definitions might be stored inside a database and retrieved on demand. (for example, the `properties()` and `property(path: string)` should be async).

This is usually the case in multi-tenant systems, where the schemas are not pre-defined.

**Comment by dziraf** [comment]
Closing as this has not been discussed locally since this issue had been opened and will likely not be implemented in near future. If you have any ideas on it's implementation please open a new issue.
