### ISSUE TITLE
Describe how to run admin in the development

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/adminjs#331]
describe:

* linking
* yarn types
* yarn build
* yarn bundle
* yarn bundle:globals

describe the distinction in production/development build

Also, write a script which runs all things together.

**Comment by ariansobczak-rst** [comment]
Ready in https://github.com/SoftwareBrothers/adminjs/pull/1017 by improving https://github.com/SoftwareBrothers/adminjs-dev
