### ISSUE TITLE
Edit login page

### ISSUE THREAD

**Issue by farmgameowner** [SoftwareBrothers/adminjs#347]
I whant to remove this
![image](https://user-images.githubusercontent.com/52417090/75908298-72035c80-5e7c-11ea-831b-0a9cb4dcaf43.png)

**Comment by wojtek-krysiak** [comment]
you can change text with i18n: https://softwarebrothers.github.io/admin-bro-dev/tutorial-09-i18n.html (keys: https://github.com/SoftwareBrothers/admin-bro/blob/master/src/locale/en.ts#L61 && https://github.com/SoftwareBrothers/admin-bro/blob/master/src/locale/en.ts#L30)

Currently, we don't have an option to hide an entire box. But we are planning to allow users to change images and it should be done end of the next week.

Leaving this open - maybe someone would like to add this option to something like `branding.loginInfoBox`

**Comment by farmgameowner** [comment]
Also if i want to change "+ add new item", what should i do?

**Comment by wojtek-krysiak** [comment]
if you like to change it for all buttons in AdminBroOptions:

```
locale: {
  translations: {
    actions: {
      new: 'Add new "new" :)'
    }
  }
}
```

in case you wan to change just add new action for one resource:
```
locale: {
  translations: {
    resources: {
      [yourResourceId]: {
        actions: {
          new: 'Add new "new" :)'
        }
      }
    }
  }
}
```

To obtain the resourceID open the chrome terminal and write REDUX_STATE - it has list of all the resources with their id's

**Comment by m-135a** [comment]
Hello, did you add the feature of customizing the login box? I'm using adminbro for a project and I need to add a custom picture.

**Comment by m-135a** [comment]
Hello, did you add the feature of changing the image of the login box? I'm using AdminBro for a project and I need to change the image. Also the docs do not have clear instructions on customizing the login page.

**Comment by wojtek-krysiak** [comment]
a login page is not customisable - you would need to create a new login route and handle login there (check out admin-bro-express code for an example - build authenticated router method)

**Comment by m-135a** [comment]
So if I wanted to just remove/change the photo I have to create a new login route? Because I thought it is going to be a feature in a next release or something. And by the way, thank you so much for the awesome project. Adminbro is really helpful and cool.

**Comment by wojtek-krysiak** [comment]
thanks - yes definitely we will make it a feature at some point since lots of people asking about it, but the solution for "right now" would be to override the route

**Comment by akashhardia** [comment]
still no way to change the image?
If not, I don't see a properly documented way to manage the custom login route.

**Comment by wojtek-krysiak** [comment]
sorry - this is not customisable (atm).

**Comment by akhilnayak0206** [comment]
Hey, @wojtek-krysiak any way to override CSS on the login page.
I tried using assets.styles to add css file and adding then adding CSS property name(.cvvLnE) with `display: none !important;` but wasn't successful in hiding that.
Any other way to hide the welcome box?
Thank You so much for this awesome project.

**Comment by joelongstreet** [comment]
@akhilnayak0206 - It looks like custom stylesheets and scripts aren't passed to the login page. I have a pull request out to update this - https://github.com/SoftwareBrothers/admin-bro/pull/726

**Comment by fahimhoque** [comment]
So how would I change the tab title or add a new login page?
My project admin dashboard shows company as a default which I would like to change. Any suggestions?

**Comment by Herve97** [comment]
So how i can change the dashboard?

**Comment by damian-pastorini** [comment]
The easier way to partially edit the login page is by changing the texts using the branding, the locale.translations (messages and labels), and by using your own assets, for example:

`branding: {
                companyName: 'Your project name',
                softwareBrothers: false,
                logo: '/your-logo-url/your-logo-file.png', // OR false to hide the default one
            },
            locale: {
                translations: {
                    messages: {
                        loginWelcome: 'Administration Panel - Login' // the smaller text
                    },
                    labels: {
                        loginWelcome: 'The Big Text', // this could be your project name
                    },
                }
            },
            assets: {
                styles: ['/css/your-custom-styles.css'], // here you can hide the default images and re-position the boxes or text.
            },`

**Comment by salehdeh76** [comment]
> The easier way to partially edit the login page is by changing the texts using the branding, the locale.translations (messages and labels), and by using your own assets, for example:
> 
> ```
> branding: {
>     companyName: 'Your project name',
>     softwareBrothers: false,
>     logo: '/your-logo-url/your-logo-file.png', // OR false to hide the default one
> },
> locale: {
>     translations: {
>         messages: {
>             loginWelcome: 'Administration Panel - Login' // the smaller text
>         },
>         labels: {
>             loginWelcome: 'The Big Text', // this could be your project name
>         },
>     }
> },
> assets: {
>     styles: ['/css/your-custom-styles.css'], // here you can hide the default images and re-position the boxes or text.
> },
> ```

But still the image in welcome pane is not changed!

**Comment by damian-pastorini** [comment]
> > The easier way to partially edit the login page is by changing the texts using the branding, the locale.translations (messages and labels), and by using your own assets, for example:
> > ```
> > branding: {
> >     companyName: 'Your project name',
> >     softwareBrothers: false,
> >     logo: '/your-logo-url/your-logo-file.png', // OR false to hide the default one
> > },
> > locale: {
> >     translations: {
> >         messages: {
> >             loginWelcome: 'Administration Panel - Login' // the smaller text
> >         },
> >         labels: {
> >             loginWelcome: 'The Big Text', // this could be your project name
> >         },
> >     }
> > },
> > assets: {
> >     styles: ['/css/your-custom-styles.css'], // here you can hide the default images and re-position the boxes or text.
> > },
> > ```
> 
> But still the image in welcome pane is not changed!

You can change it using the custom styles, the image is placed as background, you can go and change it or just remove the background from the element and the image will be removed.

**Comment by huynbt209** [comment]
I like your Icon <3, can you send it to me?

**Comment by nokeludak** [comment]
How to change login background-color??

**Comment by lavisar** [comment]
I have tried to custom the CSS then add to assets of AdminJS and it work!

![image](https://github.com/user-attachments/assets/c3b2cff0-23f6-4099-86bc-dc104c829c5b)
![image](https://github.com/user-attachments/assets/9ecfa98b-66bb-4db3-90a4-3cd48c09dcb8)

**Comment by Devendra0110** [comment]
In the new version, you have to pass translation differently.
```
locale:{
        language:'en',
        translations: {
            en:{
              components: {
                Login:{
                  welcomeMessage : "Welcome to Admin Panel"
                }
              }
            }
        }
      },
```
The keys also has been update, here is the [link](https://github.com/SoftwareBrothers/adminjs/blob/master/src/locale/en/translation.json)
