### ISSUE TITLE
Refactor bundling user components

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/adminjs#359]
Right now bundling is spread into several places in the AdminBro API and have some inconsistencies:

1. there is an AdminBro#initialize method which is called by the plugins (it works only in production environment)
2. there is an AdminBro#watch method which can be called within the app (works only in !== production environment)
3. there is a AdminBroOptions.assetsCDN property which defines from static assets should be downloaded (which is kind of ok)
4. assets generated by AdminBro goes to `./adminbro/bundle.js` but frontend asks for `components.bundle.js` (Router changes that)
5. there is a `userComponentsBundler` which is not exported by AdminBro.

Acceptance criteria

In this task we will have to organise those things.
* create one method AdminBro#bundleComponents(options) with options to:
** change path of the files
** write and watch files (the same as userComponentsBundler)
* this method should generate `components.bundle.js` file (not bundle.js file)
* working on this method should NOT depend on env variables.
* change plugins to use the new method

**Comment by duyet** [comment]
Hi @wojtek-krysiak, do you any updates on this?

**Comment by helsonxiao** [comment]
Errors with `react-markdown`:

```
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
'path' is imported by node_modules/vfile/lib/minpath.js, but could not be resolved – treating it as an external dependency
'url' is imported by node_modules/vfile/lib/minurl.js, but could not be resolved – treating it as an external dependency
'process' is imported by node_modules/vfile/lib/minproc.js, but could not be resolved – treating it as an external dependency
No name was provided for external module 'process' in output.globals – guessing 'proc'
No name was provided for external module 'url' in output.globals – guessing 'url'
No name was provided for external module 'path' in output.globals – guessing 'path'
Creating a browser bundle that depends on Node.js built-in modules ("process", "url" and "path"). You might need to include https://github.com/snowpackjs/rollup-plugin-polyfill-node
```

**Comment by umbrellait-danil-rodin** [comment]
Any updates here? Same issues. It's confusing because in the development env importing external libraries works fine, but in production all the custom components is broken.

**Comment by AshotN** [comment]
I am experiencing a similar issue trying to use https://github.com/Ionaru/easy-markdown-editor
