### ISSUE TITLE
Bulk delete could use delete handler

### ISSUE THREAD

**Issue by SimonB407** [SoftwareBrothers/adminjs#427]
**Describe the problem feature solves**
Default bulk delete handler uses separate, own implementation of deleting one record. Snippet:
```
// ...
await Promise.all(records.map(record => resource.delete(record.id())))
// ...
```
Instead it could use delete handler from this resource, because it is already doing iteration through each record. This is also beneficial for example for soft delete option implementation, because record deletion logic could be defined in delete action handler and bulk delete automatically would behave as expected.

**Describe the solution you'd like**
Use handler from delete action. It's important to take custom handler if present.

**Acceptance criteria**
- bulk delete action uses handler from delete action to delete all records
- when user provides custom handler for delete action, it should be used instead of the default one in bulk action
- custom bulk delete action handler works as previously

**Comment by wojtek-krysiak** [comment]
In your proposal, we will limit users to always use logic from (single)delete action. And these are the problems I see:

* when I override delete action I also override bulkDelete action automatically. Both actions are separated in the config so I would expect they are not connected.
* what If I want to create different logic for bulk delete. So let's say I override (single)delete that it sends a mail after deletion, and I want bulkDelete to work in a totally different fashion.
* both functions have totally different get actions (one removes an item and the other prints a summary for "records to delete")

So maybe when we will add hooks to the Mongo we could do things there and leave out logic as it is right now?

**Comment by SimonB407** [comment]
I agree that database hooks could solve these issue. 
  
Regarding all your concerns:
* delete & bulkDelete in my opinion should behave the same in almost every case. Bulk delete is only a shortcut for not having to manually delete multiple records one by one.
* Current implementation allows modifying bulkDelete handler, so it can still be done. I think the question is, if there is more cases when I want bulkDelete to behave same as delete, or there is more cases when I want bulkDelete and delete to behave differently.
* In my proposal I don't want to remove bulkDelete handler and replace it by delete handler. I just want bulkDelete POST handler to use delete handler when performing records removal. So this is not a problem. In the snipped I showed only one line from bulkDelete handler that I think could be changed. Nothing more.

**Comment by cscovino** [comment]
How I can modify bulk delete handler right now? I'm doing the delete action in this way:
```
AdminBro.ACTIONS.delete.handler = async (request, response, data) => {
  const { record, resource, currentAdmin, h, translateMessage } = data;
  if (!request.params.recordId || !record) {
    throw new NotFoundError(['You have to pass "recordId" to Delete Action'].join('\n'), 'Action#handler');
  }
  try {
    const newRecord = await record.update({ dateDeleted: new Date() });
    const [populatedRecord] = await populator([newRecord]);
    // eslint-disable-next-line no-param-reassign
    data.record = populatedRecord;

    return {
      record: populatedRecord.toJSON(currentAdmin),
      // eslint-disable-next-line no-underscore-dangle
      redirectUrl: h.resourceUrl({ resourceId: resource._decorated?.id() || resource.id() }),
      notice: {
        message: translateMessage('successfullyDeleted', resource.id()),
        type: 'success',
      },
    };
  } catch (error) {
    if (error instanceof ValidationError && error.baseError) {
      return {
        record: record.toJSON(currentAdmin),
        notice: {
          message: error.baseError.message,
          type: 'error',
        },
      };
    }
    throw error;
  }
};
```

**Comment by cscovino** [comment]
Ok, I was able to modify the bulk delete handler but I have to change the handler on every resource for example:
```
const options = {
  actions: {
    bulkDelete: {
      handler: async (request, response, context) => {
        const { records, resource, h, translateMessage } = context;

        if (!records || !records.length) {
          throw new NotFoundError('no records were selected.', 'Action#handler');
        }
        if (request.method === 'get') {
          const recordsInJSON = records.map((record) => record.toJSON(context.currentAdmin));
          return {
            records: recordsInJSON,
          };
        }
        if (request.method === 'post') {
          await Promise.all(records.map((record) => record.update({ dateDeleted: new Date() })));
          return {
            records: records.map((record) => record.toJSON(context.currentAdmin)),
            notice: {
              message: translateMessage('successfullyBulkDeleted', resource.id(), {
                count: records.length,
              }),
              type: 'success',
            },
            // eslint-disable-next-line no-underscore-dangle
            redirectUrl: h.resourceUrl({ resourceId: resource._decorated?.id() || resource.id() }),
          };
        }
        throw new Error('method should be either "post" or "get"');
      },
    },
  },
};

const AdminCompany = {
  resource: Company,
  options,
};
```
It will be great I we can modify the handler in global manner as we can do with (single) delete, show, edit and so on. Or If there is a better way I will be grateful if you can tell me how.

**Comment by SimonB407** [comment]
It looks like not updated types, but bulkDelete can be modified from global actions. AdminBro.ACTIONS is set as [this](https://github.com/SoftwareBrothers/admin-bro/blob/master/src/backend/actions/index.ts).

**Comment by cscovino** [comment]
Ok, great. Thanks!

I create [this](https://github.com/SoftwareBrothers/admin-bro/pull/795) pull request with this fix.
