### ISSUE TITLE
Session on different tab mismatch

### ISSUE THREAD

**Issue by JonaszJestem** [SoftwareBrothers/adminjs#472]
**Describe the bug**
Login as first user in one browser tab. Open second browser tab with Admin Panel -> Log out -> Login in as second user. 

Navigate to first tab. You can navigate through application with no information that you are the second user actually, because cookie changed and the UI with username is still the same

**Installed libraries and their versions**
    "admin-bro": "^2.3.1",
    "admin-bro-expressjs": "^2.0.3",
    "admin-bro-firebase-functions": "^2.1.1",
    "admin-bro-mongoose": "^0.5.2",

**Expected behavior**
UI should refresh to indicate that the user changed.

**Comment by wojtek-krysiak** [comment]
this should be an option in all the plugins (not the core). Right now they store user in session just once after login.

To solve this in let say @admin-bro/express would be to add an additional middleware to the router which will refetch user on every request. this middleware chould be trigger when user give callback: 'validateCurrentAdminOnEveryRequest(userId)' (or other name) in buildAuthenticatedUser. We can do this along with the refactor of the plugin to typescript :)
