### ISSUE TITLE
Columns with period in the name do not work correctly

### ISSUE THREAD

**Issue by bakkerthehacker** [SoftwareBrothers/adminjs#525]
**Describe the bug**
Sequelize models may have periods in the names of their columns.  These models do not work correctly in adminbro.

**Installed libraries and their versions**

```
"admin-bro": "^2.4.3",
"admin-bro-expressjs": "^2.1.0",
"admin-bro-sequelizejs": "^0.5.1",
```

**To Reproduce**
1. create a model with a column that has a period in its name
2. create a resource with this model
3. try to create or update this model in adminbro
4. creating fails (column is null) and updating has no effect on this columns with periods

**Expected behavior**
Creating and updating these columns should work

**AdminBroOptions with schema**
Paste your AdminBro config with database schema if it could be related to the issue
```
const TestModel = sequelize.define('TestModel', {
  name: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  'something.with.dots': {
    type: Sequelize.STRING,
    allowNull: false,
  },
}, {});
```

**Comment by wojtek-krysiak** [comment]
we use dot notation to flat / unflat the objects (this package https://www.npmjs.com/package/flat is used) That is why this is not possible. Implementing this will be super problematic so I am closing this issue

**Comment by bakkerthehacker** [comment]
I'm confused why this is closed.  Is this intended behaviour? Is there a workaround for tables with these columns?

**Comment by wojtek-krysiak** [comment]
sorry for being not clear. Closed that because I think that in current architecture it is not possible :(. But you are right - let's keep this open - maybe someone will find a solution.
