### ISSUE TITLE
Allow isVisible and isDisabled in PropertyOptions to take in function so that its value can be dynamically computed based on context 

### ISSUE THREAD

**Issue by xming13** [SoftwareBrothers/adminjs#543]
**Describe the problem feature solves**
Currently `isVisible` and `isDisabled` in PropertyOptions only takes in boolean. However, there are times where this needs to be computed dynamically based on context. A use case is to enable/disable editing a particular field based on current user’s role, e.g. only admin can update the publishing status of an item.

**Describe the solution you'd like**
Change `isVisible` and `isDisabled` in PropertyOptions to take in a function or boolean. similar to `isVisible` in Actions https://adminbro.com/Action.html#isVisible

**Describe alternatives you've considered**
No alternatives have been considered.

**Acceptance criteria**
- [ ] isVisible can take in a function
- [ ] isDisabled can take in a function

**Comment by wojtek-krysiak** [comment]
yesterday we released a new "layout" option. It can take a function and you can define which fields goes where. https://adminbro.com/Action.html#layout

but for is disabled and is visible you are right. We will have to implement it

**Comment by johnyvelho** [comment]
Following the @wojtek-krysiak suggestion, this was how I accomplished this need:

```
options: {
  ...yourResourceOptions,
  actions: {
    edit: {
        layout: (currentAdmin) => {
            const allResourceAttributes = Object.keys(Schema.paths)
    
            if (currentAdmin.role.name !== 'example') return allResourceAttributes
    
            const hideFields = [
                'table_field_example1',
                'table_field_example2',
                '_id',
            ]
    
            return allResourceAttributes.filter((item) => hideFields.indexOf(item) === -1)
        },
    },
  }
}
```
