### ISSUE TITLE
Primary key, which is not sequential, doesn't work

### ISSUE THREAD

**Issue by bowd** [SoftwareBrothers/adminjs#544]
**Describe the bug**
This is not so much a bug as it is a failing of the current design, but I wouldn't class it as a feature request because I believe that the current behaviour isn't the _expected_ behaviour.

If I have a Primary Key that is a string for example and it's not autogenerated as a sequence, and I add it as a column to show up in the form, I can not create records. That happens right now because `BaseRecord` makes the false assumption that because an ID is present inside of the properties then the record was saved at some point and it should do an update. But this doesn't have to be the case.

> This currently happens with typeorm, but I have looked at the sequelize code and haven't seen any reason to believe it doesn't happen there as well.

This could be addressed outside of the main project at the `admin-bro-typeorm` or `admin-bro-sequlize` level by extending and using a different record type. But I think it would be better if there's a `BaseRecord.create` method which, unlike `BaseRecord.save` just calls `this.resource.create` instead of checking the `id`. Then in the [action](https://github.com/SoftwareBrothers/admin-bro/blob/v2.9.0/src/backend/actions/new-action.ts#L31) we should call `await record.create()`.

**Installed libraries and their versions**

* admin-bro@2.9.0
* admin-bro-typeorm@0.1.6-alpha.9
* admin-bro-mongoose@2.1.1

**To Reproduce**
1. Setup a record with a primary id that's not automatically set by the database.
2. Add the id to the proprieties that show up in the form
3. Try to create a record with a manually filled in ID.

**Expected behavior**

It should be possible to create a record.

**Other cases**

take a look at this issue: #545 - this case also should be taken into consideration

**Comment by wojtek-krysiak** [comment]
yep - this is a known issue. The way of solving that could be:

* add a new method: 'isNew' in the BaseRecord or in BaseResource, which will simply return `!!this[primaryKey]` for backward compatibility.
* and then implement this method in all the adapters.

But since this issue is easy to fix (add a primary key which is sequential) it is on the bottom of the backlog :(

**Comment by bowd** [comment]
Yeah I understand, there are valid use-cases where a sequential key is not possible. But I understand it being low priority because it can be solved by extending the resource. 

But I'm not sure what you mean by the `!!this[primaryKey]` at which point would you do that because you can't really _know_ if this is an update or create just by looking at the data. You have to either rely on the intent (i.e. explicit create method in the controller) or query the database beforehand, unless I'm missing something.

**Comment by DenizUgur** [comment]
Are there any updates to this?

**Comment by helsonxiao** [comment]
I got validation errors **randomly** when adding new record based on this typeorm definition. Not sure why. Maybe hide uuid in edit mode will fix it?
```
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  @Generated('uuid')
  uuid: string;
```

**Comment by dansgithubuser** [comment]
Why is this closed? I think I'm having the same problem with express/sequelize and a string primary key.
