### ISSUE TITLE
Encoding uri breaks search records function

### ISSUE THREAD

**Issue by SimonB407** [SoftwareBrothers/adminjs#556]
https://github.com/SoftwareBrothers/admin-bro/blob/8395dca2b8a2de85233f01f4f786aa96d05de32f/src/frontend/utils/api-client.ts#L186

This solution transforms query filters to something that API does not understand. For example adding `?id={someID}` it's transformed to `%3Fid%3D{someId}`which backend cannot process resulting in empty result.
What's more using query is very ugly from code perspective. All that string contantenation can be avoided by just using `params` that axios provide (which takes object instead of string and handles everything on his own).

**Comment by ariansobczak-rst** [comment]
`Params` in this issue should be used to specify filters only but not queries. The issue is to be closed.
