### ISSUE TITLE
Move out bundler to a separate package and optymise

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/adminjs#575]
**Describe the problems feature solves**

* Right now we are using rollup, which is problematic because it doesn't bundle images, css, and some packages where it cannot find exports (ie material design)
* Along with bundler we have to add to dependencies rollup/xxxx and babel/xxx
* Bundling is configured right now with global variables
* Bundling is not described in the documentation
* removing bundler will even allow us to drop react, react-dom dependency because in the basic setup there won't be custom components. We can require users to install bundler after first call to AdminBro.bundle method.

**Describe the solution you'd like**

1. part 1 - upgrade rollup bundler to the latest version [already done]
2. totally replace rollup with something else - preferable https://github.com/evanw/esbuild because it is the fastest

**Acceptance criteria**

1. bundler should bundle these 3 scripts
* global bundle
* app bundle
* component bundle
as well as @bundle from the admin-bro/design-system
2. bundler should be in a separate package: @admin-bro/bundler with CLI and API.
- this will be a optionalDependency of AdminBro - only required when user runs AdminBro.bundle (or bundle will be taken from `@admin-bro/bundler`)
3. Bundler should handle external dependencies with ease (like slate.js, material UI etc)
4. there should be a clear information in docs how it works and how to bundle/watch and run it in production

Optional
* bundler needs to be attached only when user needs it (uses AdminBro.bundle method at least once - but question: what with features which also uses AdminBro.bundle?)
* checkout https://github.com/vitejs/vite

This should also fix the problem where typescript components tsx cannot be used from inside the node_modules

**Comment by dyabala** [comment]
Good to know that, current development with rollupjs takes too slow :(. Keep working hard sir.

**Comment by wojtek-krysiak** [comment]
you can speed up the build with AdminBro#watch()

```
const admin = new AdminBr(options)
admin.watch()
```

**Comment by wojtek-krysiak** [comment]
tested esbuild and it works for global packages with slightly updated entry file (`import * from xxx` for some packages)

```
esbuild ./src/frontend/global-entry.js  --bundle --define:process.env.NODE_ENV='"development"' --define:global=window --outfile=./src/frontend/assets/scripts/global-bundle.development.js
```

the run took `ms` instead of `20s` :)

**Comment by wojtek-krysiak** [comment]
also was working on bundling user components - ended up with:

```sh
esbuild .entry.js \
--bundle --define:process.env.NODE_ENV='"development"' \
--define:global=window \
--target=chrome58,firefox57,safari11,edge16 \
--external:react \
--external:react-dom \
--external:redux \
--external:react-redux \
--external:flat \
--external:react-router \
--external:react-router-dom \
--external:react-datepicker \
--external:styled-components \
--external:admin-bro \
--external:@admin-bro/design-system \
--external:axios \
--external:recharts \
--external:@carbon/icons-react \
--external:react-select \
--external:react-select/async \
--external:react-select/creatable \
--external:i18next \
--external:react-i18next \
--outfile=./bundle.js
```

but this requires more work - loading externals

**Comment by alvaropaco** [comment]
I'm stucked with the `rollup` fsevents dependency. Apparently, the dependencies are not installed with --no-optional: 
`ERROR in .../node_modules/admin-bro/node_modules/rollup/dist/es/shared/rollup.js
Module not found: Error: Can't resolve 'fsevents' in '.../node_modules/admin-bro/node_modules/rollup/dist/es/shared'`
