### ISSUE TITLE
Error validation breaks on recent versions of Mongoose

### ISSUE THREAD

**Issue by domingosl** [SoftwareBrothers/adminjs#595]
I cannot find any reference on the Mongoose web site BUT I'm almost 100% sure that they change the error object key "errors" to "data". In fact if you input a wrong value in a Adminbro form it breaks the backend saying:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at createValidationError (/Users/domingosarmiento/WebstormProjects/sp-api-v1/node_modules/@admin-bro/mongoose/src/utils/create-validation-error.js:4:25)
    at Resource.update (/Users/domingosarmiento/WebstormProjects/sp-api-v1/node_modules/@admin-bro/mongoose/src/resource.js:179:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The file in question is create-validation-error:

```
const { ValidationError } = require('admin-bro')

const createValidationError = (originalError) => {
  const errors = Object.keys(originalError.errors).reduce((memo, key) => {
    const { message, kind, name } = originalError.errors[key]
    return {
      ...memo,
      [key]: {
        message,
        type: kind || name,
      },
    }
  }, {})
  return new ValidationError(errors)
}

module.exports = createValidationError

```

If you change **originalError.errors** with **originalError.data** it works as intended.

**Comment by wojtek-krysiak** [comment]
which version of mongoose do you use? We have to implement it that it works with older versions as well so there will be an "if" version === statement or something like that

**Comment by domingosl** [comment]
> which version of mongoose do you use? We have to implement it that it works with older versions as well so there will be an "if" version === statement or something like that

The latest one, BUT, I'm sure they change it several versions ago because we have a similar problem at the beginning of the year with a module we develop that was using .errors instead of .data

**Comment by wojtek-krysiak** [comment]
added to the backlog. will check it out along other tasks from 3.3 milestone
