### ISSUE TITLE
CSP Error (inline script)

### ISSUE THREAD

**Issue by t1nky** [SoftwareBrothers/adminjs#607]
After login, I'm getting a couple of errors in the developer console
1. `Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-ufwggF5N/hQohyvrXIA0Cw56aUG2MQ/TRMcGbS3GBIA='), or a nonce ('nonce-...') is required to enable inline execution.`
2. `Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".`
3. `Uncaught TypeError: Cannot set property 'UserComponents' of undefined`

**Installed libraries and their versions**

* @admin-bro/express: 3.0.0
* @admin-bro/sequelize: 1.1.0
* admin-bro: 3.2.5
* helmet: 4.1.1

**To Reproduce**
1. Install Helmet
2. Run server
3. Open admin page
4. Log in

**Expected behavior**
Admin page opened

![image](https://user-images.githubusercontent.com/1833969/93348677-f5503280-f84f-11ea-9576-c5e1b4bde09c.png)

**Comment by wojtek-krysiak** [comment]
do you have sone stacktrace? I think that points 1 and 2 are not related to AdminBro. point 3 can be related to different versions used by adminbro modules. Can you run 'npm ls admin-bro' and paste the output?

**Comment by t1nky** [comment]
```
PS D:\Projects\videos\server> npm ls admin-bro     
videos-api@0.1.0 D:\Projects\videos\server
`-- admin-bro@3.2.5

PS D:\Projects\videos\server> 
```

All errors are gone without Helmet. Also, I'm not getting any errors with Helmet on other pages.

**Comment by t1nky** [comment]
First error points here:
![image](https://user-images.githubusercontent.com/1833969/93377519-8802c880-f874-11ea-8991-8d77ad590889.png)

**Comment by t1nky** [comment]
```
app.use(helmet({
    contentSecurityPolicy: {
        directives: {
            defaultSrc: ["'self'"],
            scriptSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
            styleSrc: ["'self'", "https:", "'unsafe-inline'"],
            baseUri: ["'self'"],
            fontSrc: ["'self'", "https:", "data:"]
        }
    }
}));
```

This fixed errors for me. But in my opinion, it should be used without extra 'unsafe' directives. 

Also, can you let me know if it is intended or it should be fixed (maybe it is related to another package):
Works for me with lowercased plural key
![image](https://user-images.githubusercontent.com/1833969/93383528-314dbc80-f87d-11ea-9792-ca4e5910c310.png)

But from the docs, it starts form capital and is singular/same as the model name
![image](https://user-images.githubusercontent.com/1833969/93383563-3ca0e800-f87d-11ea-9c94-929f436d90ff.png)

**Comment by wojtek-krysiak** [comment]
regarding helmet i havent used it. maybe we can adjust some global config to make it more elegant.

the translations keys are resource id's. Depend on the particular database. We have to add some kind of translation panel/script to make it more user friendly, but its not in the backlog right now.

**Comment by sidshrivastav** [comment]
Hey there! Is there any update on this? I am facing a similar issue, but after login no page rendering on production with the error in the console.

![image](https://user-images.githubusercontent.com/28773690/95748516-b8912300-0cb7-11eb-9c67-d8907c49e627.png)

**Comment by wojtek-krysiak** [comment]
no

**Comment by sidshrivastav** [comment]
Also, I found this!
![Capture](https://user-images.githubusercontent.com/28773690/95764397-0add3e80-0cce-11eb-8232-5d7ad71c98ee.PNG)

I think this is something similar to [issue](https://github.com/mozilla/pdf.js/issues/11036)

**Comment by wojtek-krysiak** [comment]
maybe it will be resolved by: #614

**Comment by Agill-Sheron** [comment]
What was the solution for this issue? I'm facing the same problem on Chrome, but Safari works fine.

**Comment by toutpuissantged** [comment]
> app.use(helmet({
>     contentSecurityPolicy: {
>         directives: {
>             defaultSrc: ["'self'"],
>             scriptSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
>             styleSrc: ["'self'", "https:", "'unsafe-inline'"],
>             baseUri: ["'self'"],
>             fontSrc: ["'self'", "https:", "data:"]
>         }
>     }
> }));

thanks , it work for me too

**Comment by Coinhexa** [comment]
```
app.use(
  helmet({
    contentSecurityPolicy: {
      directives: {
        scriptSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
      },
    },
  }),
);
```
The only directive that you actually need to modify is scriptSrc as the default values for the other directives are the same as what @t1nky mentioned in his [answer](https://github.com/SoftwareBrothers/adminjs/issues/607#issuecomment-693621747)

**Comment by Elyasnz** [comment]
any updates!?
