### ISSUE TITLE
Custom action with type record redirect to 404

### ISSUE THREAD

**Issue by hannyudayana** [SoftwareBrothers/adminjs#609]
I think I found a bug on the implementation of custom action and isAccessible property. Below is my custom action declaration:

```
approval: {
  actionType: 'record',
  label: 'Approval',
  icon: 'fas fa-exclamation',
  component: AdminBro.bundle('../components/approval'),
  handler: async (request, response, data) => {
    return {
      record: {
        ...data.record.toJSON(),
      }
    }
  },
  isAccessible: ({ currentAdmin }) => currentAdmin && (currentAdmin.role_group == 'SUPERADMIN'),
},
```
When I tried logging in with a user that is not a superadmin, the behavior is correct. Action Approval is not shown.

But when I logged in using superadmin, the action is shown, but when I clicked on it, it shows 404 page.
![image](https://user-images.githubusercontent.com/12790369/93628331-98e84100-fa10-11ea-98f8-d660d39b9d5b.png)

Versions:
"admin-bro": "^3.0.1",
"admin-bro-expressjs": "^2.1.1",
"admin-bro-sequelizejs": "^0.5.1",

Any help will be appreciated. Cheers

**Comment by wojtek-krysiak** [comment]
it looks like your action is not there. Can you paste content of `REDUX_STATE` from the chrome terminal? (your resource from `resources` array)

**Comment by hannyudayana** [comment]
You mean this one?
```
{
  "options": {
    "properties": {
      "id": {
        "isVisible": false
      },
      "created_by": {
        "isVisible": false
      },
      "updated_by": {
        "isVisible": false
      },
      "created_at": {
        "isVisible": false
      },
      "updated_at": {
        "isVisible": false
      }
    },
    "listProperties": [
      "account_name",
      "account_number",
      "bank_id",
      "city_id",
      "amount",
      "status"
    ],
    "editProperties": [
      "account_name",
      "account_number",
      "bank_id",
      "city_id",
      "amount"
    ],
    "parent": {
      "name": "Revenue Management"
    },
    "name": "Withdrawal",
    "actions": {
      "show": {},
      "new": {},
      "edit": {},
      "delete": {},
      "list": {},
      "bulkDelete": {},
      "approval": {
        "actionType": "record",
        "label": "Approval",
        "icon": "fas fa-exclamation",
        "component": "Component25"
      }
    },
    "sort": {
      "direction": "desc",
      "sortBy": "created_at"
    }
  }
}
```

**Comment by wojtek-krysiak** [comment]
yes, this one. But the action is there :(. what is the url when you click on it? and did you try to update admin to the latest version?

**Comment by hannyudayana** [comment]
This is the url:
```
/cms/resources/withdrawal/records/d53dd443-8345-4dd5-b5d4-aee2c04cff87/approval
```

Let me try updating to the latest version. Let's see if it resolves the problem

**Comment by hannyudayana** [comment]
I tried to update admin-bro to the latest version, but I got an error instead
```
WARN EINVAL: invalid argument, futime
```
Any idea why?
