### ISSUE TITLE
AdminBroFeature for Slate.js 

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/adminjs#654]
**Describe the problem feature solves**

* Right now we use quill which have problematic React interface - which has to be better documented. 
* We will probably reuse editor a loot so it would be good to have a better alternative
* Slate.js seems to be better integrated with React

**Describe the solution you'd like**

* Implement AdmniBroFeature integrating slate.js with AdmibBro
* this can be done simultaneously to the current quill integration (no breaking changes)

**Describe alternatives you've considered**

* change quill to slate.js in design system

**Comment by ariansobczak-rst** [comment]
Resolved in https://github.com/SoftwareBrothers/adminjs/pull/1059
