### ISSUE TITLE
Describe a standard for writing admin-bro packages

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/adminjs#660]
**Describe the problem feature solves**
Since the creating of Features theare are more packagages coming to the ecosystem. It would be good to have a standard defining how to write them / how to structure files inside

**Describe the solution you'd like**
* admin-bro-extension-template project with the description/requirements:
** where to put files: src / components / tests
** how to structure src folder
** which linter rules should be used.
** how to deploy the feature
** common scripts in package.json
** which testing library should we use
** tsconfig template

**Comment by krzysztofstudniarek** [comment]
We got contributing.md file which describe this
