### ISSUE TITLE
AdminBro behind a reverse proxy server?

### ISSUE THREAD

**Issue by lovebhardwaj** [SoftwareBrothers/adminjs#674]
Hi, 

I have been trying to find it but I am unable to find anything regarding running AdminBro behind a proxy server. Currently, I am running AdminBro NodeJS server behind an Nginx reverse proxy server(traffic from `https://example.com/test-server` routing to the NodeJS server). My root path for AdminBro is /admin. When I go to `https://example.com/test-server/admin` I get the following errors in the browser console: 

`GET https://example.com/test-server/admin/frontend/assets/app.bundle.js net::ERR_ABORTED 404 (Not Found)`

Could you please help me figure out what's happening or what wrong am I doing?

It works on my local matching under `http://localhost:5000/admin`.

**Comment by ayushbhat** [comment]
Can you paste your Nginx config file here?

**Comment by lovebhardwaj** [comment]
This is the server block for the particular NodeJS server:

```
	location ^~ /sparkstaging/api/ {
               proxy_pass http://localhost:9002/;
               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection 'upgrade';
               proxy_set_header Host $host;
               proxy_cache_bypass $http_upgrade;
        }
```

**Comment by wojtek-krysiak** [comment]
you will have to change rootPath to test-server/admin. take a look at the source code of the express plugin to see how it resolves paths

**Comment by lovebhardwaj** [comment]
So my NodeJS server is running with a base URL of `www.example.com/sparkstaging/api/` behind Nginx. In admin bro options I have the `rootPath: "/database"` and `loginPath: "/databaselogin"`. Everytime I go to `www.example.com/sparkstaging/api/database` I am routed to `www.example.com/databaselogin` which results in 404.

**Comment by in-live-md** [comment]
I get around these reverse proxy issues by creating a separate app (using nest easily done within the same webapp). So it gets its own port for adminbro.. keeping the incoming app path the same as the downstream app prevents those kind of issues that usually require some rewrite rules.
```
location /adminbro {
                proxy_pass    http://localhost:3005/adminbro;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_cache_bypass $http_upgrade;
        }
```
