### ISSUE TITLE
White screen when use helmet()

### ISSUE THREAD

**Issue by azjustin1** [SoftwareBrothers/adminjs#679]
**Describe the bug**

**Installed libraries and their versions**

* admin-bro@2.0.1
* admin-bro-expressjs@2.0.0
* admin-bro-mongoose@1.4.0
... mongo, express (whatever you think is relevant)

**To Reproduce**

**Expected behavior**

**Screenshots**

**AdminBroOptions with schema**
Paste your AdminBro config with database schema if it could be related to the issue

**Desktop (please complete the following information if relevant):**

**Smartphone (please complete the following information if relevant):**

**Additional context**

**Comment by nejos97** [comment]
Good evening, I had the same problem I still can't debug anyone to find a solution?

**Comment by nejos97** [comment]
![Screenshot from 2020-11-21 17-08-31](https://user-images.githubusercontent.com/13876543/99881813-35e77600-2c1c-11eb-980f-beb04e07e78d.png)

**Comment by k-efimov** [comment]
Have the same problem while development. On staging all is fine.
![image](https://user-images.githubusercontent.com/45761312/100754365-13afde00-33fc-11eb-997c-4c0912979e46.png)

**Comment by rauleb** [comment]
there is a workaround in the #607 https://github.com/SoftwareBrothers/adminjs/issues/607#issuecomment-693621747

**Comment by behrozkiaei** [comment]
and i have the same problem too

**Comment by behrozkiaei** [comment]
i opened contentSecurityPolicy and it worked . 
 app.use(
      helmet({
        contentSecurityPolicy: false,
        crossOriginEmbedderPolicy: true,
        crossOriginOpenerPolicy: true,
        crossOriginResourcePolicy:true,
        dnsPrefetchControl:true,
        frameguard:true,
        hsts:true,
        ieNoOpen:true,
        noSniff:true,
        referrerPolicy:true,
        xssFilter:true,
      })
    );
