### ISSUE TITLE
Heroku demonstration link is offline

### ISSUE THREAD

**Issue by dayvsonsales** [SoftwareBrothers/adminjs#684]
The example link hosted on Heroku (https://admin-bro-example-app-staging.herokuapp.com/admin) is broken:

![Screen Shot 2020-11-14 at 10 16 24](https://user-images.githubusercontent.com/5778467/99147833-c218fc80-2662-11eb-80ce-26774814c19e.png)

**Comment by dziraf** [comment]
Hi, the example app is now hosted using firebase functions but it seems readme hasn't been updated yet...

URL: https://admin-bro-app.firebaseapp.com/admin
Credentials: `admin@example.com` / `password`

I'll leave the issue opened until Readme is updated

**Comment by dayvsonsales** [comment]
Thank you. So, should I make a pull request or you guys are planning to do so?

**Comment by dayvsonsales** [comment]
@dziraf Thank you. So, should I make a pull request or you guys are planning to do so? Btw, there's a problem with listing Media in the example (it returns an HTTP 500 error).

**Comment by mcgouganp** [comment]
Just of note, it's not just the README, the AdminBro website demo link is still using the broken heroku link too.
![image](https://user-images.githubusercontent.com/1724689/100814344-34744400-348d-11eb-8255-9bb224a838c7.png)
