### ISSUE TITLE
Prisma Database Adapter

### ISSUE THREAD

**Issue by ayush-goyal** [SoftwareBrothers/adminjs#720]
**Describe the problem feature solves**

It would be great if there could be a database adapter for Prisma.

**Describe the solution you'd like**

Creating a new database adapter to interface with Prisma.

**Describe alternatives you've considered**

There already exist other adapters, but including one for Prisma would allow more developers to use this library.

**Acceptance criteria**
List of checkpoints which has to be met to mark the issue as completed

Creating a new adapter.

**Comment by PrimeDominus** [comment]
Would love to have this. Prisma is awesome.

**Comment by yorch** [comment]
+1
Been working with Prisma and it's just amazing

Any plans on integrating it?

**Comment by dziraf** [comment]
The v1.0.0 of the adapter has been published: https://www.npmjs.com/package/@adminjs/prisma
