### ISSUE TITLE
404 error for https://softwarebrothers.github.io/tutorial-installation-instructions.html

### ISSUE THREAD

**Issue by googol7** [SoftwareBrothers/adminjs#725]
All "Get started" buttons on the page https://softwarebrothers.github.io/admin-bro-dev/ link to https://softwarebrothers.github.io/tutorial-installation-instructions.html and this link is (currently) broken. It displays a 404 error.

![Bildschirmfoto 2020-12-30 um 17 43 07](https://user-images.githubusercontent.com/282412/103367995-c12f1380-4ac6-11eb-81ac-1e08c711bb73.png)

The demo also doesn’t work. There already exist a separate [issue](https://github.com/SoftwareBrothers/admin-bro/issues/722).

**Comment by dziraf** [comment]
The landing page and documentation is now updated
