### ISSUE TITLE
Add cancel button when adding/editing resource.

### ISSUE THREAD

**Issue by SimonB407** [SoftwareBrothers/adminjs#732]
**Describe the problem feature solves**
From UI perspective back button is not equal to cancel button. User might be confused what behavior to expect when clicking back button. Optional cancel button (set by action options, off by default) might be good solution.

**Describe the solution you'd like**
On the bottom of resource add/edit action near `save` button, there is `cancel` button which behaves the same as cancel.

**Describe alternatives you've considered**
It is possible to add that button on my own, by doing custom action component, but it is a lot of work for one button to add. Maybe solution could be more flexible, like adding option to do custom footer for add/edit action, so not whole action override is required.

**Comment by krzysztofstudniarek** [comment]
Won't do for now
