### ISSUE TITLE
Buttons to go to the last/first page

### ISSUE THREAD

**Issue by asimaranov** [SoftwareBrothers/adminjs#734]
It's inconvenient to go to the last page, if pages count is very big. I have to calculate the last page id, and insert it to the `page` get parameter. I think it would be very useful to add buttons to go to the last/first page, or display the last page in pages list like in react-admin 
![image](https://user-images.githubusercontent.com/25568730/104349428-f6e6ea00-5513-11eb-9167-e8a35a49c411.png)

**Comment by dziraf** [comment]
This is already implemented
