### ISSUE TITLE
Hiding resources

### ISSUE THREAD

**Issue by SimonB407** [SoftwareBrothers/adminjs#749]
**Describe the problem feature solves**
Sometimes admin requires you to have resource which is referenced in other resource, but I don't want to give availability to enter that resource page. Hiding resource from sidebar would be awesome.

**Describe the solution you'd like**
Adding option `isVisible: boolean` to resourceOptions.

**Describe alternatives you've considered**
You could do custom component for sidebar, but it's a bit overkill for such a simple function.

**Acceptance criteria**
- resource is not visible in sidebar
- resource records can be clickable through a reference in other record (optional, maybe even configurable)
- references work and populating other records should be working like now.

**Comment by CarlosFandango** [comment]
+1

**Comment by dominik992** [comment]
I see that this wasn't added to the new adminjs. Is there a way to hide it in adminjs?

**Comment by dziraf** [comment]
@dominik992 This is released through `beta` channel in `admin-bro@4.0.0-beta.3` release. I'll try to to push beta to master sometime next week (Monday/Tuesday?) so this should be a part of `adminjs@5.1.0` soon

**Comment by dominik992** [comment]
Is there a way to fix it before the merge?

**Comment by mokshmodi96** [comment]
For People still using AdminBro, if you set isAccessible to false for all actions

**Comment by gsusmonzon** [comment]
In case you missed the comment from @monkbroc , this worked for us: 

```js
{
  resource: MyResource,
  options: { navigation: false },
},
```

**Comment by udayanss** [comment]
Is there any way i can hide action edit/add for a particular resource?

**Comment by O-Q** [comment]
> Is there any way i can hide action edit/add for a particular resource?
```
const adminOptions: AdminJSOptions = {
    resources: [
      {
        resource: User,
        options: {
          actions: {
            new: {
              isVisible: false
            },
            edit: {
              isVisible: false
            }
          }
        }
      }
    ] satisfies ResourceWithOptions[],
    ...
    };
   ```
