### ISSUE TITLE
Missing Serverless documentation for CDN files

### ISSUE THREAD

**Issue by kkarimi** [SoftwareBrothers/adminjs#754]
I am trying to use the admin-bro with an AWS serverless application, I can see the recommended approach is to use `assetsCDN` to look up where the JS files exist, but it's not clear where to get those from?
In my `node_modules/admin-bro/lib/frontend/assets/` I have found:
```
├── scripts
│   ├── app-bundle.development.js
│   ├── app-bundle.production.js
│   ├── global-bundle.development.js
│   └── global-bundle.production.js
```
but when I access the `/admin` it seems like the HTML file requests:

```
     <script src="https://mycdn.cloudfront.net/global.bundle.js?date=1612360208109"></script>
      <script src="https://mycdn.cloudfront.net/design-system.bundle.js?date=1612360208109"></script>
      <script src="https://mycdn.cloudfront.net/app.bundle.js?date=1612360208109"></script>
      <script src="https://mycdn.cloudfront.net/components.bundle.js?date=1612360208109"></script>
```

I am sure there is a method to get these to put in my CDN but I cannot find any documentation to find them, can you please help?

Thanks

**Comment by talkl** [comment]
@kkarimi https://adminbro.com/module-@admin-bro_firebase-functions.html

also here is my gist:

https://gist.github.com/talkl/2b11dc31f2c90a72218d07c8a6e30219
