### ISSUE TITLE
design-system.bundle.js is large (25M) is rejected fastly cdn

### ISSUE THREAD

**Issue by in-live-md** [SoftwareBrothers/adminjs#755]
**Describe the bug**
Thanks for you tool its very well done. Our prod site is delivered by fastly which cant load design-system.bundle.js, proxy complains with a 503 (limit for fastly is 20M)

**Installed libraries and their versions**
    "@admin-bro/express": "3.1.0",
    "@admin-bro/nestjs": "1.0.0",
    "@admin-bro/typeorm": "^.4.0",

**To Reproduce**
Load admin bro on a site or downstream from a proxy that limits payload size to be < 25M
observed 503 http  code  (from our provider) and blank page 

**Expected behavior**
I expected admin panel to load. We do have a workaround to bypass fastly which is fine for us. I mainly wanted to point this out for others - and also see if there is a way to get that bundle size down.

**Comment by wjljack** [comment]
use `NODE_ENV=production`
in pm2 
`NODE_ENV=production pm2 restart web-interface --update-env`
