### ISSUE TITLE
Selecting dates on a Date field won't work on Safari

### ISSUE THREAD

**Issue by brickpop** [SoftwareBrothers/adminjs#761]
The date and time picker will work on Firefox / Chromium browsers, but will have no effect when used from Safari.

**Installed libraries and their versions**

* admin-bro@3.3.1
* admin-bro-expressjs@3.0.1
* admin-bro-mongoose@1.1.0

**To Reproduce**
Set a Date field like so:

```js
export const ProductSchema = new mongoose.Schema<IProductDocument>({
        // ...
	visibleAfter: { type: Date, default: Date.now },
        // ...
})
```

```js
const options: ResourceOptions = {
        // ...
        visibleAfter: { position: 2, props: { placeholder: "(date after which the product becomes visible, by default: now)" } },
        // ...
}
```

- Create a new item, or edit an existing one
- Click the blue button of the date field to open the calendar
- Select a date (nothing will happen, no error on the console)

**Expected behavior**
Selecting a date should update the value in the box and the time picker should also be rendered with the same components as the rest of browsers.

**Screenshots**
<img width="895" alt="img" src="https://user-images.githubusercontent.com/4456749/107156198-44247300-697d-11eb-8d1b-1f6c25fa1e6d.png">

**AdminBroOptions with schema**
Paste your AdminBro config with database schema if it could be related to the issue

**Desktop**
 - OS: MacOS Big Sur
 - Browser: Safari
 - Version 14.0.2

**Comment by bhoodream** [comment]
The same problem

https://user-images.githubusercontent.com/1740470/109499827-f6a4ad00-7ac7-11eb-97db-e9f373a8190f.mov

"admin-bro": "3.3.1",
"@admin-bro/express": "3.0.1"

Safari: 14.0.3 
macOS: 10.15.7
