### ISSUE TITLE
Retain the pagination state after editing

### ISSUE THREAD

**Issue by Gr8z** [SoftwareBrothers/adminjs#770]
When you edit a record in the admin panel, either in the drawer or on a new page. After saving the record, it redirects the page to the first page of the resource list. 

If you are on page 5, after editing something there, you will be redirected back to page 1. 

Would be nice if there was a way to retain the pagination state and redirect to the page where you came from. It will be a much better user experience when editing mass records.

**Comment by Whitelion2021** [comment]
I am going through same issue is there any possible solution to this.

**Comment by dziraf** [comment]
This should be available in one of the recent adminjs versions

**Comment by ZeroCho** [comment]
Hello, I think it's not working in current version(7.5.10). Could you please check again?
