### ISSUE TITLE
Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by maheshkumar2150** [SoftwareBrothers/adminjs#772]
Do i have to install tslib separately? 
It is windows 10

{
  "name": "admin",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@admin-bro/express": "^3.1.0",
    "@admin-bro/mongoose": "^1.1.0",
    "admin-bro": "^3.4.0",
    "express": "^4.17.1",
    "express-formidable": "^1.2.0",
    "mongoose": "^5.11.17"
  }
}

**Comment by fahimhoque** [comment]
happened to me.

Just installed tslib and it resolved the issue ->   npm install tslib

**Comment by darkmavis1980** [comment]
But this shouldn't happen, you either tell it in the documentation that you have to manually install this library, or you put it as a peerdependency.

**Comment by vikram-ray** [comment]
Still got the issue with "@adminjs/express"
