### ISSUE TITLE
Double scroll on chromium browsers

### ISSUE THREAD

**Issue by brickpop** [SoftwareBrothers/adminjs#773]
**Describe the bug**
When entering a page taller than the screen (edit, show, etc) double scrolling happens. 

The bottom of the body scrolls all the way up, leading to an almost blank page. 

**Installed libraries and their versions**
- "admin-bro": "^3.3.1"

**To Reproduce**
1. Go to the page of a record (edit, for example)
2. Scroll all the way down with inertia
3. Even if at the bottom, continue scrolling down
4. The body goes away

**Expected behavior**
The main body of the page should be fixed. Only the inner components should be scrollable.

**Screenshots**
<img width="1104" alt="double-scroll" src="https://user-images.githubusercontent.com/4456749/108751409-74097400-7542-11eb-9412-0449d2cac001.png">

**Desktop**
 - OS: MacOS, iPad, Linux, ...
 - Browser Chromium, Safari, Brave

---
BTW, thank you for such a great project!

**Comment by dhruvil2111** [comment]
Facing same issue

**Comment by dziraf** [comment]
Hi, do you have a checkbox on these pages?

**Comment by brickpop** [comment]
Yes, we do have a checkbox :+1:

**Comment by mokshmodi96** [comment]
I have `"@admin-bro/design-system": "1.7.3"` and `"admin-bro": "^4.0.1"` but issue still persists, is it solved in this version?
