### ISSUE TITLE
"type": "module" breaks dashboard paths

### ISSUE THREAD

**Issue by kurzai** [SoftwareBrothers/adminjs#781]
**Describe the bug**
Putting "type": "module" on any node version >= 10 gives a 

**Installed libraries and their versions**

@admin-bro/design-system@1.7.2
@admin-bro/express@3.1.0
admin-bro@3.4
esm@3.2.25
express@4.17.1
express-formidable@1.2.0
react-dom@16.14.0
tslib@2.1.0

**To Reproduce**
Linux Ubuntu 20.04
NodeJS > 10 (tested 11-15)
Use import statements and put "type": "module" in your package.json
(You can use import statements with the esm module just fine, it only breaks when putting the type to module)
Just a very basic adminbro, express setup. Make an example "dashboard" component with minimal content.

**Expected behavior**
For there not to be an error message and for the dashboard component to render

**Error message**
```
/home/user/..my stuff../admin-panel/node_modules/admin-bro/lib/admin-bro.js:320
      throw new _configurationError.default(`Given file "${src}", doesn't exist.`, 'AdminBro.html');
            ^

ConfigurationError: 
    Given file "./components/dashboard", doesn't exist.
    More information can be found at: https://adminbro.com/AdminBro.html
    
    at Function.bundle (/home/user/..my stuff..admin-panel/node_modules/admin-bro/lib/admin-bro.js:320:13)
    at file:///home/user/..my stuff../admin-panel/admin/index.js:11:23
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
npm ERR! code 1
npm ERR! path /home/user/..my stuff../admin-panel
npm ERR! command failed
npm ERR! command sh -c node ./express/index.js
```

**What I found out**
I went to the bundle function and looked at the line that the error message was giving me (node_modules/admin-bro/lib/admin-bro.js:320:13). I printed out some debugging information and the filePath that was supposed to point to the dashboard component looked like this:
`file:/home/user/..my stuff../admin-panel/admin/components/dashboard`
I tried it without the es6 import statements and used good old require and removed the "type": "module" from my package.json. Then the filePath it gave me was this one:
`/home/user/..my stuff../admin-panel/admin/components/dashboard`
which seems way more appropiate. So when I console logged some variables from a couple lines above I realized that it was probably coming from the execution path given for nodejs >= 10 which is:
`file:///home/user/..my stuff../admin-panel/index.js`
and hence my suspision that this is some kind of regex or path error.
So the only time is doesnt work is if you put "type": "module" in the package.json, otherwise it works. When I removed the "file:" from the fileName it did compile but when I opened it on my localhost it gave me another error, this time on the frontend that the ".entry.js" in the ".admin-bro" folder was broken and it gave me another broken path. So I figured I'd give you guys a heads up since I'm not familiar with the code base and don't know where are all the paths are to fix. :)

**Comment by jedashford** [comment]
We're experiencing this too. Paths broken when using esm modules instead of commonjs. Anyone have a workaround? We'd likely need to fork the project to fix the paths.

**Comment by CherryDT** [comment]
@dziraf This still happens for me on latest version 5.10.0.
