### ISSUE TITLE
Datetimepicker dateformat changing

### ISSUE THREAD

**Issue by elifoz** [SoftwareBrothers/adminjs#794]
Hi! I want to change dateformat  tried but it didnt work. I want to format 'yyyy/dd/mm' but  cant find Where I should change  this property,thanks for  help!

**Comment by dziraf** [comment]
You can try this:
```
properties: {
  myDateProperty: {
    props: { dateFormat: 'yyyy/dd/MM' }
  }
}
```
althought I haven't tested that.
