### ISSUE TITLE
Update bulkDelete ActionRequest API docs

### ISSUE THREAD

**Issue by ManuelSosaMartinez** [SoftwareBrothers/adminjs#801]
As we can see [here](https://adminbro.com/Action.html#ActionRequest)  , documentation for ActionRequest states that, on a bulkDelete action, selected record ids are stored in
   " request.params.recordIds "
However, selected record ids are stored in 
   " request.query.recordIds "

Sorry for annoying with such a small issue !

**Comment by krzysztofstudniarek** [comment]
We're rewriting the documentation. This shouldn't be an issue in the new doc ;)
