### ISSUE TITLE
Sequelize problems

### ISSUE THREAD

**Issue by codecrusher84** [SoftwareBrothers/adminjs#814]
Sequelize new/List requests do not work on your demo as well as on my local test app...

Tested Demo Link:
https://admin-bro-example-app-staging.herokuapp.com/admin

Screenshots:
<img width="1430" alt="Screen Shot 2021-04-13 at 11 30 17 AM" src="https://user-images.githubusercontent.com/56540325/114539374-bc950200-9c54-11eb-9574-c89c69332cb1.png">

<img width="1425" alt="Screen Shot 2021-04-13 at 11 46 43 AM" src="https://user-images.githubusercontent.com/56540325/114539440-cc144b00-9c54-11eb-98ea-bd5f6d0e0ed0.png">

**Comment by dziraf** [comment]
What's being logged in server's console when the error occurs? I'm using Sequelize in a project currently but there are no errors appearing in lists
