### ISSUE TITLE
Stored Cross Site Scripting

### ISSUE THREAD

**Issue by shubhambhartiya08** [SoftwareBrothers/adminjs#824]
Hi there,

Kindly guide us on how to resolve this.
![storedxss4](https://user-images.githubusercontent.com/31841628/116209678-c728be80-a75f-11eb-8649-73f3511ae9d4.png)
![storedxss2 (1)](https://user-images.githubusercontent.com/31841628/116209689-c8f28200-a75f-11eb-8a53-424804112154.png)
![storedxss3](https://user-images.githubusercontent.com/31841628/116209694-ca23af00-a75f-11eb-8437-ca3eedcff486.png)
![storedxss1](https://user-images.githubusercontent.com/31841628/116209700-cb54dc00-a75f-11eb-95ca-39c49e6ca4d9.png)

**Comment by dziraf** [comment]
Closing because the issue is old. If you still need help, please reopen.
