### ISSUE TITLE
Getting a bunch of types error after setting admin-bro with a Nestjs application. 

### ISSUE THREAD

**Issue by DevArifHossain** [SoftwareBrothers/adminjs#833]
**Installed libraries and their versions**

* admin-bro@4.0.1
* admin-bro-expressjs@2.1.1
* nestjs/core@7.0.0

**Screenshots**
![Screenshot from 2021-05-01 13-19-51](https://user-images.githubusercontent.com/43506814/116774672-04eb5700-aa80-11eb-9e81-1219b3b45848.png)

**Comment by yaroslavyal** [comment]
I had the same issue. Resolved with property `skipLibCheck": true` in my tsconfig file
