### ISSUE TITLE
Compilation error when using with Typescript

### ISSUE THREAD

**Issue by alesanchezr** [SoftwareBrothers/adminjs#834]
**Describe the bug**

I created [this repository for easy error replication](https://github.com/4GeeksAcademy/expressjs-rest-hello/tree/typescript/error).

When running `npm run build` (typescript compilation) I get this error:

```bash
Could not find a declaration file for module 'styled-components'. '/workspace/expressjs-rest-hello/node_modules/styled-components/dist/styled-components.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/styled-components` if it exists or add a new declaration (.d.ts) file containing `declare module 'styled-components';`
```

I think the problem is typescript tries to compile the whole AdminBro library again and when It finds the front-end end code and some other packages it does not know how to do it.

I wonder if I can tell typescript to ignore admin-bro.

**Installed libraries and their versions**

```json
  "dependencies": {
    "body-parser": "^1.19.0",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-async-errors": "^3.1.1",
    "jsonwebtoken": "^8.5.1",
    "morgan": "^1.10.0",
    "node-env-file": "^0.1.8",
    "pg": "^8.6.0",
    "reflect-metadata": "^0.1.13",
    "tsc-watch": "^4.2.9",
    "typeorm": "^0.2.32"
  },
  "devDependencies": {
    "@admin-bro/express": "^3.1.0",
    "@admin-bro/typeorm": "^1.4.0",
    "@types/cors": "^2.8.10",
    "@types/express": "^4.17.11",
    "@types/express-list-endpoints": "^4.0.1",
    "@types/flat": "^5.0.1",
    "@types/morgan": "^1.9.2",
    "@types/node": "^14.14.37",
    "@types/react-redux": "^7.1.16",
    "@types/styled-system": "^5.1.11",
    "admin-bro": "^4.0.1",
    "admin-bro-typeorm": "^0.1.6-alpha.9",
    "express-formidable": "^1.2.0",
    "express-list-endpoints": "^5.0.0",
    "express-session": "^1.17.1",
    "nodemon": "^2.0.7",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.3"
  }
```

**To Reproduce**
1. Clone [this repo](https://github.com/4GeeksAcademy/expressjs-rest-hello/tree/typescript/error)
2. npm install
3. npm run build

**Expected behavior**
Successfully compilation like when you type `npm run start`

**Screenshots**
https://recordit.co/OvJSLPbkZ1

**AdminBroOptions with schema**
AdminBro schema and options are fine, the app works when compiled for development.

**Additional context**
I'm no expert in typescript.

**Comment by dziraf** [comment]
You can add `skipLibCheck: true` to your tsconfig to ignore libraries type checks

**Comment by MoSattler** [comment]
@dziraf I did that, but then my production build does not work
> NoResourceAdapterError: There are no adapters supporting one of the resource you provided

even though it worked fine in development (with TS-Node)
