### ISSUE TITLE
Many-to-many support

### ISSUE THREAD

**Issue by sdepold** [SoftwareBrothers/adminjs#843]
First of all,

let me congratulate you for an amazing piece of software. It's extremely useful and well designed :)

**Describe the problem feature solves**
Using Sequelize, I'm defining a many-to-many relationship like this:

```
Tag.belongsToMany(Wishlist, { through: TagWishlistReference });
```

So this thing is building the bridge between a Tag and a Wishlist.

Heading to the Create screen for TagWishlistReference, I only get an empty form that contains only a Save button.

**Describe the solution you'd like**
I'd like to get 2 ID selectors, one for Tag and one for Wishlist just as it would be for manyToOne associations:

![image](https://user-images.githubusercontent.com/79163/118860878-2c457f00-b8dc-11eb-836f-15c900be2ac2.png)

**Describe alternatives you've considered**
I tried to integrate with https://gist.github.com/leibowitz/b94fc4eb2b8ab745267db99941757190 but couldn't get it to work.

**Acceptance criteria**
- I can select the Tag and the Wishlist
- I can create new entities of TagWishlistReference
- The same works when I edit a TagWishlistReference

**Comment by cett01** [comment]
any solutions or improvements?

**Comment by dziraf** [comment]
This isn't really a bug, you need
```
TagWishlistReference.belongsTo(Tag);
TagWishlistReference.belongsTo(Wishlist);
```
for it to work

**Comment by franka107** [comment]
I implemented an example, it is tested with typeorm and postgresql,
You can test this project quickly with VSC dev containers, the example is in the many-to-many relationship User <-> Role, to enter the admin is localhost:3000/admin

https://github.com/franka107/nestjs-adminjs-manytomany-example

![Screenshot from 2022-12-14 11-49-27](https://user-images.githubusercontent.com/49798546/207657280-83c4d672-25ca-4de7-80a9-5d3de6c7a502.png)
![Screenshot from 2022-12-14 11-49-56](https://user-images.githubusercontent.com/49798546/207657324-51af5e0d-e7ae-4e72-9865-c087a72b7180.png)
![Screenshot from 2022-12-14 11-50-06](https://user-images.githubusercontent.com/49798546/207657359-53757312-6528-4cb2-b56e-3f0092e13eda.png)

**Comment by AshotN** [comment]
@franka107 Is this something you plan on getting into the core of AdminJS?

**Comment by damian-balas** [comment]
@franka107 Awesome work! Thanks :)

**Comment by Inoir** [comment]
is this the recommendet way of implementing an many to many? @dziraf 
if so it may be worth taking the solution of @franka107 into the core of adminjs or provide some example of how to do this in "better" way. currently many to many is not working out of the box or needs some special handling i cant figure out.
currently it seems the implementation is adoptable to some generic many to many implementation

**Comment by ysavinkov** [comment]
> I implemented an example, it is tested with typeorm and postgresql, You can test this project quickly with VSC dev containers, the example is in the many-to-many relationship User <-> Role, to enter the admin is localhost:3000/admin
> 
> https://github.com/franka107/nestjs-adminjs-manytomany-example
> 
> ![Screenshot from 2022-12-14 11-49-27](https://user-images.githubusercontent.com/49798546/207657280-83c4d672-25ca-4de7-80a9-5d3de6c7a502.png) ![Screenshot from 2022-12-14 11-49-56](https://user-images.githubusercontent.com/49798546/207657324-51af5e0d-e7ae-4e72-9865-c087a72b7180.png) ![Screenshot from 2022-12-14 11-50-06](https://user-images.githubusercontent.com/49798546/207657359-53757312-6528-4cb2-b56e-3f0092e13eda.png)

can this be made using express + sequelize, or I have to rewrite the project with nest.js?

**Comment by lpbonomi** [comment]
There is now an official way to do this:

https://docs.adminjs.co/basics/features/relations
