### ISSUE TITLE
Unable to reorder properties in edit

### ISSUE THREAD

**Issue by dramikei** [SoftwareBrothers/adminjs#844]
Currently, properties cannot be reordered. If using virtual properties then they are placed at the very top followed by Model/Schema properties. This makes it very weird for the user and does not provide a good user experience. 

For example, the following `password` virtual Property would top rendered at the top of all the fields:

from [Role-Based Access Control](https://adminbro.com/tutorial-rbac.html):
```
const adminBro = new AdminBro({
  resources: [{
    resource: User,
    options: {
      properties: {
        encryptedPassword: {
          isVisible: false,
        },
        password: {
          type: 'string',
          isVisible: {
            list: false, edit: true, filter: false, show: false,
          },
        },
      },
      actions: {
        new: {
          before: async (request) => {
            if(request.payload.password) {
              request.payload = {
                ...request.payload,
                encryptedPassword: await bcrypt.hash(request.payload.password, 10),
                password: undefined,
              }
            }
            return request
          },
        }
      }
    }
  }],
  rootPath: '/admin',
})
```

One way to reorder properties would be by using `listProperties` or `editProperties` but then features don't show up (#581)

**Comment by dziraf** [comment]
You should be able to assign `position` to properties if you don't want to use `listProperties`/`editProperties`
