### ISSUE TITLE
AdminBro can't provide async model getters as params

### ISSUE THREAD

**Issue by dortonway** [SoftwareBrothers/adminjs#845]
**Describe the bug**

AdminBro can't provide async model getters as params. So I can't use it in a component for the desired field. In the response, I see an empty object instead of the promise resolution of the getter field.

**Installed libraries and their versions**

admin-bro@^3.4.0
admin-bro/sequelize@^1.2.1

**To Reproduce**
1. Add getter to a sequelize model
2. Try to access it in "show" component

**Expected behavior**
I would like to see the promise resolution

**Comment by dziraf** [comment]
I don't think we'll be supporting async getters soon. We rely entirely on specific ORMs' `find` methods currently and if they don't resolve these, we won't be resolving them either in short time.

If you'd like to see this feature in a specific adapter, please create an issue there. This is not something we can easily implement for all adapters.
