### ISSUE TITLE
Documentation of `useRecord` contains misleading example

### ISSUE THREAD

**Issue by JohnRandom** [SoftwareBrothers/adminjs#851]
**Describe the bug**
The `useRecord` documentation reports that hooks are provided by the `@admin-bro/design-system` package, while they really are provided by the core `admin-bro` bundle.

**Installed libraries and their versions**
  * admin-bro@4.0.1

**Comment by dziraf** [comment]
Doesn't seem to be the case anymore: https://adminjs.co/useRecord.html 🤔
