### ISSUE TITLE
admin-bro for multiple-tenant system

### ISSUE THREAD

**Issue by htthao** [SoftwareBrothers/adminjs#859]
Hi,

I'm new to admin-bro. I want to build a dashboard for a multiple-tenant system, one database per tenant. However, I couldn't find any example for my case. Do you have any suggestions?
Thank you.

**Comment by dziraf** [comment]
You should be able to just pass multiple DB connections to AdminJS `databases` config in most cases but it's dependant on which adapter you're using since usage might be different.
