### ISSUE TITLE
Ошибка парсера тела при нажатии на панель администратора входа

### ISSUE THREAD

**Issue by Andrukva** [SoftwareBrothers/adminjs#860]
WrongArgumentError: 
  You probably used old `body-parser` middleware, which is not compatible
  with @admin-bro/express. In order to make it work you will have to
  1. move body-parser invocation after the admin bro setup like this:
  
  const adminBro = new AdminBro()
  const router = new buildRouter(adminBro)
  app.use(adminBro.options.rootPath, router)
  
  // body parser goes after the AdminBro router
  app.use(bodyParser())
  
  2. Upgrade body-parser to the latest version and use it like this:
  app.use(bodyParser.json())

**Comment by Andrukva** [comment]
How to solve this?

**Comment by rageroot** [comment]
![image](https://user-images.githubusercontent.com/69573621/122876880-ae432080-d33e-11eb-8697-8bf1f3e262eb.png)
Порядок поменяй, дословно же написано =)
------------------------------------------------------------------
Change the order, literally it is written =)
