### ISSUE TITLE
Uploaded file being stored in root of partition

### ISSUE THREAD

**Issue by abbasharoon** [SoftwareBrothers/adminjs#861]
**Describe the bug**
When using the upload module for locally stored file, AdminBro stores the file at the root of the disk/partition. e.g configs & results.
```
local: {
      bucket: 'public'
   }
``` 
Uploaded files get stored at `D:\public` while project is located and run at `d:\projects\project-name`

When an absolute path is provided e.g `bucket: path.join(__dirname, '/public')` then form submission on front-end throws an error:
```
Error: ENOENT: no such file or directory, mkdir 'D:\D:\projects\project-name\public`
```
Either AdminBro should create/use directory with reference to it's current folder or should expect an absolute path for input. Right now I have to include the whole hierarchy of the folders except for the partition symbol in order to get it to work. But it's gonna cause issue in production as it will require the paths to be updated. 

**Installed libraries and their versions**

* admin-bro@3.4.0
* @admin-bro/express@3.1.0
* admin-bro/sequelize@1.2.1
* admin-bro/upload@1.3.1

**To Reproduce**
Use the local storage snippet from here https://adminbro.com/module-@admin-bro_upload.html, try to upload files 
They will get uploaded with reference to the root folder and not the current working directory

**Comment by abbasharoon** [comment]
Same issue mentioned [here ](https://github.com/SoftwareBrothers/admin-bro-upload/issues/16#issue-786858993) on `admin-bro-upload` about half year ago and a pull request pending [here](https://github.com/SoftwareBrothers/admin-bro-upload/pull/24) for last 27 days with no response from authors for any of it. 

Authors might be busy but at least they should merge bug fixations made by contributors. Regretting all the time I spent on learning all the quarks of this, Strapi should have been my first choice.

**Comment by KABU09** [comment]
Hi, any chance of this getting merged? I'd really appreciate it.   @dziraf
