### ISSUE TITLE
Any way to pass filter query from list through to a custom action?

### ISSUE THREAD

**Issue by amethystdeceiver** [SoftwareBrothers/adminjs#863]
Hi and thank you for building this great tool.

I've created a custom export resource action to exports records to an xlsx file. So far it works for all records of a resource, but I need to enable admins to apply the same filters as in the list/search action.

(A bulk action doesn't seem to fit as it selects only the records from a single page.)

Is there any way to persist / pass through the list filter query to my custom action?

Thanks

**Comment by Gary235** [comment]
Hey there I don't know if I can help you, but I'm curious in how did you manage to export the data into an xlsx file, I'm having trouble to transform from a .csv to .xlsx
Would you like to show how did you make it?

**Comment by martin-snajdr** [comment]
Hi! I'd also be super interested in your approach, can you please share some details?

**Comment by dziraf** [comment]
> Is there any way to persist / pass through the list filter query to my custom action?

You would need to create a middleware which stores last visited urls somewhere in the user session, then you should be able to extract filters in your action
