### ISSUE TITLE
Foreign keys are not displayed when using TypeORM

### ISSUE THREAD

**Issue by riledv** [SoftwareBrothers/adminjs#864]
**Describe the bug**
Foreign key is stored but not displayed in adminbro.

**Installed libraries and their versions**
admin-bro@4.0.1
@admin-bro/express@3.1.0
@admin-bro/typeorm@1.4.0
@pg: 8.5.1

**To Reproduce:**
User.ts
```
import {
    Entity,
    Column,
    PrimaryGeneratedColumn,
    OneToMany,
    BaseEntity,
} from 'typeorm';
import { Tag } from 'entity/Tag';

@Entity()
export class User extends BaseEntity {
    @PrimaryGeneratedColumn()
    id!: number;

    @Column({ unique: true })
    email!: string;

    @Column()
    password!: string;

    @OneToMany(() => Tag, (tag) => tag.uid, {
        cascade: true,
    })
    tag?: Tag[];
}
```

Tag.ts
```
import { User } from 'entity/User';
import {
    Entity,
    Column,
    PrimaryGeneratedColumn,
    ManyToOne,
    BaseEntity,
} from 'typeorm';

@Entity()
export class Tag extends BaseEntity {
    @PrimaryGeneratedColumn()
    id!: string;

    @Column()
    key!: string;

    @Column()
    value!: string;

    @Column({ nullable: true })
    type!: string;

    @ManyToOne(() => User, (user) => user.tag)
    uid!: User;
}
```

**Expected behavior**
The foreign key should show up.

**Screenshots**
<img width="1792" alt="Снимок экрана 2021-06-24 в 22 04 22" src="https://user-images.githubusercontent.com/14239672/123319512-2aa15380-d539-11eb-9369-71c76f466ac1.png">
<img width="1792" alt="Снимок экрана 2021-06-24 в 22 05 32" src="https://user-images.githubusercontent.com/14239672/123319559-3725ac00-d539-11eb-9a82-709de2a89401.png">
<img width="1792" alt="Снимок экрана 2021-06-24 в 22 05 36" src="https://user-images.githubusercontent.com/14239672/123319564-39880600-d539-11eb-8fc1-cf15a0a2a912.png">

**AdminJSOptions with schema**
-

**Desktop:**
 - OS: MacOS 11.2.3
 - Browser: chrome
 - Version: 91.0.4472.106 (

**Additional context**

**TypeORM config**
module.exports = {
    type: 'postgres',
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    username: process.env.POSTGRES_USER,
    password: process.env.POSTGRES_PASSWORD,
    database: process.env.POSTGRES_DB,
    synchronize: true,
    entities: ['src/entity/**/*.ts'],
    migrations: ['src/migration/**/*.ts'],
    subscribers: ['src/subscriber/**/*.ts'],
    // logging: false,
    logging: 'all',
};

**Code for adding a record to the database**
```
async createUsers(params: CreateUserBody) {
        const user = new User();
        user.email = params.email;
        user.password = params.password;

        const platformTag = TagBuilder('platform', params.platform, 'string');
        const isActiveTag = TagBuilder('isActive', 'false', 'boolean');

        user.tag = [platformTag, isActiveTag];

        const userRepository = getRepository(User);

        return userRepository.save(user);
    }
```

```
function TagBuilder(key: string, value: string, type: string) {
    const tag = new Tag();
    tag.key = key;
    tag.value = value;
    tag.type = type;

    return tag;
}
```

**Init adminbro (app.ts)**
```
import 'reflect-metadata';
import express from 'express';
import cors from 'cors';
import { createConnection } from 'typeorm';
import { config } from 'constants/config';
import compression from 'compression';
import { errorHandler } from 'middlewares/errorHanlder';
import { errorLogger, requestLogger } from 'middlewares/logger';
import { Database, Resource } from '@admin-bro/typeorm';
import AdminBro from 'admin-bro';
import AdminBroExpress from '@admin-bro/express';
import { validate } from 'class-validator';
import { userRouter } from 'routes/userRouter';
import { correctJsonCheck } from 'middlewares/correctJsonCheck';
import { notFoundHandler } from 'middlewares/notFoundHandler';

const app = express();
const router = express.Router();

Resource.validate = validate;

createConnection()
    .then((connection) => {
        AdminBro.registerAdapter({ Database, Resource });

        const adminBro = new AdminBro({
            databases: [connection],
            rootPath: '/admin',
        });
        const routerAdmin = AdminBroExpress.buildRouter(adminBro);

        app.use(compression({ level: 6 }));
        app.use(express.json());
        app.use(cors({ origin: new RegExp(config.CORS_ORIGIN) }));
        app.use(cors());

        app.use(correctJsonCheck);

        app.use(requestLogger);
        app.use(adminBro.options.rootPath, routerAdmin);
        ...
        ...
        ...
```

**Comment by dziraf** [comment]
Either `RelationId` or `JoinColumn` decorators must be used for AdminJS to be able to retrieve correct metadata. It's also advised to use `Column` decorator with the actual foreign key. This is explained in typeorm adapter's readme.

**Comment by rluncasu** [comment]
@dziraf Happening to me too, column has @JoinColumn decorator
<img width="589" alt="Screenshot 2021-10-17 at 19 18 26" src="https://user-images.githubusercontent.com/7629986/137635912-1776c0a6-4803-48c7-b139-6be1f476d6d2.png">

**Comment by pzubar** [comment]
> @dziraf Happening to me too, column has @joincolumn decorator <img alt="Screenshot 2021-10-17 at 19 18 26" width="589" src="https://user-images.githubusercontent.com/7629986/137635912-1776c0a6-4803-48c7-b139-6be1f476d6d2.png">

@dziraf I am facing the same issue - did you have the luck to fix it? Thank you in advance!

**Comment by dziraf** [comment]
It is because you don't have `productId` with `@Column` decorator in your model. This is a working example:
```
@Entity('opinions')
export class Opinion extends BaseEntity implements OpinionData {
  @PrimaryColumn({ name: 'opinion_id', type: 'uuid' })
  public opinionId!: string;

  @Column({ name: 'author_id', type: 'uuid', nullable: false })
  public authorId!: string;

  @Column({ name: 'content', type: 'text', nullable: true })
  @IsString()
  @IsOptional()
  @MinLength(1)
  @MaxLength(280)
  public content!: string | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  public createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  public updatedAt!: Date | null;

  @ManyToOne((_type) => User)
  @JoinColumn({
    name: 'author_id',
  })
  public author!: User;
}
```
