### ISSUE TITLE
Bulk data insert feature for the CRUD

### ISSUE THREAD

**Issue by ram6696** [SoftwareBrothers/adminjs#865]
**Describe the problem feature solves**
Most people don't like inserting my data one by one if there are more data to insert into the table

**Describe the solution you'd like**
The solution would be to bring in the bulk data upload feature here so that we can insert all the data at once. 
- We can consider adding all the data to the excel sheet and upload the excel to feed the data
- Reading the excel file and running validation on each row, saving the valid row, returning back the errored row in different excel sheet can be a good addon

**Describe alternatives you've considered**

**Acceptance criteria**
- As a user, by logging in to the admin panel, Should be able to upload the sheet with the required columns and data
- Should validate the data sent according to the models defined
- Should insert the data if the data row is proper
- Should give back new error sheet with all the errored rows and reason for failure so that user can upload the error sheet again by correcting errored rows

**Comment by dziraf** [comment]
Related to https://github.com/SoftwareBrothers/adminjs/issues/349

**Comment by krzysztofstudniarek** [comment]
We do have [adminjs-import-export ](https://github.com/SoftwareBrothers/adminjs-import-export)lib which should do the trick here. If the functionality there is not sufficient, then please open the issue there :)

**Comment by beautyfree** [comment]
this lib adds records through multiple db queries, is there a way to do it really bulk?
