### ISSUE TITLE
Documentation link in Readme doesn't work

### ISSUE THREAD

**Issue by musikele** [SoftwareBrothers/adminjs#866]
**Describe the bug**
Documentation link in Readme.md doesn't work 

**To Reproduce**
1. Go to https://github.com/SoftwareBrothers/adminjs/
2. Go to "Check out the documentation"
3. Click on "documentation" 

**Expected behavior**
I'd like to see the docs 

**Screenshots**
![image](https://user-images.githubusercontent.com/2239793/123394053-011b1300-d59f-11eb-91af-16dbb63ecfe1.png)

**Comment by TheRakeshPurohit** [comment]
No Conflicts, ready to merge PR https://github.com/SoftwareBrothers/adminjs/pull/870
