### ISSUE TITLE
How can i add RBAC ?

### ISSUE THREAD

**Issue by WorkImp** [SoftwareBrothers/adminjs#881]
I have to categorize 2 types of users, one is admin and others are normal users, where admin will have access more then the normal user, how can I define these two roles ?

**Comment by dziraf** [comment]
You define roles in your models. If you want to restrict access to some resources you can use `isAccessible` in action settings, if you want to filter out list records based on the role, you can do this by passing filters in list action's `before` hook. However, you might have to write your own list handler if the logic is more complex
