### ISSUE TITLE
Property 'env' does not exist on type 'typeof AdminJS'

### ISSUE THREAD

**Issue by malinowskil123** [SoftwareBrothers/adminjs#882]
Typing issue with `env` property on the AdminJS object when referencing it in a react TSX file.

**Comment by dziraf** [comment]
Frontend envs should be available via `window.AdminJS.env.<env property>`

**Comment by malinowskil123** [comment]
@dziraf I just tried that and typescript is throwing  this error `Property 'NODE_ENV' does not exist on type 'Number'`, I don't get any errors when I use `process.env` so it leads me to believe there  is a typing issue with `window.AdminsJS.env`.

**Comment by malinowskil123** [comment]
<img width="749" alt="Screen Shot 2021-07-19 at 12 38 30 PM" src="https://user-images.githubusercontent.com/48255282/126195721-b6da4678-c46f-4797-83c2-f9b9eca5ec5d.png">

**Comment by malinowskil123** [comment]
@dziraf  why is`env` type coming up as a `Number`?
