### ISSUE TITLE
changing password and login

### ISSUE THREAD

**Issue by NagievR** [SoftwareBrothers/adminjs#886]
How can I change the password or login in adminbro? 
I tried to find the information about it in the documentation but there are no answers.
I`m using action.new.before hook.

`      actions: {
        new: {
          before: async(req) => {
            if (req.payload.password) {
              req.payload = {
                ...req.payload,
                passHashed: await bcrypt.hash(req.payload.password, 8),
                password: null
              };
            }
            return req;
          },
        },
      }`

**Comment by sharifpour** [comment]
You will need to customize the edit action (exactly like you did for new).
You can use the edit property exactly how you did for the new.
[https://adminbro.com/module-EditAction.html](https://adminbro.com/module-EditAction.html)
