### ISSUE TITLE
window.AdminJS.env is being evaluated as a `Number` type

### ISSUE THREAD

**Issue by malinowskil123** [SoftwareBrothers/adminjs#888]
<img width="749" alt="126195721-b6da4678-c46f-4797-83c2-f9b9eca5ec5d" src="https://user-images.githubusercontent.com/48255282/126360712-7afa1ce5-5d53-4d7e-bbb3-026022a5259c.png">

**Comment by krzysztofstudniarek** [comment]
We're currently working on not using `window` object at all, hence this issue is no longer valid.
