### ISSUE TITLE
CSS word-break neccessary

### ISSUE THREAD

**Issue by NagievR** [SoftwareBrothers/adminjs#889]
you need to add "word-break: break-word;"  property in a list to avoid text overflow
![image](https://user-images.githubusercontent.com/71175661/127734578-4d4542a5-8620-469c-9e76-1722d39b101f.png)
This thing is very annoying. can I fix css by myself?

**Comment by dziraf** [comment]
You can add your own css overrides in AdminJS `assets` config

**Comment by dziraf** [comment]
This should be included as a default css style of `TableCell` in `@adminjs/design-system@2.0.3`
