### ISSUE TITLE
after login it doesn't redirect me on /admin but refreshes the page 

### ISSUE THREAD

**Issue by handrei** [SoftwareBrothers/adminjs#891]
**Describe the bug**
The bug is that after i login on production enviornenment in cloud, it doesn't redirect me to /admin but it refreshes the page
I have to mention that on local development and staging it's working fine.
I just updated to the latest version of adminJs from adminBro@3.4 and it does the same

**Installed libraries and their versions**

 "@adminjs/express": "^4.0.0",
    "@adminjs/mongoose": "^2.0.0",
    "@adminjs/passwords": "^2.0.0",
    "@adminjs/upload": "^2.0.1",
    "adminjs": "^5.1.0",

**To Reproduce**
1. login with correct username & password

**Expected behavior**
Go to /admin instead of refreshing the login

**Comment by khanhndq** [comment]
> **Mô tả lỗi** Lỗi là sau khi tôi đăng nhập vào production enviornenment trong đám mây, nó không chuyển hướng tôi đến / admin nhưng nó làm mới trang mà tôi phải đề cập rằng về phát triển cục bộ và dàn dựng, nó hoạt động tốt. Tôi vừa cập nhật lên phiên bản mới nhất của adminJs từ adminBro@3.4 và nó cũng hoạt động như vậy
> 
> **Thư viện đã cài đặt và phiên bản của chúng**
> 
> "@ adminjs / express": "^ 4.0.0", "@ adminjs / mongoose": "^ 2.0.0", "@ adminjs / password": "^ 2.0.0", "@ adminjs / upload": " ^ 2.0.1 ", " adminjs ":" ^ 5.1.0 ",
> 
> **Để tái tạo**
> 
> 1. đăng nhập với tên người dùng và mật khẩu chính xác
> 
> **Hành vi mong đợi Truy** cập / admin thay vì làm mới đăng nhập

I have same problems . Have you handled it yet?

**Comment by nathanguigui** [comment]
Still facing the same issue
