### ISSUE TITLE
Only update modified field

### ISSUE THREAD

**Issue by WeeJeWel** [SoftwareBrothers/adminjs#893]
I've got a collection with large documents.

I only want to change a single field, e.g. `"myvalue": "foo"` to "myvalue": "bar"`.

AdminBro updates the entire document, instead of just using `$set: { "myvalue": "bar" }`.

The HTTP requests says 'payload too large'.

**Comment by dziraf** [comment]
closing in favor of https://github.com/SoftwareBrothers/adminjs/issues/430
