### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by PRF-IPA** [SoftwareBrothers/adminjs#895]
Hi,

I am looking for some more in depth documentation about how to create custom components, how to override the default components. I have gone through the docs on adminbro.com, however, in my case it was not sufficient enough to figure this out.

The app itself runs fine, but I am unable to create a custom dashboard, create custom sidebar items and custom layouts due to lacking documentation.

I have followed your Youtube serious, but it does not cover these topics and there is not really any examples out there on the internet either.

Thanks

**Comment by dziraf** [comment]
We do not have a more detailed documentation as of now and the youtube videos might be outdated (they had been created for v1 of this library). It's best if you ask specific questions in our Slack, that's where you'll likely find help the fastest
