### ISSUE TITLE
Where to use CurrentUserNav component to add a user profile option in top right header.

### ISSUE THREAD

**Issue by bhoomiagrawal** [SoftwareBrothers/adminjs#902]
I was wondering where i should import the CurrentUserNav component to use the "My Profile" option in top right header. 
and  after clicking I should redirect to my profile page where  I can see logged in user details and edit details.

**Comment by Asher-JH** [comment]
Is this still working as of version "5.7.3"?

**Comment by dziraf** [comment]
What do you mean it doesn't work? You can't see any changes or are there errors?
https://github.com/SoftwareBrothers/adminjs/blob/926799a64bc9ca40b7e763dc2adf2b4c73f3f42f/src/frontend/utils/overridable-component.ts#L1 the code for overridable components is still here

**Comment by Asher-JH** [comment]
> What do you mean it doesn't work? You can't see any changes or are there errors?
> 
> https://github.com/SoftwareBrothers/adminjs/blob/926799a64bc9ca40b7e763dc2adf2b4c73f3f42f/src/frontend/utils/overridable-component.ts#L1
> 
> the code for overridable components is still here

No errors, but no changes either, adding a console.log in the React component as well, nothing on the frontend, while doing the exact same thing for Sidebar is working fine.

**Comment by dziraf** [comment]
can you show a screenshot od the dashboard and your component?

**Comment by Asher-JH** [comment]
![Screenshot 2022-03-29 at 5 49 50 PM](https://user-images.githubusercontent.com/60175893/160584641-aef148b2-0c3e-4cac-b65e-95b866bd40ea.png)
![Screenshot 2022-03-29 at 5 50 44 PM](https://user-images.githubusercontent.com/60175893/160584824-bd7547fb-e5f5-488c-9329-d8a8b3fa3b48.png)


I just made a very basic component in hopes something would render, the same component works when using with 'SideBar'

**Comment by Asher-JH** [comment]
Theres no trace of it when inspecting the page either?

- I am using the authentication if that has anything to do with it, logged in successfully etc..
- Order of calling **AdminJS.bundle(...)** is high up before the options are passed in
-

**Comment by Asher-JH** [comment]
@dziraf hey are you able to re-create this problem on your end or is it just an error on my side?

**Comment by Kitsutsuki-98** [comment]
Hi, this is currently not working for me, I tried everything
