### ISSUE TITLE
Please add forgot password feature also in login screen

### ISSUE THREAD

**Issue by bhoomiagrawal** [SoftwareBrothers/adminjs#903]
In my project, I need to show a link to reset password "Forgot Password" on the login screen page. Please suggest me from where I can integrate this feature.

**Comment by bhoomiagrawal** [comment]
@0xfe0 Please share working code for this if you have.

**Comment by dziraf** [comment]
The login view is not editable currently as it isn't a direct part of AdminJS. You would have to create your own custom login view and login routes, then add a `forgot password` feature yourself. If you need more help on this, I suggest asking on our Slack channel.
