### ISSUE TITLE
Docs: Outdated package names (pre-rebrand)

### ISSUE THREAD

**Issue by hichemfantar** [SoftwareBrothers/adminjs#905]
**Describe the bug**
The documentation is still showing the old pre-rebrand packages which is causing people a bunch of problems especially with the modules that integrate with external libraries.

The docs are basically telling readers to install extremely old and non functional packages.

For example: **@admin-bro/nestjs** instead of **@adminjs/nestjs**

https://adminbro.com/

**Comment by dziraf** [comment]
The documentation is available under this link: https://adminjs.co

The old one will be taken down once we have a new landing page for AdminJS
