### ISSUE TITLE
redirect adminbro.com to adminjs.co

### ISSUE THREAD

**Issue by hichemfantar** [SoftwareBrothers/adminjs#906]
**Describe the bug**
The old website is still showing the old docs instead of the new adminJS docs.
**https://adminbro.com/** should take us to **https://adminjs.co**

**Comment by HexaCubist** [comment]
I can confirm that I walked into the adminbro documentation first and was using that version of this project for some time before discovering the shift. Any documentation on why the name changed?

**Comment by dziraf** [comment]
adminbro.com now redirects to adminjs.co
