### ISSUE TITLE
Docs: Missing pages in new website

### ISSUE THREAD

**Issue by hichemfantar** [SoftwareBrothers/adminjs#907]
**Describe the bug**
https://adminbro.com/ > https://softwarebrothers.github.io/adminjs-dev/

Custom adapters page is missing.
Design System page is missing.
Modules page is missing.

**Comment by dziraf** [comment]
The correct URL is: https://adminjs.co/ (links should work there)

**Comment by hichemfantar** [comment]
> The correct URL is: https://adminjs.co/ (links should work there)

The repo still links to adminbro.
![Screenshot_20210909-150750_GitHub.jpg](https://user-images.githubusercontent.com/34947993/132701388-cfd41138-8ae5-4a60-984d-6231db396f3c.jpg)
