### ISSUE TITLE
Add description to fields (fetched via model) on Admin Bro. 

### ISSUE THREAD

**Issue by vaibhavmagon** [SoftwareBrothers/adminjs#909]
**Describe the problem feature solves**
At present once you start using the panel on production it gets confusing to remember which fields on the panel do what. As of now we maintain it on confluence (which is not very intuitive).

**Describe the solution you'd like**
Ideally if we can add a (i) button with field names with a small one line description would be really helpful. More like CSS tooltiptext.

**Describe alternatives you've considered**
Having a google sheet/confluence page - non intuitive.

**Acceptance criteria**
Nothing major. This can be fetched as a separate json or can be added as an add on to the field names fetched from Models - mongoose or sequalize.

**Comment by dziraf** [comment]
This is now implemented
