### ISSUE TITLE
TypeORM one-to-one many-to-one

### ISSUE THREAD

**Issue by AndreyOsipuk** [SoftwareBrothers/adminjs#911]
The display does not work if there are connections in the typeform manytoone. Error 404

 "@admin-bro/design-system": "1.7.3",
    "@admin-bro/koa": "1.1.1",
    "@admin-bro/typeorm": "1.4.0",
    "@koa/router": "^10.1.0",
    "@types/koa": "^2.13.4",
    "@types/node": "^16.3.2",
    "admin-bro": "4.0.1",
    "dotenv": "10.0.0",
    "koa": "^2.13.1",
    "koa2-formidable": "1.0.3",
    "ts-node": "10.1.0",
    "typeorm": "0.2.34",
    "typescript": "4.3.5"

I import models from typeorm db models, in those places where there are connections, I get a 404 error
![image](https://user-images.githubusercontent.com/45951478/132682756-6ea8bd2f-46d7-4f6f-bf82-7d09dfa80003.png)
![image](https://user-images.githubusercontent.com/45951478/132682812-c539f790-001a-412a-ad4e-6da0101e157a.png)
![image](https://user-images.githubusercontent.com/45951478/132682857-e3210a1c-704e-4c90-8b89-11dc1c5b3310.png)
![image](https://user-images.githubusercontent.com/45951478/132682962-337769fa-9bfa-42cc-9fbb-cfb9429354e3.png)
![image](https://user-images.githubusercontent.com/45951478/132683323-f721711c-16da-4bc1-9b1f-59058d650fcc.png)

If I remove @ManyToOne, then everything works and there is no error

**Comment by dziraf** [comment]
I think you also need

```
@Column()
partner_id: number
```

**Comment by AndreyOsipuk** [comment]
What for? then there will be no connection

**Comment by dziraf** [comment]
The foreign key column must be specified in the entity for AdminJS to know how to load relations

**Comment by dziraf** [comment]
Closing because of lack of response

**Comment by marksantoso** [comment]
`  @ManyToOne(() => PartnerEntity, partner => partner.tokens)
  @JoinColumn({ name: 'questionnaire_id' })
  partnerEntity: PartnerEntity;

  @Column()
partner_id: number;`

TypeOrm will create only the partner_id column
AdminJs doesn't recognise JoinColumn
