### ISSUE TITLE
Demo link broken

### ISSUE THREAD

**Issue by hichemfantar** [SoftwareBrothers/adminjs#912]
**Describe the bug**
https://demo.adminjs.co/admin
Unable to access the demo.

**Comment by MarcBroers** [comment]
Current error that is returned: ERR_SSL_UNRECOGNIZED_NAME_ALERT

**Comment by Xabibax** [comment]
http://demo.adminjs.co/admin/login

will do the trick for the moment

**Comment by dziraf** [comment]
The demo link has been updated
