### ISSUE TITLE
Cannot access 'AdminBro' before initialization

### ISSUE THREAD

**Issue by talk2mat2** [SoftwareBrothers/adminjs#918]
**Describe the bug**

**Installed libraries and their versions**

* adminjs@4.0.1
* @adminjs/express@2.0.0
* @adminjs/mongoose@1.4.0
... mongo, express (whatever you think is relevant)

**To Reproduce**

**Expected behavior**

**Screenshots**

**AdminJSOptions with schema**
Paste your AdminJS config with database schema if it could be related to the issue

**Desktop (please complete the following information if relevant):**

**Smartphone (please complete the following information if relevant):**

**Additional context**

const mongoose = require('mongoose')

// even if we pass entire database, models have to be in scope
require('path-to-your/mongoose-model1')
require('path-to-your/mongoose-model2')

const run = async () => {
  const connection = await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
  })
//the issue seems to be from here-->
  const AdminBro = new AdminBro({
    databases: [connection],
    //... other AdminBroOptions
  })
  //...
}
run()

**Comment by dziraf** [comment]
Not sure what the issue is?
