### ISSUE TITLE
Role-Based Access Control on AdminBro

### ISSUE THREAD

**Issue by lfsouzabarbosa** [SoftwareBrothers/adminjs#919]
I want to implement role-based access control in my system using AdminBro.. But I need to do this out of resources, I need to restrict access to a custom page.

In resources I do this example:

resources: [
    {
      resource: Usuario,
      options: {
        parent: 'Configurações',
        properties: {
          senha: {
            type: 'password',
            isVisible: {
              list: false, edit: true, filter: false, show: false, new: true,
            },
          }
        },
        actions: {
          edit: { isAccessible: podeEditarUsuarios },
          delete: { isAccessible: podeEditarUsuarios },
          new: { isAccessible: podeEditarUsuarios },
          show: { isAccessible: podeEditarUsuarios },
          list: { isAccessible: podeEditarUsuarios },
        }
      }
    },
  ],
in pages I need to use actions.. But it doesn't work in pages.
pages: {
    customPage: {
      label: "Custom page",
      handler: async (request, response, context) => {
        return {
          text: 'I am fetched from the backend',
        }
      },
      component: AdminBro.bundle('./c6Bank'),
    },
    C6: {
      label: "Custom page",
      component: AdminBro.bundle('./c6Bank'),
    },
    Telhanorte: {
      component: AdminBro.bundle('./homepage'),
    },
    Tumelero: {
      component: AdminBro.bundle('./tumelero'),
    },

Someone knows how to implement this in pages?

**Comment by Xabibax** [comment]
I think you can manage it in the handler as the PageContext contains currentAdmin https://adminjs.co/AdminJSOptions.html#PageContext. But you will have to code it.
A hack would be to use a custom resource with custom actions for your pages to benefit from the role-based acces control of a Resource.

**Comment by lfsouzabarbosa** [comment]
how did you do this? Because I don't have any idea how to make it in the handler...
