### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by pejmanhadavi** [SoftwareBrothers/adminjs#920]
add RTL UI support for Persian, Arabic, ... language to admin panel.

**Comment by dziraf** [comment]
I think this is currently achievable, at least I've seen some examples/screenshots in our Slack

**Comment by pejmanhadavi** [comment]
This is achievable but not automatic like django admin.

**Comment by Elyasnz** [comment]
hi guys 
im currently struggling with the same issue

@dziraf 
can you provide links to these examples?

@pejmanhadavi 
how is this achievable?
