### ISSUE TITLE
Support Prisma ORM

### ISSUE THREAD

**Issue by nikolasburk** [SoftwareBrothers/adminjs#928]
**Describe the problem feature solves**

I work at [Prisma](https://github.com/prisma/prisma) and we've been seeing user requests lately that are asking for support of AdminBro in their projects that are using Prisma as an ORM.

**Describe the solution you'd like**

It would be great if Prisma could be supported in AdminBro as an additional ORM.

![image](https://user-images.githubusercontent.com/4058327/136210590-5e5736b5-bc2d-4c37-9f33-be59a2a67afa.png)

**Comment by NathBabs** [comment]
@dziraf thank you so much, I'm excited 😊

**Comment by dziraf** [comment]
@nikolasburk Hey @nikolas, quick status update, we've finished developing the beta release of Prisma adapter, and it currently undergoes our internal testing. Next week, we should be able to deliver it to you, so you can also test it with your users.
