### ISSUE TITLE
Ability to only return required fields from apis

### ISSUE THREAD

**Issue by shahidcodes** [SoftwareBrothers/adminjs#929]
TLDR: Is there anything like mongoose `.projection()` ?

Is there any way to `project` or `select` fields to return in the API? 
Right now it returns all fields available in the document. Which leaks some information I don't want my users to see. 

For example - 
Api - 
http://localhost:3001/admin/api/resources/Listing/actions/list

Returns everything in the Listing model.

**Comment by krzysztofstudniarek** [comment]
It's a duplicate with https://github.com/SoftwareBrothers/adminjs/issues/430
