### ISSUE TITLE
Form data is not getting updated

### ISSUE THREAD

**Issue by maxcharge** [SoftwareBrothers/adminjs#939]
**Describe the bug**
In in build authenticated admin-panel whenever I edit data and save the data input in the text input components is not  updated while that in date input component is.

**Installed libraries and their versions**
"@admin-bro/express": "^3.1.0",
"@admin-bro/mongoose": "^1.1.0",
"admin-bro": "^3.4.0",

**To Reproduce**
1. Go to DB collection
2. Click on EDIT
3. Edit/add/update the necessary data using the form
4. Hit Save
5. Data Edit/add/update using date component is updated in DB but data Edit/add/updated using text input component is not

**Expected behavior**
The Data modified using the form should have been updated in the DB but it is not. The Headers form-data also does not contain the modified data

**Screenshots**
![image](https://user-images.githubusercontent.com/65158511/138323696-c81680b6-f293-40bd-b49a-c76713b7c5ee.png)
Here "ReactJS was given input in form but empty string is found in headers"

**Comment by dziraf** [comment]
I'm unable to reproduce this myself, could you share your model and resource options?

**Comment by dziraf** [comment]
Closing because of lack of response
