### ISSUE TITLE
Support for Knex.js

### ISSUE THREAD

**Issue by mlevit** [SoftwareBrothers/adminjs#940]
**Describe the problem feature solves**
Support for https://knexjs.org/ on top of Sequilize and TypeORM. https://bookshelfjs.org/ runs on top of Knex and provides ORM capabilities.

**Describe the solution you'd like**
Ability to use models created using Knex.

**Describe alternatives you've considered**
Nothing else.

**Acceptance criteria**
Ability to point AdminBro at Knex models to create admin console.

**Comment by damusix** [comment]
You should probably throw ObjectionJS in there along with it. It's widely used in the HapiJS space.

**Comment by damian-pastorini** [comment]
Maybe this is useful for you, I've made my own resource for ObjectionJS / Knex, mine is pretty simple and obviously could be improved but it works perfectly:

https://github.com/damian-pastorini/reldens/tree/37abbc8ddde86e5b515ad1570ff0900243663a39/packages/admin/server

https://github.com/damian-pastorini/reldens/blob/37abbc8ddde86e5b515ad1570ff0900243663a39/packages/admin/server/objection-driver-resource.js

**Comment by wirekang** [comment]
I made an adapter that doesn't need ORM. Check out [adminjs-sql](https://www.npmjs.com/package/adminjs-sql). It uses Knex and fetch schema from INFORMATION_SHCEMA.

**Comment by dziraf** [comment]
There's currently an adapter for Objection which uses Knex internally, there's also an unofficial adapter made by @wirekang for MySQL. I'll close this issue as Bookshelf's adapter is not planned to be implemented in near future.
