### ISSUE TITLE
Admin-bro@sequelize SequelizeDatabaseError: Conversion failed when converting date and/or time from character string.

### ISSUE THREAD

**Issue by lumayara** [SoftwareBrothers/adminjs#942]
**Describe the bug**
I have a date field in some of my resources and when I try to edit (adding is fine) the ones that have a date field I get this error:
`SequelizeDatabaseError: Conversion failed when converting date and/or time from character string.`
Any idea of how to fix this?
**Installed libraries and their versions**
"@admin-bro/express": "^3.1.0",
"@admin-bro/sequelize": "^1.3.0-beta.5" // I have this version because the other ones were not working with the filter

**Comment by lumayara** [comment]
I am using Sequelize with MSSQL and it seems like Sequelize only accepts Date, Date(6) and DateOnly as types. The type in my database is DATETIME and for some reason when I edit it sends to sequelize the "YYYY-MM-DDTHH:MM:SSz" string and it has trouble converting it. My temporary solution was to change the type in my sequelize model to DATEONLY.

ModifiedOn: {
      type: DataTypes.DATEONLY,
      allowNull: true,
      defaultValue: Sequelize.Sequelize.fn('getdate')
},
For now this is what I will be using but I am trying to find a way to keep record of the time as well.

**Comment by dziraf** [comment]
Please open an issue for this here: https://github.com/SoftwareBrothers/adminjs-sequelizejs
