### ISSUE TITLE
Facing problem in authentication

### ISSUE THREAD

**Issue by Rimpi246** [SoftwareBrothers/adminjs#946]
**Describe the bug**
User is not getting logged. Everything is done according to the documentation https://adminbro.com/tutorial-rbac.html

**Installed libraries and their versions**

* @adminjs/express@3.1.0
* @adminjs/mongoose@1.1.0

![image](https://user-images.githubusercontent.com/73873611/141968632-19834cb0-2373-40d2-8161-e8e844586fcb.png)

**Comment by dziraf** [comment]
Can you show your code where you add adminjs router to your express app?

**Comment by dziraf** [comment]
Closing because of lack of response
