### ISSUE TITLE
How can I get the currently active filters on the list from a custom action?

### ISSUE THREAD

**Issue by MathiasMoralesDixtra** [SoftwareBrothers/adminjs#947]
I have the next custom action and I want to get the currently active filters on the list in my handler method:
`    exportToExcel: {
      actionType: "resource",
      handler: (req, res, context) => {
        // I need the active filter here!
        console.log("req", req);
      },
      showFilter: true,
      isVisible: true,
      icon: "Add",
      component: false,
    },`

There is any method to do that?

**Comment by dziraf** [comment]
You would probably need to create a middleware which stores last visited urls somewhere in user's session and extract all `filters.xxxxx` query params from the visited url in your handler method

**Comment by MathiasMoralesDixtra** [comment]
I decided to use Redis to save the current filter.
