### ISSUE TITLE
want to use Id instead of _id for edit and delete

### ISSUE THREAD

**Issue by lalwanikamaldev** [SoftwareBrothers/adminjs#957]
Hi Team , 

I have a issue , I am using mongo for my application and setup the adminbro , It is setup successfully but i am facing one issue on that  .

I found the route cause for it , 
The problem is with mongodb it using have primary key column as **_id** but i have a plugin in my api system which convert _id to **ID** and then it return to the UI  .

ex:- Mongo return {
**_id** : "453545ehhrhejrhjr",
Name : "AdminBro"
}

After modification my api change the data in common plug in and it return 
{
**ID** : "453545ehhrhejrhjr",
Name : "AdminBro"
}

Now my problem is where i can define that in my system primary id is ID not _Id and then i can use it ?

**Comment by lalwanikamaldev** [comment]
can any one help me on this ?

**Comment by dziraf** [comment]
you should be able to specify:

```
ID: { isId: true }
```
in your resource config

**Comment by neerajgupta2407** [comment]
@dziraf I am having the same issue. 
Tried the solution you mention but it's not working.
Is it possible to share an example.


In My case, my primary key is `id` which needs to treated as primary key instead of `_id`.
Below is my config  for User , but when i click on user, it is unable to get pk. 


`const UserResourceOptions = {
  resource: User,
  options: {
    navigation: usersNavigation,
    listProperties: ['id',  'name', 'email', 'role'],
    properties: {
      id: { isId: true }
    },
  },
};

`

**Comment by dziraf** [comment]
@neerajgupta2407 can you try to also add `_id: { isId: false }`?

**Comment by neerajgupta2407** [comment]
@dziraf Even after adding `_id: { isId: false }`, it's not working.

My updated config.

`const UserResourceOptions = {
  resource: User,
  options: {
    navigation: usersNavigation,
    listProperties: ['id', 'name', 'email', 'role'],
    properties: {
      _id: { isId: false },
      id: { isId: true },
    },
  },
};`

**Comment by dziraf** [comment]
I think I know a reason why this happens. Will try to fix soon.

**Comment by neerajgupta2407** [comment]
@dziraf Thanks for the acknowledgement.I really appreciate it.

But i have a concern now. Since i am using AdminJs as my admin panel, may i know by when you are planning to fix this ?
