### ISSUE TITLE
Unable to print the array destructed.

### ISSUE THREAD

**Issue by SwaroopS94** [SoftwareBrothers/adminjs#959]
**Describe the bug**
I am unable to print the string array destructed in the dashboard.

**Installed libraries and their versions**

"admin-bro": "^4.0.1",
"admin-bro-expressjs": "^2.1.1",
"admin-bro-mongoose": "^0.5.2",
"express": "^4.17.1",
"express-formidable": "^1.2.0",
"mongoose": "^6.0.14"

**To Reproduce**
This happens when I try to host the project using admin bro. 

**Expected behavior**
I want to see the message destructed in the dashboard.
Please help me structure my schema so that I can achieve the behavior.

**Screenshots**
<img width="1390" alt="Screenshot 2021-12-07 at 12 52 17 PM" src="https://user-images.githubusercontent.com/37957067/144984478-7773a3b5-77b5-45d0-a799-9c2fce5fa343.png">

**AdminJSOptions with schema**
new mongoose.Schema({
  userId: {
    type: String,
    required: true,
  },
  message: {
    type: [string]
  },
  channel: {
    type: String,
    required: true
  },
  created_at: {
    type: Date,
    required: true,
  },
  updated_at: {
    type: Date,
    required: true,
  }
}, {
 collection: '',
});

**Desktop (please complete the following information if relevant):**
 - OS: [Macbook OS Catalina]
 - Browser chrome
 - Version 96.0.4664.55

**Additional context**
I want to destruct and show the array instead of showing the length as mentioned on the screenshot.

**Comment by dziraf** [comment]
You have to create a custom property component for this. Displaying the array length is the default behaviour for lists. If the array had 100 elements, we wouldn't want to show them all.

**Comment by SwaroopS94** [comment]
Perfect, thanks.
