### ISSUE TITLE
Admin user and logout not showing on dashboard

### ISSUE THREAD

**Issue by kosie99** [SoftwareBrothers/adminjs#960]
**Describe the bug**
I am using buildAuthenticatedRouter and that works fine, users can log in successfully.

_const router = AdminBroExpressjs.buildAuthenticatedRouter(adminBro, {
  authenticate: async (email, password) => {......}_

The authentication function returns the email correctly, but it does not display the current logged-in user on the dashboard, hence there is also no "logout" option.

Any idea what I can be missing?

**Installed libraries and their versions**

    "@admin-bro/express": "^3.1.0",
    "@admin-bro/sequelize": "^1.2.1",
    "admin-bro": "^4.0.1",
    "admin-bro-expressjs": "^2.1.1",

**Comment by igordelorenzi** [comment]
@kosie99, did you figured out what was missing in your configuration? My setup isn't showing "logout" option too!
