### ISSUE TITLE
Allow for customization of property.label creation

### ISSUE THREAD

**Issue by DMadrid** [SoftwareBrothers/adminjs#961]
**Describe the problem feature solves**
With large nested resources the label of fields can become rather verbose. Hence, it would be nice to be able to configure adminjs to use `property.name` instead of `property.propertyPath` for the creation of property labels.

**Describe the solution you'd like**
A solution might be to add a configuration property to AdminJS to allow users to determine whether or not ot use `property.name` or `property.propertyPath`. Another solution could be to allow users to pass in a function to create labels themselves.

**Describe alternatives you've considered**
As of right now the current solution that I have is to edit `AdminJs.ACTIONS.edit.component` and change the labels manually before we pass `property` into the `PropertyType` component.

**Acceptance criteria**
- customization of property.label creation

**Comment by dziraf** [comment]
Labels can be customized through i18n and this is the preferred way of doing that:

```
  "properties": {
    "customFields.addNewItem": "Add a custom field",
    "customFields.label": "Label",
    "customFields.value": "Value"
  }
```

**Comment by hatsune-miku** [comment]
For people who are still looking for a `label` field, I would like to share my solution here, to simply add a `label` field for `Property`, though anti-pattern, but useful if you don't need i18n.

### Types

```ts
import { PropertyOptions, ResourceWithOptions } from "adminjs"

export type PropertyOptionsWithLabelTitle = PropertyOptions & {
    label?: string
}

export type ResourceWithOptionsLabelTitles = ResourceWithOptions & {
    options: {
        properties?: Record<string, PropertyOptionsWithLabelTitle>
    }
}
```

### Usage

```ts
const properties: Record<string, PropertyOptionsWithLabelTitle> = {
    file: {
        label: 'Image File',
    },
    // ...other columns
}

export const myResource: ResourceWithOptionsLabelTitles = {
    resource: MyModel,
    options: { properties: properties, id: "My Category" }
}
```

### Implementation

```ts

const resources = [
  myResource
]

const options: AdminJSOptions = {
  locale: {
    language: 'en',
    availableLanguages: ['en'],
    translations: {
      en: {
        ...makeDefaultTranslationFor(resources)
      }
    }
  },
  // ...others
}

interface Translation {
  resources: {
    // resourceId, example: "My Category"
    [resourceId: string]: {
      properties: {
        // propertyId aka the column title key, example: "file"
        [propertyId: string]: string  // id to label
      }
    }
  }
}

function makeDefaultTranslationFor(resources: ResourceWithOptionsLabelTitles[]): Translation {
  // For each resource, build a (propertyId -> label) map
  return {
    resources: resources.reduce((acc, resource) => {
      // Build the (propertyId -> label) map
      acc[resource.options.id] = {
        properties: Object.keys(resource.options.properties).reduce((acc, key) => {
          acc[key] = resource.options.properties[key].label
          return acc
        }, {})
      }
      return acc
    }, {})
  }
}
```
