### ISSUE TITLE
Nest can't resolve dependencies of th AdminModule

### ISSUE THREAD

**Issue by WECP1999** [SoftwareBrothers/adminjs#962]
Hi everyone, i was installing the necessary dependencies for run the AdminBro, but, when i want to run the project to be sure it works, throw me this error:

![image](https://user-images.githubusercontent.com/30815773/145631390-55614a91-1495-43ec-a2ce-4176a5a5a32e.png)

And this is my AppModule
![image](https://user-images.githubusercontent.com/30815773/145631686-6236e616-f2c0-4510-b41c-e8bdf6decb59.png)

Those are the versions

    "@admin-bro/nestjs": "^1.1.0",
    "@admin-bro/typeorm": "^1.4.0",
    "admin-bro": "^3.3.1",
    "@nestjs/typeorm": "^8.0.2",
    "@nestjs/cli": "^8.0.0",

I don't know if i left some dependencies or if i have to do other configurations, thanks for the support.

**Comment by dziraf** [comment]
Please update to `adminjs` and use the latest version of `@adminjs/nestjs`: https://github.com/SoftwareBrothers/adminjs-nestjs/releases/tag/v3.0.0
