### ISSUE TITLE
Nested items doesn't work with rich text editor

### ISSUE THREAD

**Issue by teuodor** [SoftwareBrothers/adminjs#963]
# Issue 

I have an object called News. This object has a field called translations and this field is an object as well. I want the field content of the object translations (News.translations.content) to be edited with a rich text editor. The problem is that this wysiwyg doesn't work as expected. When I try to type 'dog' the typing cursor jumps to the beginning and the word written will be 'god'. I tried the same editor for News.authorName and it worked as it should.

# Expected behavior 

The cursor should stay where the user puts it. 

# Schema in mongoose

const NewsSchema = new mongoose.Schema(
  &nbsp;{
   &nbsp;authorName: {
     &nbsp;&nbsp;type: String,
      &nbsp;&nbsp;required: true,
    &nbsp;},
    &nbsp;translations: [
     &nbsp;&nbsp;{
      &nbsp;&nbsp;&nbsp;language: { type: String, enum: ['en', 'de'], required: true },
       &nbsp;&nbsp;&nbsp;headline: { type: String, required: true },
        &nbsp;&nbsp;&nbsp;shortDescription: { type: String, required: true },
       &nbsp;&nbsp;&nbsp;content: { type: String, required: true },
    &nbsp;&nbsp;},
    &nbsp;],
 &nbsp;},
  { timestamps: true }
);

# Desktop

 - OS: Windows 10
 - Browser Chrome / Firefox
 - Version 96.0 / 95.0

**Comment by dziraf** [comment]
Have you tried defining properties in resource options?

```
properties: {
  translations: { type: 'mixed' },
  'translations.content': { type: 'richtext' }
}
```

just tested and it works for me

**Comment by teuodor** [comment]
it doesn't work this solution for me

**Comment by vladiulianbogdan** [comment]
I have the same problem. Did you manage to work around it?

**Comment by dziraf** [comment]
I'm leaving this open but it should be fixed in AdminJS v6/Design System v3 since we're switching from Quill to TipTap

**Comment by krzysztofstudniarek** [comment]
We've released v6 with new rich text editor. Please validate if this issue still appears on your end and reopen if it does.
