### ISSUE TITLE
Unable to show loader in admin options.

### ISSUE THREAD

**Issue by SwaroopS94** [SoftwareBrothers/adminjs#964]
I wanted to show a loader and remove the loader and reload the page once the custom bulk action is complete.

"admin-bro": "^4.0.1",
"admin-bro-expressjs": "^2.1.1",
"admin-bro-mongoose": "^0.5.2",

<img width="1418" alt="Screenshot 2021-12-15 at 11 33 21 PM" src="https://user-images.githubusercontent.com/37957067/146240783-46118394-bba0-4a33-9d8f-e14c26ba333d.png">

My Custom bulk action looks like this :- 
shortlist: {
            actionType: 'bulk',
            icon: 'View',
            isVisible: true,
            component: false,
            layout: layout,
            showInDrawer: true,
            handler: async (request, response, context) => {
              const {
                records,
                resource,
                h,
                translateMessage
              } = context;
          
              if (!records || !records.length) {
                throw new _notFoundError.default('no records were selected.', 'Action#handler');
              }
          
              if (request.method === 'get') {
                const recordsInJSON = records.map(record => record.toJSON(context.currentAdmin));
                const recordIds = records.map(record => record.params._id);
                await UserSelectedFeedback.updateMany(
                  {_id: { $in: recordIds}},
                  { $set: { shortlist: true }},
                  {multi: true}
                );
                return {
                  records: recordsInJSON,
                  redirectUrl: '/admin/resources/user_selected_feedback',
                };
              }
          
              throw new Error('method should be either "post" or "get"');
            }
          }

 - OS: [Mac OS]
 - Browser [chrome]
 - Version [96.0]
 

Let me know if there is any way to show the loader while fetching data and to reload the page once we've got the data on the same page.

**Comment by dziraf** [comment]
You'd most likely need to create a custom component or update existing default components to show a loader while the action is in progress
