### ISSUE TITLE
NestJS/TypeOrm bug on edit

### ISSUE THREAD

**Issue by mariovojnichajduk** [SoftwareBrothers/adminjs#966]
**Describe the bug**
So, I have User and UserType entity. UserType defines the role of User in database. When I want to edit User's type, after clicking 'Edit' button, it says it was successfully edited, but it adds new record in UserType table with name of the first record and gives that record to User instead of just editing User's type in User table...

**Installed libraries and their versions**

* adminjs@4.0.1
 "@adminjs/express": "^4.0.1",
 "@adminjs/nestjs": "^3.0.1",
 "@adminjs/typeorm": "^2.0.0",

**To Reproduce**
1. Go to any user
2. Click on Edit
3. Update value of UserType
4. Click on Edit

**Expected behavior**
On edit I expect it to just update that exact table instead of adding something new in other table

**Desktop (please complete the following information if relevant):**
 - OS: Windows
 - Browser: Chrome
 
![image](https://user-images.githubusercontent.com/50987282/146472703-6fb212af-33fe-4f27-8436-e7c0d2efcc6f.png)

**Comment by mariovojnichajduk** [comment]
Solution: unnecessary cascade in model

**Comment by aguirrel** [comment]
I will use this issue to add another solution to the same problem.  If you are using postgresql, if you can, instead of BIGINT for id use INT.
