### ISSUE TITLE
AWS ELB w/ https Question

### ISSUE THREAD

**Issue by matt-mythictech** [SoftwareBrothers/adminjs#968]
Trying to deploy our API to a production EC2 instance behind a ELB within AWS. Have the cookies set to secure, but login redirects back to itself. The cookie is created but I cannot access the dashboard. I assume this is an issue with the ELB proxy. 

Does anyone have an example of how to get AWS ELB to play nice?

**Comment by csabav-coder** [comment]
in my case (using express js), I had to specifically allow proxy to be able to set secure session cookies:
`this.app.set('trust proxy', 1);`
