### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by yasikrehman** [SoftwareBrothers/adminjs#974]
When i going to install the adminJs package,  it throws exception, i have attached as below

Unexpected end of JSON input while parsing near '...e":"^11.0.0","gts":"^'

**Comment by dziraf** [comment]
Could you describe this in more detail? Just tried running `yarn add adminjs` in a new project and it worked fine for me

**Comment by yasikrehman** [comment]
> Could you describe this in more detail? Just tried running `yarn add adminjs` in a new project and it worked fine for me

Just i am try to install using npm. I will check with yarn and get you back

**Comment by yasikrehman** [comment]
@dziraf Yes, while using yarn its work like charm. kindly check the issue with npm 

**Thanks**
