### ISSUE TITLE
'isTitle' works incorrectly with sequelize virtual datatypes

### ISSUE THREAD

**Issue by monosux** [SoftwareBrothers/adminjs#979]
# isTitle works incorrectly with sequelize virtual datatypes

**Description**

If recourse's property has a virtual datatype and has the 'isTitle' option set to 'true' it works incorrectly with associated resources.
It works ok for 'list' and 'show' but does not work for 'edit' and 'new'.

Looks like on 'edit' and 'new' it tries to ORDER BY virtual field. And it is not supported by sequelize.

**Code example**

Models:

```
...
ModelA.init(
    regular_filed: DataTypes.STRING,
    virtual_field: {
        type: DataTypes.VIRTUAL(DataTypes.STRING, ['regular_filed']),
        get() {
            return `Do some action: ${this.regular_filed}`;
        }
    }
)

ModelB.init(
    regular_filed: DataTypes.STRING,
    model_a: {
        type: DataTypes.INTEGER,
        references: {
            model: 'ModelA',
            key: 'id'
        }
    },
)
...
```

Recources:

```
ModelAResource = {
    ...
    properties: {
        virtual_field: {
            isTitle: true
        }
    }
    ...
}

ModelBResource = {
    ...
    properties: {
        model_a: {
            isVisible: { list: true, filter: true, show: true, edit: true }
        }
    }
    ...
}
```

In this setup 'list' and 'show' will display the right value, but 'edit' and 'new' will show an empty select field and in the console will be an error like:

```
Error
    at Query.run (.../node_modules/sequelize/dist/lib/dialects/mysql/query.js:52:25)
    at .../node_modules/sequelize/dist/lib/sequelize.js:313:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MySQLQueryInterface.select (.../node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:396:12)
    at async Function.findAll (.../node_modules/sequelize/dist/lib/model.js:1119:21)
    at async Resource.find (.../node_modules/@adminjs/sequelize/lib/src/resource.js:85:34)
    at async Object.handler (.../node_modules/adminjs/lib/backend/actions/search/search-action.js:75:21)
    at async ActionDecorator.handler (.../node_modules/adminjs/lib/backend/decorators/action/action-decorator.js:73:19)
    at async handler (.../node_modules/@adminjs/express/lib/buildRouter.js:32:30)

```

And previous SQL code will be something like that:

```
Executing (default): ... ORDER BY `ModelA`.`virtual_field` ASC LIMIT 0, 50;

```

**Installed libraries and their versions**

* adminjs@5.5.1
* @adminjs/sequelize@2.1.0
* @adminjs/express@4.0.1
* sequelize@6.3.0
* express@4.17.2

**Screenshots**

<img width="868" alt="Screen Shot 2022-01-12 at 13 25 49" src="https://user-images.githubusercontent.com/1915620/149204141-5ac28dc4-88a9-4e54-8ad4-57e05ed91b59.png">

**Comment by dziraf** [comment]
https://github.com/SoftwareBrothers/adminjs/blob/master/src/backend/actions/search/search-action.ts#L37

Search results are sorted alphabetically by it's title field. If a virtual field is a title field, it cannot be used for sorting. You can define a custom `sortBy` field in your resource options which will be used for ordering search results

**Comment by monosux** [comment]
Hi @dziraf,

Thank you a lot! That is what I was looking for 🎉

**Comment by dziraf** [comment]
You can also create a `before` hook in your ModelA's search action which will set a specific `sortBy`:
```
const setSearchDefaults = (request) => {
  const { query = {} } = request;
  const newQuery = { ...query };
  newQuery.sortBy = 'regular_field'

  request.query = newQuery;

  return request;
};
```

This is assuming you're using the most recent version of `adminjs`

**Comment by monosux** [comment]
Thanks @dziraf! 

'sortBy' is working perfect for me!
