### ISSUE TITLE
[TypeOrm] Having problems with One To Many relationship

### ISSUE THREAD

**Issue by thanhlm93** [SoftwareBrothers/adminjs#980]
Hello everyone !
Currently I am building an admin page based on adminjs platform. I'm using Typeorm and am having a One To Many relationship problem.
I have followed the instructions for One To Many relationship exactly, but the result is not showing in the UI. In contrast, the Many To One relationship displays very accurately. Currently, the One To Many relationship is not supported, right?

**Comment by Nick-CookieFirst** [comment]
I have indeed the same issue

**Comment by fandasson** [comment]
@thanhlm93 According to the [documentation](https://docs.adminjs.co/module-@adminjs_typeorm.html), only ManyToOne is currently supported. So, you seem to be right 👍.
